### ISSUE TITLE
Binary output probabilities counterintuitive (0.0-0.5 false, 0.5-1.0 true)

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#1005]
During inference\prediction, using ludwig's API, I'm seeing that the binary output probabilities is actually a rough transposition of the binary value itself, being that anything true will have a probability > 0.5, whilist anything false will be < 0.5, thus having to postprocess in my own code a "classic" confidence value that will be 0.0-1.0 in each case

if binary_output_value: # (or if raw_output_probability >= 0.5)
	binary_output_probability = (raw_output_probability - 0.5) * 2
else:
	binary_output_probability = (0.5 - raw_output_probability ) * 2

Is my interpretation correct? Is this by design?

**Comment by w4nderlust** [comment]
The output probabilities produced by a binary classifier are the probabilities of the positive class, as the probabilties of the negative class are always `1- p(pos)`. Does this clarify the issue?

**Comment by carlogrisetti** [comment]
Oh well yes and no. If you consider p and 1-p they'll never get above 0.5
Naively I expected a result comparable to a classifier, where each possible result (true or false) had its own probability ranging from 0% to 100%.

Thanks

**Comment by w4nderlust** [comment]
Probably I was not clear. There are two classes, pos and neg. the reported probability is the confidence if the classifier in pos, because being there only two classes and because probabilities sum up to one, the probability of neg is 1-p(pos). If you sum the probability of pos (p(pos)) and the probability of neg (1-p(pos)) you get p(pos)+1-p(pos)= 1.

**Comment by carlogrisetti** [comment]
Sorry, my bad explaining this: i expected there could have been a predicted positive output with, let's say, 40% confidence, which would translate to a predicted confidence value of 0.4 if it was a classifier. In this case what I interpret as true with 40% confidence is 0.7, because true with 0% confidence (like saying "it's probably true but I'm so uncertain about that it could be as well false" would be 0.5 in the current output.

If I'm looking for a false prediction, I can't evaluate confidence in the same way, I would always need to have an inverse logic for confidence on false values, since my 100% false would be 0.0, while 0% false would be 0.49/0.5

I understand the math and reasoning behind the current implementation, my point is that Ludwig could output a more "user-friendly" value, ready to be used. It's only an added convenience, not a real bug :)

**Comment by carlogrisetti** [comment]
Of course this would be a breaking change, and if this behavior was by design it has to stay like this

**Comment by w4nderlust** [comment]
I understand your point about user friendliness, but consider there is a `threshold` parameter that you can also set for binarization, by default it's 0.5 but you can set it to different values and it influences precision and recall. So the only correct way to make it more use friendly would anyway be to return both p and 1-p as two separate column, but then the prediction could still seem weird, for instance If I set the threshold to be 0.8, I would have: p(pos)=0.7, p(neg)=0.3, prediction=False.
Anyway, will think about this, and what could be a better way to return binary probabilities ;)

**Comment by carlogrisetti** [comment]
Yes, I perfectly understand.
Both approaches are valid, the current one is more technical and "deep".
I suspect that having an added (this semi-hidden) output would defy the purpose of having it noob-friendly, so I don't really know what to do :)
