### ISSUE TITLE
Preload fails with ludwig 

### ISSUE THREAD

**Issue by mangleddata** [uber/ludwig#1009]
I am using ludwig on cpu only mode on multicore system. I run as below

horovodrun -np 24 -H localhost:24 --binding-args="-bind-to socket -map-by socket" ludwig train --training_set train.csv --validation_set valid.csv --random_seed 42 -cf ${MODELFILE} --model_name ${MODELNAME} 

Now I am trying to preload the model file for a different run (all else being the same. Infact, exact same data file even).
horovodrun -np 24 -H localhost:24 --binding-args="-bind-to socket -map-by socket" ludwig train --training_set train.csv --validation_set valid.csv --random_seed 42 -cf ${MODELFILE} --model_name ${MODELNAME} -mlp results/experiment_train_model/model

I am assuming this is the correct way to make multicore (otherwise ludwig just runs on single core)

It fails with error
```
[1,2]<stderr>:    "Intra op parallelism cannot be modified after initialization.")
[1,2]<stderr>:RuntimeError: Intra op parallelism cannot be modified after initialization.
```

Any idea why preload fails ?

Will build a reproducer if needed, but want to eliminative trivial issues if I am missing something.

 - OS:  18.04.1-Ubuntu
- Python version 3.7.6
- Ludwig version
- Tensorflow 2.3.1

**Comment by tgaddair** [comment]
Hey @mangleddata, thanks for reporting this.  This does look like a bug on our side when specifying the `model_load_path`.  The root of the problem, I suspect, is that we are no plumbing the parameters [here](https://github.com/uber/ludwig/blob/master/ludwig/train.py#L162), resulting in attempts to initialize TensorFlow with different parameters.  I'll take a look at this today.

**Comment by tgaddair** [comment]
Hey @mangleddata, can you try #1011 and let me know if it addresses your issue?

**Comment by mangleddata** [comment]
@tgaddair Thanks for fixing it. I am able to preload now.

**Comment by mangleddata** [comment]
One related question. I have the following scenario
Run 1: Have features_{0..100} and have a trained model.
Run 2: I now have a new feature feature_101 added to the same data set and have a new features added to the model file.  Now using the pretrained model in run 1 for run 2 still seems to run - but from what I could tell, it drops the newly added feature (I don't see the feature in the input_features array in description.json)

Is this expected ?
