### ISSUE TITLE
Set as Input feature

### ISSUE THREAD

**Issue by donfour10** [uber/ludwig#1018]
**Describe the bug**
I have a Set of categories as one input_feature. When I change the order of these within the set, the probability of the prediction changes.

I am not sure if I misunderstood the "set" but this surprises me. 

**To Reproduce**

This is one of my input features:
`        {
            'name': 'company_category_list',
            'type': 'set',
            'preprocessing': {
                'format': 'comma'
            }
        }`
For example a value for this column looks like this: "Artificial Intelligence,Machine Learning,Hospital"

Thre are more numerical and category input features.

My output feature looks like this:
`'output_features': [
        {
            'name': 'label',
            'type': 'binary'
        }
    ]`

**Expected behavior**
When i predict and the look in the probability I want that "Artificial Intelligence,Machine Learning,Hospital" will give the same probability as "Machine Learning,Hospital,Artificial Intelligence", because the categories are completely the same but that is not the case.

I look in it like that:
`prediction = model.predict(dataset=test_df, gpus=[0])`
`print(prediction[0]['label_probabilities'])`

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 19.10
- Python 3.7.5
- Ludwig 0.3.1

**Additional context**
As I said it could be that i misunderstood the "set" feature but maybe then you can help me to use it correctly.

**Comment by tgaddair** [comment]
Hey @donfour10, can you try changing the preprocessing parameter `format` to `tokenizer` like so:

```
'preprocessing': { 'tokenizer': 'comma' }
```

Looks like the documentation is out of date, as this parameter was changed in the most recent version.

**Comment by donfour10** [comment]
Thank you very much! Worked now ;)
