### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by AUnicornWithNoLife** [uber/ludwig#1047]
**Describe the bug**
Ludwig fails to install on macOS

**To Reproduce**
1. pip3 install ludwig

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
correctly installs ludwig

**Screenshots**
Output:
`Collecting ludwig
  Using cached ludwig-0.3.1.tar.gz (221 kB)
  Using cached ludwig-0.3.tar.gz (212 kB)
  Using cached ludwig-0.2.2.8.tar.gz (174 kB)
  Using cached ludwig-0.2.2.7.tar.gz (172 kB)
  Using cached ludwig-0.2.2.6.tar.gz (172 kB)
  Using cached ludwig-0.2.2.5.tar.gz (170 kB)
  Using cached ludwig-0.2.2.4.tar.gz (167 kB)
  Using cached ludwig-0.2.2.3.tar.gz (170 kB)
  Using cached ludwig-0.2.2.2.tar.gz (167 kB)
  Using cached ludwig-0.2.2.tar.gz (170 kB)
  Using cached ludwig-0.2.1.tar.gz (164 kB)
  Using cached ludwig-0.2.tar.gz (157 kB)
  Using cached ludwig-0.1.2.tar.gz (134 kB)
  Using cached ludwig-0.1.1.tar.gz (129 kB)
  Using cached ludwig-0.1.0.tar.gz (121 kB)
ERROR: Cannot install ludwig==0.1.0, ludwig==0.1.1, ludwig==0.1.2, ludwig==0.2, ludwig==0.2.1, ludwig==0.2.2, ludwig==0.2.2.2, ludwig==0.2.2.3, ludwig==0.2.2.4, ludwig==0.2.2.5, ludwig==0.2.2.6, ludwig==0.2.2.7, ludwig==0.2.2.8, ludwig==0.3 and ludwig==0.3.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    ludwig 0.3.1 depends on tensorflow>=2.2
    ludwig 0.3 depends on tensorflow>=2.2
    ludwig 0.2.2.8 depends on tensorflow==1.15.3
    ludwig 0.2.2.7 depends on tensorflow==1.15.3
    ludwig 0.2.2.6 depends on tensorflow==1.15.2
    ludwig 0.2.2.5 depends on tensorflow==1.15.2
    ludwig 0.2.2.4 depends on tensorflow==1.15.2
    ludwig 0.2.2.3 depends on tensorflow==1.15.2
    ludwig 0.2.2.2 depends on tensorflow-gpu==1.15.2
    ludwig 0.2.2 depends on tensorflow-gpu==1.15.2
    ludwig 0.2.1 depends on tensorflow==1.14.0
    ludwig 0.2 depends on tensorflow==1.14.0
    ludwig 0.1.2 depends on tensorflow==1.13.1
    ludwig 0.1.1 depends on tensorflow==1.13.1
    ludwig 0.1.0 depends on tensorflow>=1.12

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - 11.0.1
- python - 3.8.2
- 0.3.1 - attempted install

**Additional context**

**Comment by tgaddair** [comment]
Hey @AUnicornWithNoLife, looks like you're not able to install tensorflow.  You may need to try upgrade `pip` and `setuptools`:

```
pip3 install --upgrade pip3
pip3 install --upgrade setuptools
```

If that doesn't work, please try running `pip3 install tensorflow` before `pip3 install ludwig` and let me know how it goes.

**Comment by AUnicornWithNoLife** [comment]
when i try

pip3 install --upgrade pip3
pip3 install --upgrade setuptools

it will install setup tools, but says it cannot find a matching version for pip, and then will give the same error for tensor flow.

**Comment by tgaddair** [comment]
Hey @AUnicornWithNoLife, can you share the exact error message?  Sounds like the problem lies in your Python environment.  I would suggest creating a virtualenv.

**Comment by AUnicornWithNoLife** [comment]
thank you,

managed to get it working with a virtual env

**Comment by tgaddair** [comment]
Great!  Glad you got it working.
