### ISSUE TITLE
model_defintion as a sting when using api

### ISSUE THREAD

**Issue by pangka** [uber/ludwig#109]
Can model definitions be a string?
Using this code:
model_definition = '{input_features: [{name: CumGPA, type: numerical}], output_features: [{name: Target, type: binary}]}'
ludwig_model = LudwigModel(model_definition)
I get this error:
 File "C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\site-packages\ludwig\utils\defaults.py", line 126, in merge_with_defaults
    model_definition.get('preprocessing', {})
AttributeError: 'str' object has no attribute 'get'

I must be reading the api documentation incorrectly, but I don't see where.

**Comment by w4nderlust** [comment]
No model definition is a dictionary. Just do `model_definition = yaml.load(model_definition_string)`.

**Comment by pangka** [comment]
Thank you.
