### ISSUE TITLE
Question regarding: model.train(dataframe)

### ISSUE THREAD

**Issue by pangka** [uber/ludwig#110]
I'm using pandas to import a csv file :
training_data = pd.read_csv(csv_file_path)

Yet when I use the ludwig api:
train_stats = model.train(data_df=training_data)

I get this error:
FileNotFoundError: [WinError 2] The system cannot find the file specified

I'm misunderstanding the api examples. My understanding is one can specify either a csv file path or a dataframe, yet am unable to get either to work properly.

**Comment by w4nderlust** [comment]
It looks like that's a pandas error, you are loading the wrong file, doesn't seem to be a Ludwig error. Please make sure of that, if you able to load the csv correctly and look at it's content before callin `model.train()` then post here a reproducible result and I will look into it.

**Comment by pangka** [comment]
Doesn't appear to be a pandas issue. I installed and ran another automl package in the same environment, on the same data,  and it worked fine. Here's my session after the csv import until it crashes in the subprocess.py file:

>from ludwig import LudwigModel

>model_definition_string = '{input_features: [{name: Grants, type: numerical}, {name: Loans, type: numerical}, {name: CumGPA, type: numerical}, {name: Level, type: category}, {name: Load, type: category}, {name: LowIncome, type: category}], output_features: [{name: Target, type: binary}]}'

>model_definition = yaml.load(model_definition_string)

>model = LudwigModel(model_definition)

>train_stats = model.train(data_df=data)

>Traceback (most recent call last):

  File "<ipython-input-11-071512b12528>", line 1, in <module>
    train_stats = model.train(data_df=data)

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\site-packages\ludwig\api.py", line 417, in train
    random_seed=random_seed)

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\site-packages\ludwig\utils\misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "C:\Users\name\AppData\Local\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by w4nderlust** [comment]
the variable ‘data’ is not defined in your snippet of code.

Plus please format and indent your code and error correcly otherwise it is unreadable.

Please provide a fully replicable example, including a sample of the data or an equivalent, what os you are running on and all the details that are needed, otherwise it is difficult for us to try to solve your issue.

**Comment by pangka** [comment]
Windows 10 Pro
Python 3.6.7
Conda 4.6.3

I'm using the iris data set imported with pandas as a (150, 5) DataFrame.

The code I'm testing Ludwig with is:
------------------------------------
import pandas as pd
import yaml

path = 'C:/tf_data/iris.csv'
data = pd.read_csv(path)

from ludwig import LudwigModel

model_definition_string = '{input_features: [{name: sepal_length, type: numerical}, {name: sepal_width, type: numerical}, {name: petal_length, type: numerical}, {name: petal_width, type: numerical}], output_features: [{name: species, type: category}]}'

model_definition = yaml.load(model_definition_string)

model = LudwigModel(model_definition)
train_stats = model.train(data_df=data)

The error thrown is:
---------------------

File  ~\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by w4nderlust** [comment]
I need the full stack of the error to figure out where it happens. Please provide it. Also please run `data.describe()` before importing Ludwig and report on what it prints.

**Comment by pangka** [comment]
data.describe() prints various statistics describing the iris numerical data; count, mean, std, min, 25%, 50%, 75%, max.

The full stack error is:
---------------------
Traceback (most recent call last):

  File "<ipython-input-10-071512b12528>", line 1, in <module>
    train_stats = model.train(data_df=data)

  File ~\Continuum\anaconda3\envs\ludwig\lib\site-packages\ludwig\api.py", line 417, in train
    random_seed=random_seed)

  File ~\Continuum\anaconda3\envs\ludwig\lib\site-packages\ludwig\utils\misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0

  File ~\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File ~\Continuum\anaconda3\envs\ludwig\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File ~\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File ~\Continuum\anaconda3\envs\ludwig\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by w4nderlust** [comment]
I believe this has to do with the attempt to get the git hash, try to use the current master branch as i already solved an issue related to this.

**Comment by pangka** [comment]
I found the closed issue referenced and used the stop-gap code addition mentioned therein. Look forward to upcoming releases. Thank you.
