### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec

### ISSUE THREAD

**Issue by DougSilkstonekk** [uber/ludwig#113]
Hi guys - Getting thrown the following error:
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 4: unexpected end of data

Occurs whilst using the below command with 
> ludwig experiment --data_csv trainers.csv --model_definition_file trainers_model.yaml

trainers_model.yaml
`input_features:
    -
        name: Image
        type: image
        encoder: stacked_cnn

output_features:
    -
        name: Brand
        type: category`

CSV is in format

randomImageofsneaker1.png / Adidas 
randomImageofsneaker2.png / Vans
randomImageofsneaker3.png / Nike
randomImageofsneaker4.png / Nike

Set of files I'm using is available here. Any ideas?
[Ludwig UTF8 Error.zip](https://github.com/uber/ludwig/files/2874640/Ludwig.UTF8.Error.zip)

Full error from console here - 
`PS E:\Web Projects\LUDWIG UBER> ludwig experiment --data_csv trainers.csv --model_definition_file trainers_model.yaml
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Experiment

Experiment name: experiment
Model name: run
Output path: results\experiment_run_0

ludwig_version: '0.1.0'
command: ('C:\\Users\\GODZILLA\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\ludwig '
 'experiment --data_csv trainers.csv --model_definition_file '
 'trainers_model.yaml')
dataset_type: 'trainers.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'encoder': 'stacked_cnn',
                              'in_memory': True,
                              'name': 'Image_url',
                              'should_resize': False,
                              'tied_weights': None,
                              'type': 'image'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'class_distance_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'Brand',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': 10000,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': False},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {'missing_value_strategy': 'backfill'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 3,
                    'epochs': 200,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}

Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Traceback (most recent call last):
  File "pandas\_libs\parsers.pyx", line 1169, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1299, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1315, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1553, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 4: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GODZILLA\AppData\Local\Programs\Python\Python36\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\experiment.py", line 548, in cli
    experiment(**vars(args))
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\experiment.py", line 234, in experiment
    random_seed=random_seed
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\data\preprocessing.py", line 457, in preprocess_for_training
    random_seed=random_seed
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\data\preprocessing.py", line 54, in build_dataset
    dataset_df = read_csv(dataset_csv)
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\ludwig\utils\data_utils.py", line 46, in read_csv
    df = pd.read_csv(data_fp, header=header)
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\pandas\io\parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\pandas\io\parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "c:\users\godzilla\appdata\local\programs\python\python36\lib\site-packages\pandas\io\parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 991, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1123, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas\_libs\parsers.pyx", line 1176, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1299, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1315, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1553, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 4: unexpected end of data`

**Comment by Nasnl** [comment]
I had the same. Then instead of creating a CSV with MS Office, I created it in Open Office with the appropriate settings for CSV and the probems vanished. 'CSV' is not always UTF-8 CSV.

**Comment by DougSilkstonekk** [comment]
Took @Nasnl 's advice and got past that user error. Thanks!

**Comment by w4nderlust** [comment]
We have to specify in the dicumentation that datasets need to be encoded in utf8.
