### ISSUE TITLE
Insufficient input parameters

### ISSUE THREAD

**Issue by uriva** [uber/ludwig#116]
The following code yields:

> Insufficient input parameters

What am I doing wrong here? (Sorry if this is obvious... the docs are a bit sparse when using the python API).

```
import ludwig

model = ludwig.LudwigModel(
    model_definition={
        "input_features": [{"name": "text", "type": "text", "encoder": "rnn"}],
        "output_features": [{"name": "is_name", "type": "binary"}],
    }
)

positive = ["james", "ruth"]
negative = ["house", "flower"]

model.train(
    data_dict={
        "text": positive + negative,
        "is_name": [True] * len(positive) + [False] * len(negative),
    }
)
```

**Comment by w4nderlust** [comment]
Can you provide the full stack trace please?

**Comment by uriva** [comment]
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-5-ebd8e4622545> in <module>
>      12     data_dict={
>      13         "text": positive + negative,
> ---> 14         "is_name": [True] * len(positive) + [False] * len(negative),
>      15     }
>      16 )
> 
> ~/env-airbud/lib/python3.7/site-packages/ludwig/api.py in train(self, data_df, data_train_df, data_validation_df, data_test_df, data_csv, data_train_csv, data_validation_csv, data_test_csv, data_hdf5, data_train_hdf5, data_validation_hdf5, data_test_hdf5, train_set_metadata_json, model_name, model_load_path, model_resume_path, skip_save_progress_weights, dataset_type, skip_save_processed_input, output_directory, gpus, gpu_fraction, random_seed, logging_level, debug, **kwargs)
>     467                 preprocessing_params=
>     468                 self.model_definition['preprocessing'],
> --> 469                 random_seed=random_seed)
>     470 
>     471         logging.info('Training set: {0}'.format(training_set.size))
> 
> ~/env-airbud/lib/python3.7/site-packages/ludwig/data/preprocessing.py in preprocess_for_training(model_definition, dataset_type, data_df, data_train_df, data_validation_df, data_test_df, data_csv, data_train_csv, data_validation_csv, data_test_csv, data_hdf5, data_train_hdf5, data_validation_hdf5, data_test_hdf5, train_set_metadata_json, skip_save_processed_input, preprocessing_params, random_seed)
>     556 
>     557     else:
> --> 558         raise RuntimeError('Insufficient input parameters')
>     559 
>     560     replace_text_feature_level(
> 
> RuntimeError: Insufficient input parameters
>

**Comment by w4nderlust** [comment]
I see, so at the moment `data_dict` is not supported as a viable way to provide data to `train()` as you can see [here](https://uber.github.io/ludwig/api/#train). We will add it in next releases.
For the time being please first create a dataset with
```
dataset_df = pd.DataFrame({
    "text": positive + negative,
    "is_name": [True] * len(positive) + [False] * len(negative),
})
```
and then use it for training;
```
model.train(data_df=dataset_df)
```

A full example for your problem is the following:
```
import logging
import pandas as pd
from pprint import pprint

import ludwig

model = ludwig.LudwigModel(
    model_definition={
        "input_features": [{"name": "text", "level": "char", "type": "text", "encoder": "rnn"}],
        "output_features": [{"name": "is_name", "type": "binary"}],
        "training": {"epochs": 20}
    }
)

positive = ["james", "ruth"]
negative = ["house", "flower"]
dataset_df = pd.DataFrame({
    "text": positive + negative,
    "is_name": [True] * len(positive) + [False] * len(negative),
})

stats = model.train(
    data_train_df=dataset_df
)
pprint(stats)
```

I added `level: char` otherwise each single word is a token, plus I also reduced the number of epochs.
Make sure you are using the latest master commit version of Ludwig when trying it.
To install it first uninstall Ludwig, then:
```
pip install git+https://github.com/uber/ludwig.git@master
```
