### ISSUE TITLE
Training Accuracy 90%, Prediction Accuracy 0.3% ?

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [uber/ludwig#123]
Hey There, great tool! Have a question though that I can't seem to figure out. 

I trained a model using a sample data set for banking information which takes in customer demographics and has a binary "purchase" column of whether they purchased a certificate of deposit or not (1 or 0). Trying to make a prediction for future customers on that column based on the same.

I trained my model and have a 90% accuracy after 20 epochs.

![screen shot 2019-02-19 at 11 47 17 am](https://user-images.githubusercontent.com/14937052/53032336-ab695580-343c-11e9-886b-e422e6e1d879.png)

But when I run a predict on a single datapoint with the **--only_predictions** flag. I get a prediction of "False" which is correct (I just used one of the data points from the set for a manual test), **but I got a probability of 0.0033177494 which is very low for a 90% testing accuracy**

![screen shot 2019-02-19 at 11 49 47 am](https://user-images.githubusercontent.com/14937052/53032476-ebc8d380-343c-11e9-800a-8611c6bd90ae.png)

**Am I doing something wrong or misinterpreting something?**

train.csv

```
age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,purchase
44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,210,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
```

predict.csv (same thing, just without the 'purchase' column)
```
age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed
56,unemployed,married,basic.9y,unknown,no,yes,telephone,may,tue,43,2,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191
```

**Comment by CMobley7** [comment]
So, 0.0033177494 is the probability that the example provided is from positive class. I believe Ludwig threshold is 0.5; so, anything less than 0.5 will be predicted as the negative class, while anything above 0.5 will be predicted as the positive class. This number doesn't relate to accuracy.

**Comment by w4nderlust** [comment]
@CMobley7 yes, Ludwig sets the threshold to 0.6 by default, but you can change it if you want, it's a configurazion parameter (like almost everything else ;) ).

@JohnAntonusMaximus the correct way to interpret it is "What's the likelihood of this datapoint being positive". Which means the model is pretty convinced that this datapoint is false. Think about it as `1-P(positive)`, which means that the model is outputting a 0.997 probability of this datapoint to be false. This is the way binary outputs are supposed to work :) Closing the issue,
