### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by tboo** [uber/ludwig#143]
Hi,

thanks for constantly fixing issues. Here's another one.

I want to distribute my training onto 2 GPUs on a single machine. I did install Horovod and the required packages successfully.

Now, I thought that 

```
ludwig train --data_csv annotations_350x150.csv --model_definition "[...]" -uh -g 0,1
```
would allow for that. Instead I get an error:

```
ludwig train: error: argument -g/--gpus: invalid int value: '0,1'
```
I can use the same synthax (-g 1 or -g 0) to run the training on either card. So the devices are all properly visible. 

Any help is appreciated.

**Comment by msaisumanth** [comment]
@tboo  Thanks for raising the issue. Try: 

```code
ludwig train --data_csv annotations_350x150.csv --model_definition "[...]" -uh -g 0 1
```

That should fix it. [Reference](https://docs.python.org/3/library/argparse.html) 

Please close the issue if that solves your problem.

**Comment by w4nderlust** [comment]
@tboo aso be sure to run through `mpirun`. Let us know if you have further issues.

**Comment by tboo** [comment]
Thanks for the quick response. I was just confused because the [documentation](https://uber.github.io/ludwig/user_guide/#train) stated, that the GPU list are the IDs separated by comma. This now works but I found that at least in our environment `mpirun` (v 3.0.0) just overwrites the `-g` arguments and as stated correctly running ludwig w/o `mpirun` fails for distributed training making `-g` somewhat obsolete.

Other than that thanks for the package. It was very smooth sailing to set up distributed training on a GPU cluster. Thanks a lot for that. Great work.

**Comment by w4nderlust** [comment]
You are right, there's a discrepancy between the documentation and the implementation. We either have to change one or the other. Thanks for noticing it. And thanks you for your comments, much appreciated. Let me know if you encounter problems, Ludwig is still young and any suggestion for improvement and error report is greatly appreciated to make it more robust.
