### ISSUE TITLE
Example datasets with configuration files for text and image features to use as a template.

### ISSUE THREAD

**Issue by shyamalschandra** [uber/ludwig#144]
Could the developers of Ludwig provide example datasets (text, image) for all the different types of executions for the package?

**Comment by shyamalschandra** [comment]
Do you also have the output so I can do a diff between the resulting classification for the training and testing pair?

**Comment by msaisumanth** [comment]
@shyamalschandra We are working on adding some examples where you can download the data.  But, currently we are prioritizing bug fixes. If you just want to look at how you can use some of the features in Ludwig, please refer to the integration tests as they have several types of model definitions.

**Comment by shyamalschandra** [comment]
How long before if can be done?

**Comment by w4nderlust** [comment]
@shyamalschandra we are prioritizing fixing bugs at the moment. After we are done with that we will focus on feature requests, we still have to prioritize them.

**Comment by shyamalschandra** [comment]
@w4nderlust: It has been 13 days and nothing has happened.  Can anyone from Uber respond?

**Comment by w4nderlust** [comment]
@shyamalschandra as I already told you, we are prioritizing other things, in particular fixing bugs. Your request will eventually be addressed, we can't give any timeframe for that, but consider it is low priority, so it may take a while.

**Comment by shyamalschandra** [comment]
@w4nderlust: Why do you think it is low priority?

**Comment by w4nderlust** [comment]
Because the set of examples that are already there, albeit without specific datasets, is already sufficient for the majority of people to start working with Ludwig. Having more examples with specific datasets and also notebooks or colabs would be great, but there's more tasks than people to do them at the moment.
I would gladly accept help and PR from the community on this (come people are already contributing in this sense.

**Comment by shyamalschandra** [comment]
Yes, a research colab with examples would be great, first step to take for clarification.

**Comment by w4nderlust** [comment]
I think the  notebooks and code in the `examples` section actually address this issue, so I'm closing.
