### ISSUE TITLE
OSError: Can't prepare for writing dat

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#150]
F:\ezjoiner>ludwig experiment --data_csv eng_incompleteness2.csv --model_definit
ion_file sent_complete_model_definition_continuous.yaml
f:\programdata\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: C
onversion of the second argument of issubdtype from `float` to `np.floating` is
deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type
`.
  from ._conv import register_converters as _register_converters
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Experiment

Experiment name: experiment
Model name: run
Output path: results\experiment_run_1

ludwig_version: '0.1.0'
command: ('F:\\ProgramData\\Anaconda3\\Scripts\\ludwig experiment --data_csv '
 'eng_incompleteness2.csv --model_definition_file '
 'sent_complete_model_definition_continuous.yaml')
dataset_type: 'eng_incompleteness2.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'English',
                              'tied_weights': None,
                              'type': 'text'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'Incompleteness',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical',
                               'weight': 1}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': 10000,
                                    'missing_value_strategy': 'fill_with_const',

                                    'most_common': False},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_cons
t'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_co
nst',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {'missing_value_strategy': 'backfill'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_c
onst'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_co
nst',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',

                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const'
,
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_
const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 3,
                    'epochs': 200,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}

Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading NLP pipeline
f:\programdata\anaconda3\lib\site-packages\ludwig\features\numerical_feature.py:
63: FutureWarning: Method .as_matrix will be removed in a future version. Use .v
alues instead.
  np.float32).as_matrix()
Writing dataset
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "f:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\ProgramData\Anaconda3\Scripts\ludwig.exe\__main__.py", line 9, in <mo
dule>
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 86, in m
ain
    CLI()
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 64, in _
_init__
    getattr(self, args.command)()
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 67, in e
xperiment
    experiment.cli(sys.argv[2:])
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 5
48, in cli
    experiment(**vars(args))
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 2
34, in experiment
    random_seed=random_seed
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\data\preprocessing.py"
, line 461, in preprocess_for_training
    data_utils.save_hdf5(data_hdf5_fp, data, train_set_metadata)
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\utils\data_utils.py",
line 99, in save_hdf5
    dataset = h5_file.create_dataset(key, data=value)
  File "f:\programdata\anaconda3\lib\site-packages\h5py\_hl\group.py", line 106,
 in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "f:\programdata\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 14
3, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py\_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py\_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't prepare for writing data (file write failed: time = Thu Feb 28 02
:52:33 2019
, filename = 'eng_incompleteness2.hdf5', file descriptor = 4, errno = 22, error
message = 'Invalid argument', buf = 000000BB97EE4031, total write size = 1477792
7695, bytes this sub-write = 2147483647, bytes actually written = 18446744073709
551615, offset = 32212256753)

**Comment by msaisumanth** [comment]
@jiangweiatgithub I think this is because of some data format issues. So, could you please share your model definition?

**Comment by jiangweiatgithub** [comment]
Sure, it is:
input_features:
    -
        name: English
        type: text
        level: word

output_features:
    -
        name: Incompleteness
        type: numerical

And some sample csv data:
This,3
sentence is incomplete,-1
This sentence,2
is incomplete,-2
This sentence is,1
incomplete,-3
This sentence is complete,0

Now I just realized that i have been running two different experiments at the same time, from the same folder. Is this the reason for the 2nd one? (The 1st one is still running.)

**Comment by msaisumanth** [comment]
Yeah, that's a possibility because of the way the folder structures are used by Ludwig. Please confirm that solved your issue.

**Comment by w4nderlust** [comment]
So if you are running two experiments at the same time on the same dataset, wait for the first experiment to finish writing the hdf5 file. Otherwise they'll try to write the same file at the same time. Let us know if that solves the problem.

**Comment by jiangweiatgithub** [comment]
Not really. I was running two totally different experiments at the same time - different csv and differe yaml, thought they are in the same folder.

**Comment by w4nderlust** [comment]
That should work fine. Could it be the case that you dataset is huge and you are running out of space on disk? Or in general any problem related to writing files to disk like permissions?

**Comment by jiangweiatgithub** [comment]
Yes - it has started training as expected. 😊

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Piero Molino <notifications@github.com>
发送时间: Friday, March 1, 2019 2:44:31 PM
收件人: uber/ludwig
抄送: jiangweiatgithub; Mention
主题: Re: [uber/ludwig] OSError: Can't prepare for writing dat (#150)


So if you are running two experiments at the same time on the same dataset, wait for the first experiment to finish writing the hdf5 file. Otherwise they'll try to write the same file at the same time. Let us know if that solves the problem.

**Comment by w4nderlust** [comment]
Oh that's great, closing this issue. Just to be sure, what was the the source of the problem to begin with and what solved it?
