### ISSUE TITLE
Time series prediction for n steps

### ISSUE THREAD

**Issue by stevevaius77** [uber/ludwig#154]
Is there any way to use single column series data to predict next n steps ahead with some presetting method like gru/lstm? Or at least can be a feature for next release?

**Comment by w4nderlust** [comment]
That's exactly what the[ timeseires example](url
https://uber.github.io/ludwig/examples/#time-series-forecasting) does.

**Comment by kishorkumar89** [comment]
Please provide the correct URL its not working

**Comment by w4nderlust** [comment]
updated to the current url
