### ISSUE TITLE
--model_resume_path FileNotFoundError

### ISSUE THREAD

**Issue by chaoannricardo** [uber/ludwig#155]
I'm trying to enhance the accuracy of prediction by an existing modle.
However, after inserting `--model_resume_path results/experiment_run_51/model/` , Ludwig just stopped with following error message:

>  FileNotFoundError: [Errno 2] No such file or directory: 'results/experiment_run_51/model/model/training_progress.p

Am I doing anything wrong with the command?
Many thanks!

**Comment by msaisumanth** [comment]
Try: 
--model_resume_path results/experiment_run_51/

**Comment by chaoannricardo** [comment]
Thanks for the comment. I've tried the command, 
(both `--model_resume_path results/experiment_run_51/` and 
`--model_resume_path results/experiment_run_51`)
the command does work, but with following message, the process ended up early/
Though it does not show up with an error message, I doubt that whether the application had functioned
 correctly. (I've attached the screenshot below.)

> ╒══════════╕                                                                                                                                                 
│ TRAINING │                                                                                                                                                 
╘══════════╛                                                                                                                                                                                                                                                                                                              
2019-03-02 13:18:22.442399: I tensorflow/core/platform/cpu_feature_guard.cc:141] 
........
Resuming training of model: results/experiment_run_51/model                                                                                                  WARNING:tensorflow:From /home/ricardo/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.                                                                    
.......                                                                                                                                                                                                                             
Finished: experiment_run                                                                                                                                     Saved to: results/experiment_run_51/                       
<img width="960" alt="screenshot1" src="https://user-images.githubusercontent.com/47705950/53677686-0f1e3900-3cef-11e9-9311-1aadc08a4e89.PNG">

**Comment by w4nderlust** [comment]
Please read this issue that explains the difference between load and resume https://github.com/uber/ludwig/issues/71 . The documentation states it pretty clearly too. Closing for now, feel free to reopen if that doesn't solve your issue.
