### ISSUE TITLE
Inconsistent arguments for 'get_experiment_description'

### ISSUE THREAD

**Issue by graytowne** [uber/ludwig#159]
It seems when calling 'get_experiment_description' in ```train.py```([link](https://github.com/uber/ludwig/blob/master/ludwig/train.py#L200)), the argument order is inconsistent with the one from function definition ([link](https://github.com/uber/ludwig/blob/master/ludwig/utils/misc.py#L29)).

**Comment by w4nderlust** [comment]
Your PR solves the issue, thanks!
