### ISSUE TITLE
How to check if ludwig is installed correctly?

### ISSUE THREAD

**Issue by dhariyalbhaskar** [uber/ludwig#168]
I'm trying to install ludwig, however I wish to check if it is installed properly before moving ahead. Please let me know.

**Comment by tmontana** [comment]
In python:

from ludwig import LudwigModel

check there are no error messages

**Comment by msaisumanth** [comment]
@dhariyalbhaskar You can also run the integration tests. Check the [developer guide](https://uber.github.io/ludwig/developer_guide/#tests)
