### ISSUE TITLE
how prediction model works

### ISSUE THREAD

**Issue by KattaOmkareshwar** [uber/ludwig#171]
I've just now seen the example of movie rating prediction. But on what algorithms the prediction model is going to work. How can we compare the accuracy of different models?

**Comment by msaisumanth** [comment]
@KattaOmkareshwar Based on your input and output features, Ludwig selects default encoders, decoders and combiner.  If you want to specify a particular type of model, you can choose them in the model definition. Check some examples [here](https://uber.github.io/ludwig/examples/).

**Comment by w4nderlust** [comment]
To compare different models, you can compare their measures and use [visualizations](https://uber.github.io/ludwig/user_guide/#visualizations) to do that too.
