### ISSUE TITLE
ludwig output & yaml creation

### ISSUE THREAD

**Issue by skw1990** [uber/ludwig#177]
Hi, 

Is there a simpler way to create .yaml file so that it can be used to train data with hundreds features? Sorry if this sounds like a trivial question. 

Also, for example of titanic dataset (binary classification), is it possible to check AUC?

Thanks.

**Comment by w4nderlust** [comment]
@skw1990 the roc_auc is already reported.
Regarding creating the yaml, if you have thousands of features you can write your own little python script to do it.
Cheers
