### ISSUE TITLE
Multi-input (image and continuous/categorical variables) models on Colab

### ISSUE THREAD

**Issue by AnthonyBozzo** [uber/ludwig#178]
Hello, 

I have a project which combines both image data (Xrays) and clinical variables (both continuous and categorical) in a binary classification task. I would like to set this up in LUDWIG. 

Based on the examples from the User Manual and Example page, it seems that the CSV file should contain the addresses of the images, and then all the other variables of interest can be stored in subsequent CSV columns. 

1) Can we clarify if this is the best method for Google Colab? What do the addresses look like for the files stored on the mounted gdrive? Is there a way to point to these files without including their address in a CSV column?

2) Any considerations for the combiner?

Thanks!

**Comment by ydudin3** [comment]
@AnthonyBozzo - we haven't developed / tested anything with Google Colab. All the functionality for image classification examples is for running ludwig locally on your laptop. In this case CSV should contain either absolute file paths for the images or relative ones to the path of the CSV. Possibly it will work with Google Colab but ones needs to test and I'm not sure how paths are managed there.

**Comment by w4nderlust** [comment]
To add to it, we are currently thinking about ways foe users to provide also raw images instead of paths, which would allow you to load the data from gdrive and then provide it to ludwig without the paths, but we are still working on it. If you find a handy way to make absolute paths work in Colab let us know!

**Comment by w4nderlust** [comment]
Closing this for the moment, feel free to reopen if you have further questions, or open a thread on [Gitq](https://gitq.com/uber/ludwig)
