### ISSUE TITLE
KeyError: 'char_str2idx'

### ISSUE THREAD

**Issue by crsrusl** [uber/ludwig#183]
I'm having real issues running Ludwig - I'm getting the following error message:

`KeyError: 'char_str2idx'`

Mac OSX Mojave, 10.14.2

I've attached the traceback as well. 

<img width="1440" alt="screenshot 2019-03-07 at 16 35 21" src="https://user-images.githubusercontent.com/1391215/53975296-6b70c680-40fc-11e9-96ed-7a36502d14d6.png">

**Comment by w4nderlust** [comment]
Use the version from master, this bug should have already being fixed. Please reopen if the bug persists.

**Comment by crsrusl** [comment]
Unfortunately the issue continues to persist, despite using the latest version from the master branch.

**Comment by crsrusl** [comment]
@w4nderlust  please reopen this issue

**Comment by w4nderlust** [comment]
@crsrusl please provide a reproducible example, complete with code, model definition, data and command, so that I can look into it.

**Comment by crsrusl** [comment]
Hi,

Command `python3 train.py --data_csv data1.csv --model_definition_file model_definition.yaml`
also tried `ludwig experiment --data_csv data1.csv --model_definition_file model_definition.yaml`

Model def and example data (reduced in file size) file attached in the zip.

[Archive.zip](https://github.com/uber/ludwig/files/2949457/Archive.zip)

**Comment by w4nderlust** [comment]
I was able to replicate the problem. Will look into it and let you know.

**Comment by w4nderlust** [comment]
Figured it out: you have the same features in input and output, also with different datatypes. That is not supported.
If you remove the duplicated features it trains (not really well, but that depends on the data itself).
I suggest to avoid using a parallel cnn for everything, some features are categorical so you should encode them as categorical.
