### ISSUE TITLE
Can I generate character sequences with Ludwig?

### ISSUE THREAD

**Issue by aletote** [uber/ludwig#184]
Also, does it support Transformer model?

**Comment by w4nderlust** [comment]
Please, read the docs, the faqs and the blogpost that describe Ludwig BEFORE asking questions.
The short answers are "yes, it can generate characters" adn "not yet, the transformer is coming in the next update".

**Comment by aletote** [comment]
I'm sorry, I found the transformer plans in FAQ. However, I can't find a sequence of character generation example on the list of examples. I'm looking for a way to do what char-rnn does with Shakespeare text but with Ludwig. Care to help me?

**Comment by w4nderlust** [comment]
Use a text feature and set `level: char` ;) In the docs: [text feature](https://uber.github.io/ludwig/user_guide/#text-features)

**Comment by aletote** [comment]
I have input file called shakespeare.csv of 1mb with:
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

...

I have test.yaml with:

input_features:
    -
	name: shakespeare
        type: text
        encoder: rnn
        cell: lstm
        bidirectional: true
        level: char

output_features:
    -
	name: shakespeare
        type: text

I use ludwig experiment --data_csv shakespeare.csv --model_definition_file test.yaml butain it doesn't train, gives me "TypeError: 'int' object is not callable".
I suspect there are some things I'm doing wrong, I want to generate new text in the style of Shakespeare. If you know how to do it please tell me so I can do it. Thanks.

**Comment by w4nderlust** [comment]
you have to respect Ludwig's data format. READ THE DOCS.

**Comment by aletote** [comment]
I have read the damn docs! They are obviously not clear enough, at least on my problem. Being Ludwig promoted as easy to implement as it is, I was expecting a little quick help instead of just saying read the docs like a robot. For now I'll wait until Uber hires someone who can respond to my questions properly.

**Comment by w4nderlust** [comment]
@aletote this entitled and abusive attitude is not constructive and will not get you any help from anyone.
