### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.initializers' has no attribute 'random_normal'

### ISSUE THREAD

**Issue by Barath19** [uber/ludwig#186]

**Comment by w4nderlust** [comment]
How do you pretend I will be able to solve this without even a single word to describe it? Please provide a reproducible example, with code, model definition and data.

**Comment by rajputakhil** [comment]
Maybe the issue was due to tensorflow 1.13. With that now fixed by @w4nderlust, this error must have gotten resolved. Did @Barath19 try again?

**Comment by Barath19** [comment]
I had upgraded to tensorflow 1.13. Got it fixed

**Comment by rajputakhil** [comment]
@Barath19 so did converting from 1.13 to 1.12 fixed it? Thanks

**Comment by w4nderlust** [comment]
Closing this as it is solved.

**Comment by amgsharma** [comment]
Same error on tensorflow 2.0.0 
Here's the traceback: https://pastebin.com/LRP9gW71
