### ISSUE TITLE
missing value handling for time series

### ISSUE THREAD

**Issue by BenMacKenzie** [uber/ludwig#188]
a couple things:

1. you don't seem to be able to over-ride fill_value for timeseries.
2. so you are stuck with the default, which is  " .
3. this causes and exception when  ludwig tries to convert the time series to a float.

also...

for a lot of use cases that we are looking at the number of floats in a timeseries needs to be the same across all examples.  so if your data looked like this:

data:
x,y,label
3.4 5.6 6.9, a b c, 1
**3.4, a b c, 1**
3.4 5.6 6.9, a b c, 1
3.4 5.6 6.9, a b c, 1

you'd want it to look like:
x,y,label
3.4 5.6 6.9, a b c, 1
**3.4 0 0, a b c, 1**
3.4 5.6 6.9, a b c, 1
3.4 5.6 6.9, a b c, 1

after pre-processing. assuming 0 was you flll_value.  so sort of a combination of missing_value_strategy and padding.

**Comment by w4nderlust** [comment]
Thanks for the comments @BenMacKenzie .
.Yes you can change both the fill value, the fill value strategy and the padding value.
Those are all parameters of the timeseries preprocessing.
Fill value is the value that is used when in the whole datapoint is missing, padding is the value that is used to fill sequences to the fixed length that is specified.
I should probably make it more explicit in the documentation, I say timeseries are treated in the same way of the sequences ([here](https://uber.github.io/ludwig/user_guide/#time-series-features-preprocessing)), but I should also add that you can use the same preprocessing parameters, specified [here](https://uber.github.io/ludwig/user_guide/#sequence-features-preprocessing).
Closing this for now, let me know if there are other prprocessing parameters that would be useful in your use case.

**Comment by BenMacKenzie** [comment]
thanks @w4nderlust 

I wasn't clear in my comments.  I did try to set the fill_value for a timeseries feature, but it didn't work.

line 140 in preprocessing.py checks to see if 'preprocessing' is in feature, and if so it merges the global_processing parameters with the feature preprocessing parameters.    The feature preprocessing parameters contain fill_value: 0, however....the merge_dict never happens because the if condition fails (i.e., there is no 'preprocessing' in feature for timeseries.

Ben

**Comment by w4nderlust** [comment]
You have to specify the preprocessing in the feature. I believe you did something like this:
```
input_features:
  -
    name: whatever
    type: timeseries
    fill_value: 42
```
but what you should do is:
```
input_features:
  -
    name: whatever
    type: timeseries
    preprocessing:
      fill_value: 42
```
of you can set the global preprocessing for all time sereis features with a key at the first level of the YAML that looks like:
```
preprocessing:
  timeseries:
    fill_value: 42
```
