### ISSUE TITLE
Issues with Docker install

### ISSUE THREAD

**Issue by rajputakhil** [uber/ludwig#189]
I tried to create a Docker image (named **ludwig**)) using the provided Dockerfile . Though I was able to successfully create the docker image, when I try to run it (using the comand **docker run -it ludwig**), I get the following error message:
**AttributeError: module 'tensorflow.python.keras.api._v2.keras.initializers' has no attribute 'random_normal'**

I am using: 
 - OS: Ubuntu 18.04.2 LTS 
- Python version: 3.7.1

Could you please help?

Thanks

**Comment by w4nderlust** [comment]
@rajputakhil will take a closer look, but my take it stat with hte recent new releases of Tensorflow (1.13 and 2.0alpha) those changed some APIs. So I would actually try to recreate the docker changing `tesnorflow>=0.12` to `tensorflow==0.12` in `requirements.txt` and `setup.py`.
Also make sure the python version inside the docker is 3.6.
let me know if this solves the issue.
In ludwig v0.1.1 I will change both files to use a specific TensorFlow version.

**Comment by rajputakhil** [comment]
@w4nderlust thanks a lot. The changes you made did help me to compile the docker image and sun ludwig successfully. Perhaps it indeed was the change of ```tesnorflow>=0.12``` to ```tensorflow==0.12``` which did the trick.
