### ISSUE TITLE
ERROR : git clone git@github.com:uber/ludwig.git 

### ISSUE THREAD

**Issue by pumpkinband** [uber/ludwig#190]
Cloning into 'ludwig'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Denniso2** [comment]
You can clone using the url if you are having problems like this `git clone https://github.com/uber/ludwig`

**Comment by pumpkinband** [comment]
@Denniso2 thanks a lot !!

**Comment by w4nderlust** [comment]
I updated the README with the https url, which should solve the issue for people in the future. Closing this, thank you both!

**Comment by purekaarnage** [comment]
aaa just spent 3 hours on this. why they dont just do that then
