### ISSUE TITLE
Input/output error of model file

### ISSUE THREAD

**Issue by skim2257** [uber/ludwig#195]
Executed ludwig via command line: 
`ludwig train --data_csv Iris.csv --model_definition "{input_features: [{name: SepalLengthCm, type: numerical}, {name: SepalWidthCm, type: numerical}, {name: PetalLengthCm, type: numerical}, {name: PetalWidthCm, type: numerical}], output_features: [{name: Species, type: category}]}"`

Ludwig successfully went through 18 training epochs. 

Code ended with following error: 
```
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: results\experiment_run_0\model\model_weights_progress.meta.tmp70474c99
60e942c3bc895bc797136026 to: results\experiment_run_0\model\model_weights_progress.meta : ???? ???????.
; Input/output error
```

When trying to train on programmatic API with the following script,
```
df = pd.read_csv ("Iris.csv")

print (df.head())

#train a model

model_definition = yaml.load('{input_features: [{name: SepalLengthCm, type: numerical}, {name: SepalWidthCm, type: numerical}, {name: PetalLengthCm, type: numerical}, {name: PetalWidthCm, type: numerical}], output_features: [{name: Species, type: category}]}')
model = LudwigModel(model_definition)
train_stats = model.train(df)

# or load a model
model = LudwigModel.load(model_path)

# obtain predictions
predictions = model.predict(test_dataframe)

model.close()
```

I received a similar error: 
```
UnknownError (see above for traceback): Failed to rename: results\_run_3\model\model_weights.data-00000-of-00001.tempstate10969392275462195049 to: results\_run_3\model\model_weights.data-00000-of-00001 : ???? ???????.
; Input/output error
	 [[node save/SaveV2 (defined at C:\Users\samkr\Desktop\MEGA\Github\ludwig-test\venv\lib\site-packages\ludwig\models\model.py:213) ]]
```

Environment:
 - OS: Windows 10
- Python: v3.6.1
- Ludwig: v0.1.0
- IDE: PyCharm Professional

**Comment by w4nderlust** [comment]
Can you please double check if you are using `tensorflow==0.12`? If not, can you please install that version and retry?

**Comment by skim2257** [comment]
`tensorflow==0.12` works. 
Is there a deliberate reason for this? 

Also, I think it might be helpful to let users know to install `tensorflow==0.12` via pip, you need to be on Python 2.7 / 3.4 / 3.5. I was quite confused haha

**Comment by skim2257** [comment]
SOLUTION: exited MEGAsync software, which was fighting Python/Ludwig for the file. 

'Twas a setup-specific issue. Sorry if this confuses anybody.
