### ISSUE TITLE
Stream input for time forecast

### ISSUE THREAD

**Issue by snapo** [uber/ludwig#203]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to use a block stream as input. For example:
input file contains:
time1 , 2
time2 , 3
time3 , 4
time4 , 5.5
time5 , 12
...

the features i generate are more then 50k that would mean a 1GB source file would end up with 50TB if i preproceed the data. As this is very disk consuming it would be nice to have a feature to do preprocessing of the last X ammount of rows.

**Describe the use case**
Even diskspace is cheap novadays, as soon as you have a exponential ammount of features even disks will get expensiv.

**Describe the solution you'd like**
I am requesting a feature like a function or something where it calls a python script that does the preprocessing... something like:
ludwig -preprocess preprocess.py 
And in the ludwig yaml a preprocess attribute with how many rows to look back for the preprocess.

Alternatively stream each row for preparation to the preprocess.py and the preprocess py handles how many rows back to consider.

**Describe alternatives you've considered**
Buy more disks :-)

**Additional context**
No additional context required.

**Comment by w4nderlust** [comment]
@snapo could you please explain more about how your data looks like and how do you expect it to look like? In your example you have one timestamp per line and one value per line, a simple transformation will make it into a format ludwig could read, which will occupy the same space or even less (as you don't have row ids), so I'm not really getting what the issue is here.

**Comment by snapo** [comment]
Hi w4nderlust,
Sorry for not properly describe it, for example i have stock data to play with...

Source CSV File i have....
timestamp, ms
1, 299.9991
2, 299.9992
3 , 299.9995
... and so on (1,2,3 are just samples and represent timestamps)

Before i input this to ludwig, i would like to add the close of to each step with a higher timeframe.

timestamp, ms close, 2ms close, 3ms close ..... up to 1 second.
1, 299.9991, 299.9991,299.9991 .....
2, 299.9992, 299.9991, 299.9991 ....
3 , 299.9995, 299.9992, 299,9991 ...

After that i would additionally add features to each column containing ema (exponential moving average 1-100) , sma (simple moving average 1-100), macd ... and so on.

As you see the CSV file would never fit to disk if i add all that to the csv. Within tensorflow you have for example the ability to prepare you inputdata before it will be sent to the neural network.

Here is a example with keras that shows the preprocessing of the data:
https://stackoverflow.com/questions/51983391/preprocess-huge-data-with-a-custom-data-generator-function-for-keras

this preprocessing could also come handy for image / video analysation.

Hope i have explained it properly. If something is still not clear please let me know

**Comment by w4nderlust** [comment]
Got it. I believe there are two different issues going on here.

One is: how to deal with data provided per timestamp, which I guess is kind of the standard for timeseries data (I'm not expert in timeseries). At the moment ludwig requires you to provide the whole timeseries, with different features, as a row. For instance you example would look like:
```
ms_close,                                 2ms_close,                              3ms_close, ...
299.9991 299.9992 299.9995, 299.9991 299.9991 299.9992, 299.9991 299.9991 299,9991, ...
```
With the assumptions that you have several timeseries you are learning from, not only one. But i would be curious to hear your thoughts about it as, again, I'm no timeseries expert.

The second is: how do you feed data (independently of the shape) from streams. The is not simple way to do that in Ludwig at the moment, I have to figure out well the usecase, in particular if it is for training, for prediction or for both.
In the meantime, one thing I may suggest is to use the programmatic API, as the `LudwigModel` class provides both an `online_train` method that trains on a specific batch that you provide, and also a `predict` that predicts on the specific data you provide (which can come from a queue from a stream or whatever else). What goes around it (reading the stream, modifying the data and providing it to Ludwig) will have to be implemented by you, but at least you have a way to do that.

I'mm mark this as enhancement, but some deeper thought needs to go into this i believe.

**Comment by snapo** [comment]
@w4nderlust Thanks a lot, i will check out if i could achive my target with online_train (from the sound of it it could work out). If i should still require the enhancement i would like to get back to you with a sample... until then i think the issue can be freezed.

**Comment by w4nderlust** [comment]
Great, let me know.
