### ISSUE TITLE
can you add fully connecter layers to an RNN encoder?

### ISSUE THREAD

**Issue by BenMacKenzie** [uber/ludwig#206]
The diagram in documentation suggest yes, but num_fc_layers and fc_layers are not listed as available parameters as they are for e.g., parallel cnn or stacked cnn.  

It does not seem like it is supported based on a few experiments however I am using the RNN encoder inside a sequence combiner, so possibly this is causing problems.  

for example, this does not seem to add any fc_layers:

 combiner = {'type': 'sequence',
 'main_sequence_feature': 'x',
 'encoder': 'rnn',
 'reduce_output': 'concat',
 'fc_layers': [{'fc_size': 64}] }

thanks!

**Comment by w4nderlust** [comment]
The issue teams from the fact that you usually do a reduction at the end of the rnn (max or sum or avg over time for instance) or just picking the last timestamp. That representation could be passed through fc_layers, at the moment it isn't. So I guess your feature request is to add additional fc_layers on top of the rnn (and I guess also the cnnrnn) encoder. Will add it to the backlog.
Anyway, depending on how the decoder side of your model works, you can add fc_layers at the beginning of the decoder that would have exactly the same function.

**Comment by BenMacKenzie** [comment]
thanks @w4nderlust i wouldn't give this one a very high priority since as you point out adding fc_layers at beginning of de-coder achieves the same result (which is in fact what i did).  it was more a conceptual point to make sure i wasn't missing something.  Might make sense to update the diagram in documentation?

keep up the great work!!

**Comment by w4nderlust** [comment]
Yeah all you are suggesting makes sense :)

**Comment by jeffin07** [comment]
Hello @w4nderlust  I would like to work on this issue.Can you help me with any details to start?

**Comment by w4nderlust** [comment]
@jeffin07 thank you so much for being willing to help. Right now we are doing a big porting to TensorFlow 2 and this issue will solved there, so actually no need to worry I'll take care of it shortly.
But I really appreciate your willingness to help, maybe take a look at the tasks here to find something that you are interested in helping with: https://github.com/uber/ludwig/projects/1

**Comment by w4nderlust** [comment]
It took some time, sorry for that, but I actually implemented this today as part of the porting to TensorFlow 2 as you can see here:
https://github.com/uber/ludwig/blob/tf2_porting/ludwig/models/modules/sequence_encoders.py#L1204-L1242
You'll be able to use it in the next release of Ludwig.
