### ISSUE TITLE
Bad import in base_feature.py

### ISSUE THREAD

**Issue by graytowne** [uber/ludwig#211]
Minor issue:
There is a bad import in [base_feature.py](https://github.com/uber/ludwig/blob/master/ludwig/features/base_feature.py#L21). The reduce_sequence function is actually in the [reduction_modules](https://github.com/uber/ludwig/blob/master/ludwig/models/modules/reduction_modules.py#L79) not recurrent_modules.

I can have a PR to fix this.

**Comment by w4nderlust** [comment]
Merged it, thanks!
