### ISSUE TITLE
Timeseries example when using the API

### ISSUE THREAD

**Issue by George3d6** [uber/ludwig#223]
Hi,

I seem to be able to use `sequential` values in the API via arrays (e.g. a cell of the sqeuential feature being [1,2,3,4]) but if I try to do the same for timeseries ludwig crashes trying to cast `[121,` to a float64.

How are we supposed to use timeseries features with the API ?

**Comment by w4nderlust** [comment]
It doesn't work for sequences either. In the docs we describe the format functions and what is expected from the default ones. By default the format is just provide values separated by space (without the brackets).
