### ISSUE TITLE
Add pretrained models to Ludwig

### ISSUE THREAD

**Issue by DennisFaucher** [uber/ludwig#235]
**Describe the bug**
I'm new at Ludwig but I used the image classification example with my own images and the model never swayed from 50% accuracy.

**To Reproduce**
1. pip install https://github.com/uber/ludwig/archive/master.zip
2. ludwig experiment --data_csv image_class.csv --model_definition_file image_class.yaml
3. Learning stops after about 14 epochs and accuracy never changes from 0.5000

IMAGE_CLASS.YAML
===============
input_features:
    -
        name: image_path
        type: image

output_features:
    -
        name: class
        type: category

IMAGE_CLASS.CSV
==============
image_path,class
chickens/10538543_brown_hen_isolated_on_white_studio_shot_.jpg,chicken
chickens/1200px_Mother_hen_with_chicks02.jpg,chicken
chickens/126523696_56a885a65f9b58b7d0f30ca9.jpg,chicken
chickens/1304236.jpg,chicken
chickens/137318_004_A879596D.jpg,chicken
chickens/2017_11_largeimg14_Tuesday_2017_164436973.jpg,chicken
chickens/2Hen12_430.jpg,chicken
chickens/3163854817.jpg,chicken
chickens/378px_Hen_with_chicks__Raisen_district__MP__India.jpg,chicken
chickens/3a7e0342a3d2915f239900fba3321841.jpg,chicken
chickens/4874110_brown_hen.jpg,chicken
chickens/491460075_56a8859f3df78cf7729e88b0.jpg,chicken
chickens/4e6b49549f7437.53336402.jpg,chicken
chickens/5a8f097f1e000017087ac8b2.jpeg,chicken
chickens/5ea1a70a_a954_4a69_9824_faaeda975aa8.jpg,chicken
chickens/7339222.jpg,chicken
chickens/760px_Light_sussex_hen.jpg,chicken
chickens/87606415_XS.jpg,chicken
chickens/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzAxNS83NTYvb3JpZ2luYWwvcm9vc3Rlci13YXR0bGUtMTAwODE5LTAyLmpwZw__.jpg,chicken
chickens/Backyard_hens_rdax_500x309.jpg,chicken
chickens/Broody_Hen.png,chicken
chickens/brown_chicken_hen_standing_i_35691_5.jpg,chicken
chickens/Buff_Orpingtons_1.png,chicken
chickens/CARING_FOR_HENS_EGGS.jpg,chicken
chickens/chick1.jpg,chicken
chickens/chicken.jpg,chicken
chickens/Chickens_Chicken_Guide_A_mother_hen_looking_after_her_recently_hatched_chicks.jpg,chicken
chickens/cofmvahtvcx8qteyjyqikev3uplccoxyrkpsuqygwfx5yqewqkscsmtytldddup5_.jpg,chicken
chickens/Common_Diseases_in_Lying_Hens.jpg,chicken
chickens/country_chicken_500x500.jpg,chicken
chickens/country_hen_500x500.jpg,chicken
chickens/db837831dcffe7b35a7c8130e2c2fe76.jpg,chicken
chickens/dc_Cover_ctlr5hasmnp66sis03r364tlq0_20180825091821.Medi.jpeg,chicken
chickens/eggs_and_hen.jpg,chicken
chickens/Employee_Holding_Hen_OhioFresh2.jpg,chicken
chickens/favicon.png,chicken
chickens/G2ASF5CQYRF3HMKBKT3L6RHERI.jpg,chicken
chickens/gender_hen_2.jpg,chicken
chickens/handling1.jpg,chicken
chickens/hen_151155842_250.jpg,chicken
chickens/hen1.jpg,chicken
chickens/hen_500x500.jpg,chicken
chickens/Hen6.png,chicken
chickens/hen_png_hd_red_single_chicken_png_image_40291_free_png_hen_515.png,chicken
chickens/hens_adopt_animals_5979b483663b9__700.jpg,chicken
chickens/hens.jpg,chicken
chickens/hoens_eller_kyllinger.jpg,chicken
chickens/hqdefault.jpg,chicken
chickens/IMG_6126_1_1024x1024.jpg,chicken
chickens/kadaknath_black_hen_500x500.jpg,chicken
chickens/latest.jpg,chicken
chickens/Laying_Hen.jpg,chicken
chickens/maxresdefault1.jpg,chicken
chickens/maxresdefault2.jpg,chicken
chickens/maxresdefault3.jpg,chicken
chickens/nly6qb4vs3xgzttkdgkr.jpg,chicken
chickens/Norwegian_hen.jpg,chicken
chickens/photo_1535275226173_7ee8b465f0c1.jpg,chicken
chickens/Rhode_Island_Red_Hen_Hybrid.jpg,chicken
chickens/Rooster_vs_Hen.jpg,chicken
chickens/Spent_hen.JPG,chicken
chickens/swedish_flower_hen2.jpg,chicken
chickens/Swedish_Flower_Hen.jpg,chicken
chickens/Talking_Hens_5_Month_Old_Hy_Line_Brown_Pullets_1.jpg,chicken
chickens/tanja_pedersen_happy_and_gydde1.jpg,chicken
chickens/unnamed1.jpg,chicken
chickens/What_to_Feed_Laying_Hens.jpg,chicken
chickens/White_hen_300x291.jpg,chicken
chickens/white_hen_500x500.jpg,chicken
chickens/0027493_siberian_husky_id_dog_tag.jpeg,chicken
huskies/00b0788bf9ca083f28b3eb2c5328908b.jpg,husky
huskies/01_siberian_huskies_eyes_gettyimages_84041048.ngsversion.1539113409912.adapt.1900.1.jpg,husky
huskies/13181877_f496.jpg,husky
huskies/17223096_siberian_husky_dog_portrait.jpg,husky
huskies/220px_Woody_Puppy.jpg,husky
huskies/248f5b8263546d871b5f602c1dca2cd4.jpg,husky
huskies/26732932_10204046885128816_216743306_o.jpg,husky
huskies/500000291_medium.jpg,husky
huskies/500_F_129581365_gZ8pwBEmoqqC6Oh9pcqGsOazDG91i9CF.jpg,husky
huskies/51674814_siberian_husky_dog_with_blue_eyes_outdoor_closeup.jpg,husky
huskies/734cb0e923223cb519eec8cd4fcafcf1.jpg,husky
huskies/8250f4ef_c480_4f31_88e6_12aea3831169.png,husky
huskies/87527328.jpg,husky
huskies/932358_11188300.jpg,husky
huskies/a234898de7bb54fb4eac0b3f1c229746.png,husky
huskies/AdobeStock_61487366_1024x726.jpeg,husky
huskies/AdobeStock_85274165_1024x680.jpeg,husky
huskies/article_image_horiz_104.jpg,husky
huskies/best_harness_husky_dogstruggles.jpg,husky
huskies/Black_Magic_Big_Boy.jpg,husky
huskies/c1303a96a88c9a80a2cf00a0bf6b63c3.jpg,husky
huskies/DBS_SibHusky.jpg,husky
huskies/hqdefault.jpg,husky
huskies/Huskiesatrest.jpg,husky
huskies/husky10.jpg,husky
huskies/husky_2699136_1920_1_1024x678.jpg,husky
huskies/husky_770x405.png,husky
huskies/husky_dog_behaviors.jpg,husky
huskies/husky_dog_diy_5d_diamond_painting_full_drill_1024x1024.png,husky
huskies/husky_dog_kart_from_akureyri_north_iceland_3.jpg,husky
huskies/husky_dog_names_hero.jpg,husky
huskies/husky_dog_names.jpg,husky
huskies/husky.jpg,husky
huskies/Husky_with_two_different_colored_eyes.jpg,husky
huskies/image.jpg,husky
huskies/iStock_000018251084_Small.jpg,husky
huskies/istock_146773846.jpg,husky
huskies/latest_news_ez_pages_how_to_choose_dog_harness_1507347612.jpg,husky
huskies/ollie_denali_1170x540_1170x540.jpg,husky
huskies/photo_1457914109735_ce8aba3b7a79.jpg,husky
huskies/red4.jpg,husky
huskies/siberian einstein.jpg,husky
huskies/siberianhuskies2.jpg,husky
huskies/siberian_husky_1460718_1280.jpg,husky
huskies/siberian_husky_1.jpg,husky
huskies/siberian_husky_3.jpg,husky
huskies/siberian_husky_4217efb5_9130_4bdc_aa80_b274821bd05d_large.jpg,husky
huskies/Siberian_Husky_4.jpg,husky
huskies/Siberian_Husky_600.jpg,husky
huskies/Siberian_Husky_7.jpg,husky
huskies/siberian_husky_card_small.jpg,husky
huskies/siberian_husky_detail.jpg,husky
huskies/siberian_husky_dog_breed_info.jpg,husky
huskies/siberian_husky_dog_breed_information.jpg,husky
huskies/siberian_husky_dog_breed_pictures_1.jpg,husky
huskies/siberian_husky_dog_breed_pictures_6.jpg,husky
huskies/Siberian_Husky_Featured.jpg,husky
huskies/Siberian_Husky.jpg,husky
huskies/siberian_husky_large_shutterstock_529869769_copy.jpg,husky
huskies/Siberian_Husky_On_White_03.jpg,husky
huskies/Siberian_Husky_on_White_12_800x600_1.jpg,husky
huskies/SiberianHuskySibePurebredDogMisha5YearsOld1.jpg,husky
huskies/siberian_husky_snow.jpg,husky
huskies/snow1.jpg,husky
huskies/snow3.jpg,husky
huskies/the_alaskan_malamute_1415_0_600.jpg,husky
huskies/types_and_breeds_of_husky_dogs_1415_600.jpg,husky
huskies/types_husky_dogs.jpg,husky

**Expected behavior**
Accuracy should increase up into the 90 percentile
**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Version 10.13.6
- Python version 3.6.0
- Ludwig version: Latest

**Additional context**
Prediction based on the model created is inaccurate. Predicted that a photo of chickens was a photo of a husky with 96% accuracy.

**Comment by w4nderlust** [comment]
Have you trained other models that learn to classify this dataset to 90%? Can you post them so that i can compare?
This doesn't look like an issue anyway, it's likely that playing around with the hyperparameters you can improve your scores.

**Comment by DennisFaucher** [comment]
Thank you w4nderlust. I used the same data with straight Python Tensorflow and predicted correctly at 96%. My write-up of that is here: http://blog.faucher.net/2019/01/tensorflow-chicken-recognition-in.html
What do you mean by "hyperparameters"?

**Comment by w4nderlust** [comment]
What you are doing in your colab is taking a - model, trained on millions of images, and finetuning on the few images you have.
What you are doing with Ludwig is training a classifier from scratch on the small amount of images that you have.
You cannot really expect to two things to perform the same :)
That said, we are going to add the option to use pre-trained image stacks like the one you used in your example also in Ludwig, so stay tuned (marking this as a feature request for pretrained models).
(hyperparameters are parameters of the architecture of the model and / or of the training process. For instance how many layers, how many filters, how much dropout etc.)

**Comment by DennisFaucher** [comment]
@w4nderlust thank you again. I am new to this and your explanation makes complete sense. I thought that my colab was creating the model based on the same images I fed to ludwig. It looks like my colab uses retrain.py which first downloads inception-2015-12-05.tgz and then adds my images to that existing model.

**Comment by DennisFaucher** [comment]
Final piece of data. This is the output of ludwig visualize. Looks like training went well even though predicting on one of the actual chicken images used for training results in 96% husky. 
![Learning_Visualization_1](https://user-images.githubusercontent.com/9034190/54716367-efc73e80-4b2b-11e9-8dbb-8df255b43f4a.png)

**Comment by w4nderlust** [comment]
this is actually weird, wold you mind making a zip containing the image directories and send it to me? (it 's too big you can use wetransfer) so that i can look at it more closely?

**Comment by DennisFaucher** [comment]
@w4nderlust is a shared Google Drive folder OK?
* Chickens: https://drive.google.com/open?id=1livLm4eGlm4ez2bpj0eDjEui3e91bKJL
* Huskies: https://drive.google.com/open?id=1Im4H9gLaKN48x-sMMCoXY0ctwGoGM5Oa

**Comment by w4nderlust** [comment]
Please provide a zipped file, as google drive as a hard time allowing people to download directories with many files inside them like in this case (it tries to zip them but takes forever to do so). You can put the zipped file containing the 2 directories on gdrive and then post a link to it. Thank you really much.

**Comment by DennisFaucher** [comment]
[chickens.zip](https://github.com/uber/ludwig/files/2990353/chickens.zip)
[huskies.zip](https://github.com/uber/ludwig/files/2990354/huskies.zip)

**Comment by w4nderlust** [comment]
Took a deeper look, found a bunch of things.
1. in your csv there is a wrong file with wrong label: `chickens/0027493_siberian_husky_id_dog_tag.jpeg, chicken`
2. using the following model definition, just for a super quick test with really small images:
```
input_features:
-
  name: image_path
  type: image
  preprocessing:
    width: 28
    height: 28
output_features:
-
  name: class
  type: category
```
I can get 0.85 accuracy after 8 epochs with just the default parameters:
```
Epoch  10
Training: 100%|██████████| 12/12 [00:07<00:00,  1.58it/s]
Evaluation train: 100%|██████████| 12/12 [00:01<00:00,  6.45it/s]
Evaluation vali : 100%|██████████| 2/2 [00:00<00:00,  7.00it/s]
Evaluation test : 100%|██████████| 4/4 [00:00<00:00,  7.01it/s]
Took 10.6772s
╒═════════╤════════╤════════════╤═════════════╕
│ class   │   loss │   accuracy │   hits_at_k │
╞═════════╪════════╪════════════╪═════════════╡
│ train   │ 0.2958 │     0.8421 │      1.0000 │
├─────────┼────────┼────────────┼─────────────┤
│ vali    │ 1.9955 │     0.8571 │      1.0000 │
├─────────┼────────┼────────────┼─────────────┤
│ test    │ 1.3736 │     0.8552 │      1.0000 │
╘═════════╧════════╧════════════╧═════════════╛
```
This suggests that Ludwig is working properly and that it's mostly a matter of hyperparameters.
Closing this, feel free to keep commenting if other issues arise.

**Comment by DennisFaucher** [comment]
Oh, excellent. Thank you. I'll check my data and try again.

**Comment by DennisFaucher** [comment]
@w4nderlust the "preprocessing" directive caused an error in the ludwig experiment run on my Mac. I'll try in Google Collab and see if I get the same error.

Found hdf5 and json with the same filename of the csv, using them instead
Using full hdf5 and json
Loading data from: image_class.hdf5
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Loading metadata from: image_class.json
Training set: 6
Validation set: 2
Test set: 2
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/experiment.py", line 548, in cli
    experiment(**vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/experiment.py", line 242, in experiment
    update_model_definition_with_metadata(model_definition, train_set_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ludwig/train.py", line 420, in update_model_definition_with_metadata
    'preprocessing'
KeyError: 'preprocessing'

**Comment by w4nderlust** [comment]
Please remove the hdf5 and json file and run again, those were created without the preprocessing explicitly listed, so the size of the images will be different.
