### ISSUE TITLE
from ludwig import LudwigModel error

### ISSUE THREAD

**Issue by mariuszolszewski676** [uber/ludwig#236]
**Describe the bug**
from ludwig import LudwigModel 

gives me error:

ImportError: cannot import name 'LudwigModel'

**Expected behavior**
executing without error

**Screenshots**
![image](https://user-images.githubusercontent.com/47120207/54674848-8af4ef80-4afd-11e9-82eb-2efb8b9d3805.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
- Python version 3.6
- Ludwig version 0.1

**Comment by w4nderlust** [comment]
Can you please just run `python` in you virtual environment and then type `from ludwig import LudwigModel`? You are probably just not using an interpreter that has access to the pip package you installed.

**Comment by mariuszolszewski676** [comment]
I had only one environment (in anaconda), I use spider to execute script.   I should create new virtual enviroment in anaconda?       
            
          
     
      
       
        Dnia 20 marca 2019 19:29 Piero Molino &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Can you please just run  python  in you virtual environment and then type  from ludwig import LudwigModel ? You are probably just not using an interpreter that has access to the pip package you installed.

**Comment by w4nderlust** [comment]
Within your anaconda environment please try to do what i suggested before. If it works, it means that it's an issue with spyder / runfile and not with Ludwig.

**Comment by mariuszolszewski676** [comment]
Python 3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32   Warning:  This Python interpreter is in a conda environment, but the environment has  not been activated. Libraries may fail to load.  To activate this environment  please see  conda.io conda.io   Type &#34;help&#34;, &#34;copyright&#34;, &#34;credits&#34; or &#34;license&#34; for more information.  &gt;&gt;&gt; from ludwig import LudwigModel    looks like it works   what should I do now? 
            
          
     
      
       
        Dnia 20 marca 2019 19:29 Piero Molino &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Can you please just run  python  in you virtual environment and then type  from ludwig import LudwigModel ? You are probably just not using an interpreter that has access to the pip package you installed.

**Comment by w4nderlust** [comment]
I'm not familiar with spyder and runfile, so I'm not sure how you would go make it run there.
I would suggest to just run `from ludwig import LudwigModel` directly in spyder without using runfile.
Anyway we made sure that it is not an issue related with Ludwig. so you probably want to ask for help about your issue with spyder and runfile on StackOverflow.

**Comment by abhijeetfenix** [comment]
In your virtual environment,  go to lib/python3.6/site-packages/ludwig/
now open __init__.py and add below code to :

from ludwig.api import LudwigModel
from ludwig.cli import CLI

**Comment by w4nderlust** [comment]
If you do that, the import time will skyrocket
