### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by mariuszolszewski676** [uber/ludwig#240]
**Describe the bug**
After running a script I had error:
  File "C:\Anaconda3\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**To Reproduce**
my code:

from ludwig import LudwigModel
import pandas as pd
from mysql.connector import (connection)
cnx = connection.MySQLConnection(user='C', password='CCC', host='CCCCC')

query = """
 
Select * from da_col.aaa_temp_lud where period < '2019-03-01'

        """
c = cnx.cursor(buffered=True)

#for result in c.execute(query, multi=True):
#    pass
c.execute(query)

columns = [desc[0] for desc in c.description]
data = c.fetchall()
df1 = pd.read_sql(query, cnx)
print(df1.dtypes)

cnx.commit()
c.close()
cnx.close()
cnx.disconnect()

#pd.read_csv(r"C:/Users/mariusz.olszewski/Desktop/ludwig/train.csv")

#training

#train_stats = ludwig_model.train(data_df=dataframe)
model_definition = {}
model_definition['input_features'] = [{'name': 'year' , 'type' : 'numerical'},
                                      {'name': 'month', 'type' : 'numerical'},
                                      {'name': 'loan_balance', 'type' : 'numerical'},
                                      {'name': 'princ_balance', 'type' : 'numerical'},
                                      {'name': 'count', 'type' : 'numerical'},
                                      {'name': 'onhold', 'type' : 'numerical'},
                                      {'name': 'dpd', 'type' : 'numerical'},
                                        {'name': 'repaid', 'type' : 'numerical'},
                                        {'name': 'app_score', 'type' : 'numerical'}]

model_definition['output_features'] = [{'name': 'cash', 'type' : 'numerical'}]
ludwig_model = LudwigModel(model_definition)
train_stats = ludwig_model.train(data_df=df1)

**Expected behavior**
fix error

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win10
- Python version 3.6
- Ludwig 0.1

**Additional context**

**Comment by w4nderlust** [comment]
Sorry, this is not reproducible as it is tied to you SQL serever. Please provide some self contained code.

**Comment by mariuszolszewski676** [comment]
from ludwig import LudwigModel
import pandas as pd
df = pd.read_csv(r"C:/Users/mariusz.olszewski/Desktop/aaa.csv")
print(df.dtypes)
#training

#train_stats = ludwig_model.train(data_df=dataframe)
model_definition = {}
model_definition['input_features'] = [{'name': 'year' , 'type' : 'numerical'}, 
                                      {'name': 'month', 'type' : 'numerical'}, 
                                      {'name': 'loan_balance', 'type' : 'numerical'}, 
                                      {'name': 'princ_balance', 'type' : 'numerical'}, 
                                      {'name': 'count', 'type' : 'numerical'}, 
                                      {'name': 'onhold', 'type' : 'numerical'}, 
                                      {'name': 'dpd', 'type' : 'numerical'},
                                        {'name': 'repaid', 'type' : 'numerical'},
                                        {'name': 'app_score', 'type' : 'numerical'}]



model_definition['output_features'] = [{'name': 'cash', 'type' : 'numerical'}]
ludwig_model = LudwigModel(model_definition)
train_stats = ludwig_model.train(df)
[aaa.zip](https://github.com/uber/ludwig/files/2993968/aaa.zip)
![image](https://user-images.githubusercontent.com/47120207/54785055-888db500-4c25-11e9-9127-391162622347.png)

**Comment by w4nderlust** [comment]
Thanks for the additional details. This problem has already been solved, please install Ludwig from master.

**Comment by mariuszolszewski676** [comment]
hi,
for me installing:

pip install https://github.com/uber/ludwig/archive/master.zip

not help with this issue. Could you check?

**Comment by w4nderlust** [comment]
Unfortunately I don't have a windows machine and I cannot reproduce the issue.
Anyway, it's unlikely that the issue is the same, as line 43 of `utils/misc.py` is different from the one that is causing the error in your report.
Specifically that part is now wrapped within a try/except block as you can see here https://github.com/uber/ludwig/blob/master/ludwig/utils/misc.py#L45 which means that if the error were to trigger it would just be ignored. This suggests that you probably aren't using the newer version when testing again, as the error should be at line 48 (but it cannot happen because it would be catched by the try/except).
So please make sure you are using the new one, or, if you get a different error with the new one, report the different error.
