### ISSUE TITLE
What data type should date be? 

### ISSUE THREAD

**Issue by avinregmi** [uber/ludwig#243]
If I have a date column in my data frame what should the data type be? 
These are the datatypes right now:
- binary
- numerical
- category
- set
- bag
- sequence
- text
- timeseries
- image

Also, does Ludwig do special processing for dates? Such as extracting year, month, day of the week and so on.. 

If there a guide which tells which kind of datatypes to use? Ie. When should I use set and bag?

**Comment by msaisumanth** [comment]
@avinregmi There's no provision for extracting year, month etc. You'll have to do that before feeding the data to Ludwig. The details about how the features are work can be found here https://uber.github.io/ludwig/getting_started/

**Comment by avinregmi** [comment]
I see. Also, I understand numerical, image, text and category datatypes. Is there a guide that tells when to use a specific data type. For example, when should I use sequence, bag, and set?

**Comment by gobzer** [comment]
There are some hints in the **Examples** section: https://uber.github.io/ludwig/examples/
### Sequence
- [Named Entity Recognition Tagging](https://uber.github.io/ludwig/examples/#named-entity-recognition-tagging)
- [Natural Language Understanding](https://uber.github.io/ludwig/examples/#natural-language-understanding)
- [Multi-Task Learning](https://uber.github.io/ludwig/examples/#multi-task-learning)

### Set
- [Movie rating prediction](https://uber.github.io/ludwig/examples/#movie-rating-prediction)
- [Multi-label classification](https://uber.github.io/ludwig/examples/#multi-label-classification)

Any information you provide should be meaningful.
For example, can you predict traffic with a unix timestamp: `1553625845` ?
And if I'll tell you that it's friday? Workday?

@avinregmi  What is your date format and what are you trying to predict?

**Comment by w4nderlust** [comment]
Anyway, we are considering adding a specific `date` datatype in the future.
@gobzer suggestion regarding meaningfulness is gold.

**Comment by w4nderlust** [comment]
Quick update: we are almost done with the date datatype, you can see the date branch right now, it will be merged soon.

**Comment by w4nderlust** [comment]
Update: the date datatype was finally added!
https://github.com/uber/ludwig/commit/9c93622cb60ca89becbfd8d8110ee1a74d491d7f
and a description was added to the the docs source:
https://github.com/uber/ludwig/commit/7f5101d5f7dcb9d4b9fa09e64bb1ec079f7f0aed
Next time I'll compile the docs, they will appear also in on the website.

Would love to receive your feedback, but I'm closing the issue, feel free to open another one to discuss about encoders for instance.

**Comment by ikramelmbarki** [comment]
> Update: the date datatype was finally added!
> [9c93622](https://github.com/uber/ludwig/commit/9c93622cb60ca89becbfd8d8110ee1a74d491d7f)
> and a description was added to the the docs source:
> [7f5101d](https://github.com/uber/ludwig/commit/7f5101d5f7dcb9d4b9fa09e64bb1ec079f7f0aed)
> Next time I'll compile the docs, they will appear also in on the website.
> 
> Would love to receive your feedback, but I'm closing the issue, feel free to open another one to discuss about encoders for instance.

I have a multivariate time series and I wanna use Ludwig, it will work for my case? and what type of algorithms work with ? the categorical data need an encoding before feeding them to Ludwig

**Comment by w4nderlust** [comment]
> I have a multivariate time series and I wanna use Ludwig, it will work for my case? and what type of algorithms work with ? the categorical data need an encoding before feeding them to Ludwig

There's a discussion on that topic where yo ucan find the answers: https://github.com/uber/ludwig/issues/668
