### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by wang703** [uber/ludwig#248]
After running Ludwig, the following error occurs:
![1553676275(1)](https://user-images.githubusercontent.com/48428697/55061856-bc4a5e00-50af-11e9-9bdf-9d5df891d1fd.jpg) 
 What should be done?

**Comment by msaisumanth** [comment]
@wang703 follow the examples [here](https://uber.github.io/ludwig/examples/)

Ludwig is not really an interactive command line tool (like python I suppose)

**Comment by wang703** [comment]
sorry, I can't understand you, like this
![1553762757(1)](https://user-images.githubusercontent.com/48428697/55143132-12370880-5179-11e9-8753-e37a40bb60e4.png)
I want to know how it works ?
Can you post pictures ? Thank you !

**Comment by w4nderlust** [comment]
http://ludwig.ai explains how Ludwig works.
