### ISSUE TITLE
Add multi language text  tokenizing support

### ISSUE THREAD

**Issue by manugarri** [uber/ludwig#251]
**Describe the use case**
Right now ludwig only provides a way of tokenizing english language via spacy.However, Spacy supports a wide variety of language tokenizers that we could benefit from.

**Describe the solution you'd like**
There would be a way to specify the language by field, for example:
```
    -
        name: name
        type: text
        language: es
        encoder: parallel_cnn
        level: word
```

**Comment by w4nderlust** [comment]
It is pretty straightforward to add this. Added to the backlog.

**Comment by w4nderlust** [comment]
Actually, as it is really easy (just look at `utils/nlp_utils.py` PRs from users are really encouraged.

**Comment by manugarri** [comment]
yeah i saw that, will take a look when i have some time :)

**Comment by w4nderlust** [comment]
This was added in v0.1.1.
To use it:
```
name: name
type: text
preprocessing:
  word_format: spanish_tokenize
```

**Comment by manugarri** [comment]
oh wow, that was fast. thanks a ton for putting the  time!

**Comment by w4nderlust** [comment]
You're welcome!
