### ISSUE TITLE
Train model fail with cryptic message

### ISSUE THREAD

**Issue by VZWUSER** [uber/ludwig#252]
Newbie using Ludwig for training a simple comment analysis with 4 columns
I am getting the error below 

`u18:~/ludwig$ ludwig train --data_csv /home/moooo/ludwig/androidcomments.csv -mdf /home/moooo/ludwig/model_definition.yaml
 _         _        
ludwig v0.1.0 - Train

/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py:149: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  model_definition = merge_with_defaults(yaml.load(def_file))
Traceback (most recent call last):
  File "/home/moooo/.local/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 149, in full_train
    model_definition = merge_with_defaults(yaml.load(def_file))
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/defaults.py", line 156, in merge_with_defaults
    output_type_registry[model_definition['output_features'][0][
KeyError: 0
`
yaml file content is shown below:
`input_features: 

   name: version
   type: category

   name: device
   type: category

   name: review
   type: text

output_features:

   name: rating
   type: category  
   
training:
 epochs: 10`

Any ideas what is wrong?

**Comment by msaisumanth** [comment]
@VZWUSER there's something wrong with your yaml file's format. Could you please attach it instead of pasting the content there? Or paste the yaml file contents in this manner:

```yaml
input_features:
    -
        name: Pclass
        type: category
    -
        name: Sex
        type: category
    -
        name: Age
        type: numerical
        missing_value_strategy: fill_with_mean
    -
        name: SibSp
        type: numerical
    -
        name: Parch
        type: numerical
    -
        name: Fare
        type: numerical
        missing_value_strategy: fill_with_mean
    -
        name: Embarked
        type: category

output_features:
    -
        name: Survived
        type: category

combiner:
    type: concat
    num_fc_layers: 1
    fc_size: 28

training:
   -
        learning_rate: 0.01

(Basically put a ```yaml markdown before pasting your yaml content)


Ludwig performs sanity checks on the yaml file. So I'm curious to see why they didn't get triggered here.

**Comment by VZWUSER** [comment]
Thank you for your reply. attached is the yaml file. 
[model_definition .yaml.txt](https://github.com/uber/ludwig/files/3019542/model_definition.yaml.txt)

**Comment by VZWUSER** [comment]
And here is an example of inline model definition which also fails

> u18:~/ludwig$ ludwig train --data_csv /home/moooo/ludwig/androidcomments.csv --model_definition "{input_features: [{name: version, type: category},{name: device, type:category},{name: review, type: text,  level: word}], output_features: [{name: rating, type: category}]}"
/usr/lib/python3.6/argparse.py:2303: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  result = type_func(arg_string)
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Train

Traceback (most recent call last):
  File "/home/moooo/.local/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 151, in full_train
    model_definition = merge_with_defaults(model_definition)
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/defaults.py", line 168, in merge_with_defaults
    get_from_registry(input_feature['type'],
KeyError: 'type'
moooo@u18:~/ludwig$ 

> 

>

**Comment by w4nderlust** [comment]
you wrote `type:category` is has to be `type: category`. Please doublecheck your yamland retry.

**Comment by VZWUSER** [comment]
Thank you for your response. The original issue with YAML file I included earlier still exists and I am not able to find any issues with YAML file. 

As far as the inline model definition, adding the space got me further. Now it is complaining about ModuleNotFoundError: No module named 'en_core_web_sm'. ANy ideas is greatly appreciated.

here is the trace
`moooo@u18:~/ludwig$ ludwig train --data_csv /home/moooo/ludwig/androidcomments.csv --model_definition "{input_features: [{name: version, type: category},{name: device, type: category},{name: review, type: text,  level: word}], output_features: [{name: rating, type: category}]}"
/usr/lib/python3.6/argparse.py:2303: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  result = type_func(arg_string)
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Train

Experiment name: experiment
Model name: run
Output path: results/experiment_run_0


ludwig_version: '0.1.0'
command: ('/home/moooo/.local/bin/ludwig train --data_csv '
 '/home/moooo/ludwig/androidcomments.csv --model_definition {input_features: '
 '[{name: version, type: category},{name: device, type: category},{name: '
 'review, type: text,  level: word}], output_features: [{name: rating, type: '
 'category}]}')
dataset_type: '/home/moooo/ludwig/androidcomments.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'name': 'version',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'name': 'device',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'review',
                              'tied_weights': None,
                              'type': 'text'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'class_distance_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'rating',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': 10000,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': False},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {'missing_value_strategy': 'backfill'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 3,
                    'epochs': 200,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}


Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading NLP pipeline
Traceback (most recent call last):
  File "/home/moooo/.local/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 224, in full_train
    random_seed=random_seed
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 457, in preprocess_for_training
    random_seed=random_seed
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 83, in build_dataset_df
    global_preprocessing_parameters
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 124, in build_metadata
    preprocessing_parameters
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/features/text_feature.py", line 99, in get_feature_meta
    preprocessing_parameters['lowercase']
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/features/text_feature.py", line 80, in feature_meta
    lowercase=lowercase
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/strings_utils.py", line 91, in create_vocabulary
    line.lower() if lowercase else line)
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/strings_utils.py", line 212, in english_tokenize
    return process_text(text, load_nlp_pipeline())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/nlp_utils.py", line 37, in load_nlp_pipeline
    import en_core_web_sm
ModuleNotFoundError: No module named 'en_core_web_sm'
`

**Comment by VZWUSER** [comment]
Thank you for your reply. For the inline model definition I have got further but problem still persists with YAML file I submitted earlier. Not sure what is going on there.

Now that the typo is fixed. I am getting further but I am getting error:
 ModuleNotFoundError: No module named 'en_core_web_sm'

I tried your recommendation from another post, installed spacy and ran "python -m spacy download" but it fails with message /usr/bin/python: No module named spacy

here is the log:
```
moooo@u18:~/ludwig$ ludwig train --data_csv /home/moooo/ludwig/androidcomments.csv --model_definition "{input_features: [{name: version, type: category},{name: device, type: category},{name: review, type: text,  level: word}], output_features: [{name: rating, type: category}]}"
/usr/lib/python3.6/argparse.py:2303: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  result = type_func(arg_string)
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Train

Experiment name: experiment
Model name: run
Output path: results/experiment_run_2


ludwig_version: '0.1.0'
command: ('/home/moooo/.local/bin/ludwig train --data_csv '
 '/home/moooo/ludwig/androidcomments.csv --model_definition {input_features: '
 '[{name: version, type: category},{name: device, type: category},{name: '
 'review, type: text,  level: word}], output_features: [{name: rating, type: '
 'category}]}')
dataset_type: '/home/moooo/ludwig/androidcomments.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'name': 'version',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'name': 'device',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'review',
                              'tied_weights': None,
                              'type': 'text'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'class_distance_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'rating',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': 10000,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': False},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {'missing_value_strategy': 'backfill'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 3,
                    'epochs': 200,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}


Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading NLP pipeline
Traceback (most recent call last):
  File "/home/moooo/.local/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/train.py", line 224, in full_train
    random_seed=random_seed
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 457, in preprocess_for_training
    random_seed=random_seed
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 83, in build_dataset_df
    global_preprocessing_parameters
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 124, in build_metadata
    preprocessing_parameters
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/features/text_feature.py", line 99, in get_feature_meta
    preprocessing_parameters['lowercase']
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/features/text_feature.py", line 80, in feature_meta
    lowercase=lowercase
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/strings_utils.py", line 91, in create_vocabulary
    line.lower() if lowercase else line)
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/strings_utils.py", line 212, in english_tokenize
    return process_text(text, load_nlp_pipeline())
  File "/home/moooo/.local/lib/python3.6/site-packages/ludwig/utils/nlp_utils.py", line 37, in load_nlp_pipeline
    import en_core_web_sm
ModuleNotFoundError: No module named 'en_core_web_sm'
moooo@u18:~/ludwig$ python -m spacy download en
/usr/bin/python: No module named spacy
```

**Comment by VZWUSER** [comment]
Thank you. That did the trick for inline model definition. Any ideas as to why it does not like my YAML file?
[model_definition .yaml.txt](https://github.com/uber/ludwig/files/3022802/model_definition.yaml.txt)

**Comment by w4nderlust** [comment]
you need the `-` in the yaml for each element of a list.
