### ISSUE TITLE
Permission denied for visualize

### ISSUE THREAD

**Issue by skim2257** [uber/ludwig#253]
The train command runs perfectly fine: 
`ludwig train --data_csv "Iris.csv" -mdf "model.yaml"`

But when I attempt to visualize:
`ludwig visualize -v learning_curves -ts "results/_run_7"`

I receive a permission error (last 3 lines): 
```
  File "c:\users\sejin\appdata\local\programs\python\python36\lib\site-packages\ludwig\visualize.py", line 43, in <listcomp>
    for learning_stats_f in
  File "c:\users\sejin\appdata\local\programs\python\python36\lib\site-packages\ludwig\utils\data_utils.py", line 65, in load_json
    with open(data_fp, 'r') as input_file:
PermissionError: [Errno 13] Permission denied: 'results/_run_7'
```

It might be worth noting that I've seen this issue only on some computers, while other setups run perfectly fine.

**Comment by w4nderlust** [comment]
You have to open the trainin_statistics.json file contained in that directory and you need to have the permission to the file.
