### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#255]
F:\ezNeuralJoiner\alt_1m_classifier_eng>pushd "F:\ezNeuralJoiner\alt_1m_classifier_eng\"

F:\ezNeuralJoiner\alt_1m_classifier_eng>ludwig experiment --data_csv "F:\ezNeuralJoiner\alt_1m_classifier_eng\alt_en-US_zh-CN_20171222.tmx.src.txt.1_full.csv" --model_definition_file "F:\ezNeuralJoiner\alt_1m_classifier_eng\sent_complete_model_definition_classifier.yaml"
e:\programdata\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Experiment

Experiment name: experiment
Model name: run
Output path: results\experiment_run_1

ludwig_version: '0.1.0'
command: ('E:\\ProgramData\\Anaconda3\\Scripts\\ludwig experiment --data_csv '
 'F:\\ezNeuralJoiner\\alt_1m_classifier_eng\\alt_en-US_zh-CN_20171222.tmx.src.txt.1_full.csv '
 '--model_definition_file '
 'F:\\ezNeuralJoiner\\alt_1m_classifier_eng\\sent_complete_model_definition_classifier.yaml')
dataset_type: 'F:\\ezNeuralJoiner\\alt_1m_classifier_eng\\alt_en-US_zh-CN_20171222.tmx.src.txt.1_full.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'English',
                              'tied_weights': None,
                              'type': 'text'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'class_distance_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'Completeness',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': 10000,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': False},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {'missing_value_strategy': 'backfill'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 1,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 3,
                    'epochs': 200,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}

Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading NLP pipeline
Traceback (most recent call last):
  File "e:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 548, in cli
    experiment(**vars(args))
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 234, in experiment
    random_seed=random_seed
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 457, in preprocess_for_training
    random_seed=random_seed
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 62, in build_dataset
    **kwargs
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 90, in build_dataset_df
    global_preprocessing_parameters
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 165, in build_data
    preprocessing_parameters
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\features\text_feature.py", line 165, in add_feature_data
    metadata[feature['name']], preprocessing_parameters
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\features\text_feature.py", line 150, in feature_data
    preprocessing_parameters['lowercase']
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\utils\strings_utils.py", line 165, in build_sequence_matrix
    dtype=format_dtype)
  File "e:\programdata\anaconda3\lib\site-packages\numpy\core\numeric.py", line 335, in full
    a = empty(shape, dtype, order)
MemoryError

**Comment by w4nderlust** [comment]
Issues that are not correctly formatted will be closed. If you want to get help provide all the required information.
