### ISSUE TITLE
Generate integer numerical outputs, not float 

### ISSUE THREAD

**Issue by SachitNayak** [uber/ludwig#259]
Hi,

I'm trying to predict a sequence of next 5 integers using 5 other integers as output. I'm using type: numerical for all the inputs and outputs. However as I understand 'numerical' type encompasses floating values, hence on prediction I get float values as output. Is there any encoder/decoder that I can use to map those float output values to the nearest integer output values? My sincerest thanks in advance! I've used ludwig for last 3 weeks now, I'm really enjoying it. Thanks.

**Comment by w4nderlust** [comment]
@SachitNayak thank you for your comments!
It really depends on what those numbers actually mean. are those integers representing different entities / classes? Does the order and value matter? (meaning is 1 closer to 2 than it is to 20, for instance)
If the different integers represent different classes, you should use `sequence` as datatype. If the values and ordering do matter, then I'm curious to know about your usecase, but what I would do is to obtain the floats and then I would just ceil the obtained values after receiving them from Ludwig.
If there is a strong reason for, i could potentially add a 'ceil' parameter to the numerical output, but I would need to understand the usecase well first.

**Comment by SachitNayak** [comment]
> @SachitNayak thank you for your comments!
> It really depends on what those numbers actually mean. are those integers representing different entities / classes? Does the order and value matter? (meaning is 1 closer to 2 than it is to 20, for instance)
> If the different integers represent different classes, you should use `sequence` as datatype. If the values and ordering do matter, then I'm curious to know about your usecase, but what I would do is to obtain the floats and then I would just ceil the obtained values after receiving them from Ludwig.
> If there is a strong reason for, i could potentially add a 'ceil' parameter to the numerical output, but I would need to understand the usecase well first.

Hi @w4nderlust , my use case is derby prediction of top 5 horses based on previous race results. There are 40 horses in all; I'm representing each by a unique integer between 1 and 40. So far I've tried various combinations of inputs and input types and also output types to predict the most probable 5 winners of the next race. I tried 10 **'timeseries' inputs** (representing past 10 races), each timeseries input containing 5 winners of the pertinent races. I have 5 output variables y1, y2, y3, y4, y5 each of numerical type and representing 5 highly probable winners of the upcoming race. 

For the **numerical output** types I get floating values. I bound the value to [1,40] using the clip property of output features. However they are still floating numbers.

In another attempt I used **'sequence'** type as output with just one output variable y, which has 5 winners in it separated by commas. However interestingly in this case it produces the same set of 5 horses as winners for every possible race (I tested against 1000 races; all 1000 races had the same 5 horses predicted to be the winners by the model). Another interesting thing I noticed with sequences is that during training phase, ludwig automatically uses 'edit distance' metric, which is normally used for text sequences and not for numerical types.

I also attempted using **category type** for the outputs, the predictions generated are only <UNK> token for all test inputs.

I believe ceil parameter to the output feature would be a wonderful enhancement, because it is really cumbersome for me to go into the results/ directory and take all y<num>_predictions.csv files and then run ceil on each of those 1000 odd numbers from each of the 5 output files.

Really appreciate your consideration. Thank you. Any thoughts or suggestions will be much appreciated.

**Comment by w4nderlust** [comment]
@SachitNayak this sounds like a each horse is it's own category, you could replace those integers with the unique name of the horse and it would be the same, meaning integers in this case are just IDs of entities. For this reason, `sequence` is the right choice. In order to use it, you need one column containing the names of the horses separated by space. If the names are integer ids, or strings or any other thing, it doesn't matter, they will be treated like strings. So for instance, one possible values is `horse2 horse7 horse1 horse3 horse4`. The edit distance is a generic measure of distance between discrete sequences, in this case it would be useful for you to understand how far the prediction of the model is from the true sequence, 5 would mean it's completely off, 0 means it's perfect.

**Comment by w4nderlust** [comment]
Anyway, closing this as it's not an issue, but feel free either to keep commenting or to move this to the Gitq forum.

**Comment by SachitNayak** [comment]
@w4nderlust Alright perfect! I was wondering how do I embed the timeseries info along with the sequence type in the inputs? ( for instance 10 sequence columns for 10 past races)?

**Comment by bertyhell** [comment]
I'm wondering what the correct type is when the output features represent positions on a chess board.
eg: [1, 3] is the first row, third column position.
Would you still use numerical and ceil the results?

**Comment by w4nderlust** [comment]
I would use two categories.
