### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by renatochacon** [uber/ludwig#261]
Hello. I was able to use 'ludwig experiment' on the titanic's datasets on kaggle, just as described here https://uber.github.io/ludwig/examples/ using the suggested yaml file.

I also tried to use it to train a dataset, but got this on terminal:

$ ludwig train --data_csv train.csv --model_definition modelo.yaml
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Train

Traceback (most recent call last):
  File "/home/renatochacon/ludwig/venv/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 86, in main
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 64, in __init__
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 70, in train
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/train.py", line 729, in cli
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/train.py", line 170, in full_train
  File "/home/renatochacon/ludwig/venv/lib/python3.5/site-packages/ludwig-0.1.0-py3.5.egg/ludwig/utils/defaults.py", line 137, in merge_with_defaults
AttributeError: 'str' object has no attribute 'get'

**Comment by w4nderlust** [comment]
Please use the latest code from master and try again.
Uninstall Ludwig, then:
pip install http://github.com/uber/ludwig/zipball/master

**Comment by renatochacon** [comment]
Thank you. I'd like to know one more thing, please:

I was able to work on the train.csv which contais all columns, including features (input variables) and target (output variable). But how do I use ludwig to predict on datasets like the one from test.csv which doesn't contain the target column 'Survived'?

**Comment by w4nderlust** [comment]
Read the docs, in the predict section of the user guide. There's a parameter `--only_predict`.

**Comment by vreyespue** [comment]
@w4nderlust I think in the last version of ludwig (0.4) this is happening again. 
I get as well the mentioned error message, i.e. 
```
$ python3 simple_model_training.py
Traceback (most recent call last):
  File "simple_model_training.py", line 25, in <module>
    logging_level=logging.INFO)
  File "/Users/vicente.reyes/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ludwig/api.py", line 193, in __init__
    self.backend = initialize_backend(backend or config.get('backend'))
AttributeError: 'str' object has no attribute 'get'
```
Could you maybe double check?
If so, should we reopen this issue, or create a new one?
Many thanks and best regards.

**Comment by w4nderlust** [comment]
@vreyespue it's a different error.
Can you please open a separate issue about it with instructions on how to reproduce it?
I run the `simple_model_training.py` in the `examples/titanic`, which I believe is what you were running, and it works fine.

**Comment by vreyespue** [comment]
Hi @w4nderlust I got this issue both in macos and linux, simply by doing a `pip install ludwig` and executing `simple_model_training.py` in the `examples/titanic` folder. Actually I think it is because [here](https://github.com/ludwig-ai/ludwig/blob/master/examples/titanic/simple_model_training.py#L24) we call the api with config as str (i.e. file path), and [in the api](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/api.py#L193) we try to get the `backend` from the string, which results in an error. I opened [a PR](https://github.com/ludwig-ai/ludwig/pull/1213) to resolve the issue. Many thanks and best regards.
#1213

**Comment by Derrick56007** [comment]
Can confirm this issue on linux with ludwig==0.4.

**Comment by w4nderlust** [comment]
The PR #1213 was merged.

**Comment by Judy-Bloom** [comment]
@w4nderlust Hi Pierre, I'm getting the same issue as vreyespue. Config file in same directory as python file. Replacing the config YAML with a python dictionary and works as expected. Any thoughts?
Error: AttributeError: 'str' object has no attribute 'get'

**Comment by w4nderlust** [comment]
@Judy-Bloom the issue has been solved but we haven't released a new version yet. You can install Ludwig by cloning the `tf-legacy` branch in the meantime. We are going to release a v0.4.1 this week anyway ;)

**Comment by Judy-Bloom** [comment]
Thanks man :) looking forward to it.
