### ISSUE TITLE
cant import ludwig

### ISSUE THREAD

**Issue by emudria** [uber/ludwig#262]
**Describe the bug**
I have installed ludwig via pip but when I try to import it in python it gives error and kills python 

```
(base) C:\>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ludwig import LudwigModel
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-04-01 10:28:04.393999: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

```

**Screenshots**
I have added a screen shot as well.

**Environment (please complete the following information):**
 - OS: [windows10]
 
- '3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'
- Ludwig version

**Additional context**
I did pip install ludwig
and got this issue and later even did 
pip to master zip file
![2019-04-01 10 28 21]
(https://user-images.githubusercontent.com/18720437/55296740-8ae3e080-5469-11e9-876d-84f050319afb.png)

**Comment by w4nderlust** [comment]
Please use the latest code from master, it has updated dependencies that solve the issue.

**Comment by upalchowdhury** [comment]
hi , "Please use the latest code from master" can you provide more details please thanks .

**Comment by w4nderlust** [comment]
When this qquestion was asked the latest version of the code on master had moved to a newer version of numpy that did not have the problem, so i was suggesting to use that instead of the package on Pypi, but thie issue with numpy versions has vbeen solved long ago.
