### ISSUE TITLE
Question: Two data types one input feature?

### ISSUE THREAD

**Issue by danielduckworth** [uber/ludwig#280]
Suppose I have a single input feature that in some cases is text and in some cases is an image. Is there a way for an input feature to be one or the other?

**Comment by w4nderlust** [comment]
it means that they are not the same input feature, they are two separate ones. And if you have two features and sometimes one of the two is missing you can have a placeholder (empty text or an all black image) when one of the two is missing. Closing as this is not an issue, but a discussion. Feel free to continue it on Gitq if you like.
