### ISSUE TITLE
KeyError: 'tied_weights'

### ISSUE THREAD

**Issue by Rhasz** [uber/ludwig#293]
**Describe the bug**
Using API to load a pre trained model and getting the error
KeyError: 'tied_weights'

**To Reproduce**
Run in Google Colab
Python code so indents may need to be added for loops and conditionals for code to work.

**Imports and Installations**
_from __future__ import print_function
import math
import time
from IPython import display
from matplotlib import cm
from matplotlib import gridspec
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import metrics
import tensorflow as tf
from tensorflow.python.data import Dataset
tf.logging.set_verbosity(tf.logging.ERROR)
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.2f}'.format
!pip3 install ludwig
import yaml
from ludwig import LudwigModel_

**ModelDefinition:**
_dict = {'input_features': [{'name': 'Open_Price', 'type': 'numerical'}], 'output_features': [{'name': 'Closing_Price', 'type': 'numerical'}], 'training':{'epochs': 3000}}
model_definition = dict 
ludwig_model = LudwigModel(model_definition)_

**Sample Data:**
The full code pulls data from an exchange through their API, the below is a modified version to generate a sample.
Data is generated in code
Create a data frame with first series having numerical and a second series having numerical...
Series are generated in a loop using append

Replace stock_bars[i].o and stock_bars[i].o with a constant like 200.00 in following code to generate sample series

_limit = 1000
stock_open = []
stock_close = []
if len(stock_open) == 0:
   for i in range(limit):
       stock_open.append(stock_bars[i].o)_

_if len(stock_close) == 0:
   for i in range(limit):
          stock_close.append(stock_bars[i].c)_

_df = pd.DataFrame({ "Open_Price": pd.Series(stock_open), "Closing_Price": pd.Series(stock_close)})
print(df)
df.describe()_

**Training**
_train_stats = ludwig_model.train(df)_

**Saving** (Drive needs to be mounted before saving, will need to also replace stock_symbol)

_save_path = "gdrive/My Drive/Colab Notebooks/" + stock_symbol
ludwig_model.save(save_path)_

**Loading**

_model_dir = "gdrive/My Drive/Colab Notebooks/" + stock_symbol
ludwig_model = []
ludwig_model = LudwigModel.load(model_dir)_

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
Model loaded

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS]  (colab)
 - Version [e.g. 22] (colab)
- Python version (colab)
- Ludwig version (!pip3 install ludwig)

**Additional context**

Code for mounting a drive
_from google.colab import drive
drive.mount('/content/gdrive')_

**Comment by msaisumanth** [comment]
@Rhasz Could you please paste the stacktrace?

**Comment by Rhasz** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-48-c45ece5c68d7> in <module>()
      1 model_dir = "gdrive/My Drive/Colab Notebooks/" + stock_symbol
      2 ludwig_model = []
----> 3 ludwig_model = LudwigModel.load(model_dir)

/usr/local/lib/python3.6/dist-packages/ludwig/api.py in load(model_dir, logging_level)
    197             set_disable_progressbar(True)
    198 
--> 199         model, model_definition = load_model_and_definition(model_dir)
    200         ludwig_model = LudwigModel(model_definition)
    201         ludwig_model.model = model

/usr/local/lib/python3.6/dist-packages/ludwig/models/model.py in load_model_and_definition(model_dir, use_horovod)
   1619         )
   1620     )
-> 1621     model = Model.load(model_dir, use_horovod=use_horovod)
   1622     return model, model_definition

/usr/local/lib/python3.6/dist-packages/ludwig/models/model.py in load(load_path, use_horovod)
   1331         )
   1332         hyperparameters = load_json(hyperparameter_file)
-> 1333         model = Model(use_horovod=use_horovod, **hyperparameters)
   1334         model.weights_save_path = os.path.join(
   1335             load_path,

/usr/local/lib/python3.6/dist-packages/ludwig/models/model.py in __init__(self, input_features, output_features, combiner, training, preprocessing, use_horovod, random_seed, debug, **kwargs)
    107             preprocessing,
    108             random_seed,
--> 109             **kwargs
    110         )
    111 

/usr/local/lib/python3.6/dist-packages/ludwig/models/model.py in __build(self, input_features, output_features, combiner, training, preprocessing, random_seed, **kwargs)
    157                 self.regularizer,
    158                 self.dropout_rate,
--> 159                 is_training=self.is_training
    160             )
    161 

/usr/local/lib/python3.6/dist-packages/ludwig/models/inputs.py in build_inputs(input_features, regularizer, dropout_rate, is_training, **kwargs)
     37                                                     dropout_rate,
     38                                                     is_training=is_training,
---> 39                                                     **kwargs)
     40         feature_representations[input_feature['name']] = feature_representation
     41     return feature_representations

/usr/local/lib/python3.6/dist-packages/ludwig/models/inputs.py in build_single_input(input_feature, regularizer, dropout_rate, is_training, **kwargs)
     52         input_feature['name']
     53     ))
---> 54     if input_feature['tied_weights'] is not None:
     55         scope_name = input_feature['tied_weights']
     56 

KeyError: 'tied_weights'

**Comment by w4nderlust** [comment]
Fixed, closing this, comment if it doesn't solve the isue for you.

**Comment by Rhasz** [comment]
I got same error
