### ISSUE TITLE
Normalization for numerical inputs

### ISSUE THREAD

**Issue by Guufii** [uber/ludwig#296]
**Is your feature request related to a problem? Please describe.**
It seems as if numerical inputs for Ludwig do not get normalized to zero mean and a standard deviation of one. I have to preprocess the data manually before and keep the statistics of the inputs to normalize unseen data.

**Describe the use case**
Useful for all users that deal with numerical data.

**Describe the solution you'd like**
I would like an option in the preprocessing setting of the model dict to normalize inputs and store the statistics in the final model file. So if I predict new data I do not have to do any manual normalization steps before.

Best
G

**Comment by w4nderlust** [comment]
Makes sense. Will add it to the list of features. Thanks for requesting it.

**Comment by lordeddard** [comment]
I would like to work on this feature. @w4nderlust , can I? Thanks in advance!

**Comment by Guufii** [comment]
Yes please go ahead... Thanks

**Comment by Guufii** [comment]
I that massage was not intended for me... lets see what @w4nderlust says.

**Comment by w4nderlust** [comment]
@lordeddard yes sure.
Let me give you some instructions:
you should add some code in `numerical_feature.py`. In particular in the base feature you can add a `normalization_strategy` preprocessing parameter. The default value is `None`, the optional value is `zscore` and maybe also `minmax`.
In `get_feature_meta` if the `normalization_strategy` in preprocessing is `zscore` you compute mean and standard deviation of the column and return those values inside the return dictionary (they will be saved in the metadata json files). If `minmax` then you will collect minimum and maximum.
in `add_feature_data` if the `normalization_strategy` in preprocessing is `zscore` you can obtain mean and standard deviation from the metadata and use them to normalize the data column, something similar for `minmax`.
It should be pretty straightforward.
Once you are done, please write a testcase to make sure it works.
Finally don't forget to update the documentation, in particular `mkdocs/docs/user_guide.md`.
Let me know if something is not clear or if you need support,

**Comment by lordeddard** [comment]
Thanks for the instructions. I’ll start working on this.

**Comment by w4nderlust** [comment]
@lordeddard thank you for working on this!

**Comment by w4nderlust** [comment]
@lordeddard added this functionality, thanks so much! Now the user can normalize with zscore, normalize with minmax and not normalize at all. If people want to add additional normalization strategies, if would be pretty straightworward, so feel free to contribute.

**Comment by Guufii** [comment]
@lordeddard  Also thanks from my side...
