### ISSUE TITLE
Inconsistent Split Probabilities

### ISSUE THREAD

**Issue by dorintt** [uber/ludwig#297]
The defaults are described as `split_probabilities: [0.7, 0.2, 0.1]` here https://uber.github.io/ludwig/user_guide/#preprocessing

However, by looking at model_definition in `description.json`  (experiment results directory) we can see `"split_probabilities": [0.7, 0.1, 0.2]`. I did not overwrite them in my supplied model definition, these are the actual defaults.

I don't know if this is only a json config bug or the data is actually split in inconsistent ways during training, but it's misleading at best.

Also to avoid possible confussions / bugs I suggest something like `split_probabilities: {'train':0.7, 'validation': 0.2, 'test':0.1}`

**Comment by w4nderlust** [comment]
Thanks for reporting. It’s just a typo in the docs, will fix.

**Comment by w4nderlust** [comment]
Solved
