### ISSUE TITLE
Issue with ludwig.visualize

### ISSUE THREAD

**Issue by SaraFdezCalleja** [uber/ludwig#305]
Hi, 

thanks for sharing this amazing project. I think it is not a bug in the project but a problem with the installation of the packages but maybe you can help me. 
I'm running 
python -m ludwig.visualize --visualization learning_curves --training_statistics results/experiment_run_5/training_statistics.json
 after running the example => python -m ludwig.experiment   --data_csv reuters-allcats.csv  --model_definition_file model_definition.yaml

I'm having this as error : 
usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'ludwig.visualize' found in sys.modules after import of package 'ludwig', but prior to execution of 'ludwig.visualize'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))

![image](https://user-images.githubusercontent.com/49948254/56661263-ad9c9a00-66a1-11e9-9548-08c421484b5a.png)

I'm running everything on a windows pc. And i've installed a windows subsystem for linux. 

I hope ypu can help me, thank you!!

**Comment by w4nderlust** [comment]
@SaraFdezCalleja you're welcome.
You are seeing that message because you both have Ludwig installed as a package and you running it from within the `ludwig` directory, which contains a `ludwig` package directory. If you run it from another directory (you can also run `ludwig visualize` instead of `python -m ludwig.visualize`) you shouldn't have any problem, the pip installed Ludwig package will be used. Or, if you want to use the code you pulled, uninstall the pip package an run your current command from thepulled directory and it should also work fine.

**Comment by SaraFdezCalleja** [comment]
Hello w4nderlust,

yes!! it works perfect now. Thank you for tour answer, very clear!!!

**Comment by w4nderlust** [comment]
You're welcome!

**Comment by Mariyamimtiaz** [comment]
Hello SaraFdezCalleja,
Hope you are doing well. May you please share the Ludwig visualization command code. Because I am also facing the same problem. 
Thanks in anticipation.

**Comment by w4nderlust** [comment]
It's not about the command but where you are calling it from, please read my previous comment.

**Comment by Mariyamimtiaz** [comment]
The code below not showing a graph. 

![Screenshot_1](https://user-images.githubusercontent.com/45830027/57211605-4a442d80-6ffa-11e9-95da-c78fd56ddcac.png)

**Comment by w4nderlust** [comment]
The visualize command opens a window in the os to visualize the plot, doesn't work on colab.
We are adding the capability to save images and improving the visualization APIs so that they are easy to use programmatically.
In the meantime you can use:
```
from ludwig.visualize import learning_curves
learning_curves(['/content/results/api_experiment_run_0/training_statistics.json'])
```
