### ISSUE TITLE
TensorFlow contrib dependency

### ISSUE THREAD

**Issue by floscha** [uber/ludwig#306]
When importing Ludwig, I receive the following warning: `WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.` This is because currently, Ludwig uses the following modules from *contrib*:
- rnn
- seq2seq
- layers

All of these are contained in the TensorFlow [Addons](https://github.com/tensorflow/addons) package which is [suggested as a replacement for contrib](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md). Are there any plans yet to move away from *tf.contrib*? If you want, I can create a PR to move the listed dependencies to *addons* instead.

**Comment by w4nderlust** [comment]
@floscha I was planning to do that once moving to TF 2.0 would become a necessity, but if addons works both with TF 1.13.1 and TF 2.0 and a porting to tfa can be done now without particular problems, than I would gladly accept a PR about it! Thanks for proposing to do that.

**Comment by w4nderlust** [comment]
@floscha thank you so much for looking into this, it's going to be really useful when moving to TF 2.0.
At the moment I believe that TF 2.0 is still pretty much in its infancy, and I guess many things will change over time (in particular with RNNs, as many features have been completely left behind, like beam search and attention). So at the moment my strategy is to wait for those things to come back and to have something as close as a 1:1 mapping from 1 to 2. When that happens then i will start to port, or at least, that's my intent at the moment.

**Comment by w4nderlust** [comment]
Closing this as the `tf2_porting` branch, which will become v0.3 already solved this issue ;)
