### ISSUE TITLE
cant import LudwigModel

### ISSUE THREAD

**Issue by upalchowdhury** [uber/ludwig#318]
**Describe the bug**
---------------------------------------------------------------------------
from ludwig.api import LudwigModel
             or 
from ludwig import LudwigModel

results in below error , 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-99-5a4a2b29af26> in <module>()
----> 1 from ludwig.api import LudwigModel

Can you please provide guidance on how to fix it . thanks

**Comment by w4nderlust** [comment]
Hi, please provide all the details to make the issue reproducible.
On all machines and configurations I've ever tried it imports just fine.

**Comment by Mariyamimtiaz** [comment]
I am also facing same problem.
![Screenshot_11](https://user-images.githubusercontent.com/45830027/57120091-3e513500-6d88-11e9-870e-c98c868e7d1c.png)

**Comment by msaisumanth** [comment]
@Mariyamimtiaz please provide the version of ludwig you're using and how you've installed it as well. 
It's hard to understand why this is happening without context.

**Comment by w4nderlust** [comment]
You should do `from ludwig.api import LudwigModel`. Closing this, feel free to post again if it doedn't solve your issue.

**Comment by Mariyamimtiaz** [comment]
Now its working. Thanks a lot.
