### ISSUE TITLE
Add Google Cloud Storage support to Ludwig

### ISSUE THREAD

**Issue by gogasca** [uber/ludwig#327]
**Is your feature request related to a problem? Please describe.**
Some training data is located in Google Cloud Storage or any other Cloud file systems:

 * Google Cloud: [Google Cloud Storage](https://cloud.google.com/storage/) `gs://`
 * Amazon Web Services: [AWS S3](https://aws.amazon.com/s3/) `s3://`
 * Azure: [Azure DataLake Store](https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-overview), [Azure Blob Store](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-overview) `adl://, abs://`
    

We need the ability to declare training data path located in GCS when running a training job in ludwig 

Example:
```
ludwig train --data_csv gs://ludwig/Tweets.csv --model_definition_file model_definition.yaml --output_directory /tmp/
```

**Describe the use case**
Training data exists in GCS already, we would like to just reference data as a central location.

**Describe the solution you'd like**
Add support for [gcsfs](https://github.com/dask/gcsfs) library 

**Describe alternatives you've considered**
Copy GCS data in CSV /HDF5 format to local folder and process from there.

**Additional context**
N/A

**Comment by w4nderlust** [comment]
Thanks for you PR, we will look at it carefully.
