### ISSUE TITLE
sequence_concat and sequence encoders for combiner failing

### ISSUE THREAD

**Issue by Guufii** [uber/ludwig#335]
Hi,
I am experimenting with different encoders for the combiner. If I use something else than the standard concat combiner, I get an error in combiners.py, line 139, in __call__
    representations_size = representation.shape[2].value
since sequence and timeseries features have only a dimension of 2. I have specified main_sequence_feature to be sure the correct input is chosen.

I use the following model_dict:

model_definition = {'combiner': {
        'type': 'sequence_concat',
        'encoder': 'cnnrnn',
        'cell_type': 'rnn',
        'main_sequence_feature': 'DEBT_EQUITY',
        # 'main_sequence_feature': 'RATING',
        'conv_layers': [{'activation': 'relu',
                         'filter_size': 3,
                         'norm': None,
                         'num_filters': 32,
                         'pool_size': 2,
                         'pool_stride': 2,
                         'regularize': True}]},
                        'input_features': [{'name': 'TICKER',
                                            'type': 'category'},
                                           {'name': 'DEBT_EQUITY',
                                            'type': 'timeseries'},
                                           {'name': 'RATING',
                                            'type': 'sequence'},
                                           {'name': 'YEAR',
                                            'type': 'timeseries'}],
                        'output_features': [{'name': 'RATING_Label',
                                             'type': 'category'}],
                        }

Together with the attached dummy input.
[data_preprocessed.zip](https://github.com/uber/ludwig/files/3163449/data_preprocessed.zip)

Hope you can reproduce this...

Best
G

**Comment by w4nderlust** [comment]
As explained [here](https://uber.github.io/ludwig/user_guide/#sequence-concat-combiner) the sequence concat combiner looks for rank 3 tensors among the features. And as explained in all sequence, text and timeseries encoders the way to make them output a rank 3 tensor is by setting `reduce_output: null`.
Please try to add that to all your input features (but TICKER), make sure they all have the same second dimension (sequence length, and let me know if it works for you.
Will probably improve the description of the sequence concat combiner to make this point more clear.

**Comment by Guufii** [comment]
Hi @w4nderlust,
thanks for your explanation, that was exactly the cause of the error.
Best
G
