### ISSUE TITLE
Logging issue when activating Comet contrib

### ISSUE THREAD

**Issue by Lothiraldan** [uber/ludwig#340]
**Describe the bug**

When activating the Comet contrib, most of Ludwig log message disappears.

**To Reproduce**

Launch: `ludwig experiment --data_csv reuters-allcats.csv --model_definition_file model_definition.yaml -l info --comet`

You won't see the following output:
```
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.2 - Experiment

Experiment name: experiment
Model name: run
Output path: results/experiment_run_43


ludwig_version: '0.1.2'
```

**Expected behavior**

The log messages should be displayed when the Comet contrib is activated.

**Environment (please complete the following information):**
 - OS: Fedora
 - Version 28
- Python version: 3.6.8
- Ludwig version: 0.1.2

**Additional context**

I think the issue is that ludwig is using the root-level logger configured through `logging.basicConfig`. The comet contrib integration contains some logging calls, for example, https://github.com/uber/ludwig/blob/master/ludwig/contribs/comet.py#L56.

Those calls happen before any `basicConfig` call https://github.com/uber/ludwig/blob/master/ludwig/experiment.py#L461.

The issue with calling the root-level `logging.info`, `logging.error` and so on is that they will call `logging.basicConfig` on their own if the root logger is not configured yet https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L2065. The direct effect is that the first call to `logging.info` will configure the root logger with no configuration which will create a StreamHandler pointing to `/dev/stderr`.

The unfortunate side-effect is that calling `basicConfig` will do nothing as the root handler as already a handler so the root logger will not be set to the right log level and the stream handler will not point to the right device.

I would recommend moving from using the root logger and configure the logger through `basicConfig` to using a `ludwig` logger and configure it manually, it's not that more complex. I can help if wanted.

One last issue with using the root logger is when configuring the root logger to the debug level, all libraries which are logging will start displaying their log messages. That includes requests and is polluting the output. Using a separate logger would also solve this issue.

**Comment by w4nderlust** [comment]
@Lothiraldan thanks for reporting this. It is indeed a bug to fix. Also notifying @dsblank as he is the main contributor of the comet integration.
Would gladly accept your help offer on this. I'd like to avoid having a logger object that is passed around the whole codebase, but apart from that I'm open to suggestions.

**Comment by dsblank** [comment]
@w4nderlust Yes, and @Lothiraldan and I both are on the Comet team, so we have already been discussing this. @Lothiraldan has much expertise in loggers, so I look forward to his suggestions as well.

**Comment by Lothiraldan** [comment]
Hi @w4nderlust, thank you for your prompt answer. I forgot to said that I'm working with @dsblank in the Comet team.

Having a non-global logger is ideal but not always feasible.

The approach I'm using in my projects is the following, use a logger per module: `LOGGER = logging.getLogger(__name__)`. As the __name__ often contains your project name, you get will get loggers like `dulwich`, `dulwich.experiment`, `dulwich.contribs.comet`. I think I have taken this idea from Django https://docs.djangoproject.com/en/2.1/topics/logging/#using-logging.

This way you can configure the top-level logger for your project and every other loggers will just propagate the log messages to it and uses the configured handlers. This unlock having different log level on a module basis or even different handlers if needed.

I would highly recommend having a central function where the top-level logger is configured, something like https://github.com/Lothiraldan/balto/blob/master/balto/_logging.py#L6, I found it that it really helps for maintaining a coherent logging configuration.

Apart from that, the Ludwig project seems to be only using a StreamHandler right now so there is no much expertise I can give you on the handlers subjects.

Don't hesitate if you have some questions.

**Comment by w4nderlust** [comment]
Thanks for the detailed explanation @Lothiraldan . @msaisumanth Is on top of it. It looks pretty straightforward: have a single global logger setup function, add a logger in every module, use that logger instead of logging. I expect this to be solved pretty quickly.
Thank you again!

**Comment by msaisumanth** [comment]
@Lothiraldan please take a look at https://github.com/uber/ludwig/pull/352
I was able to verify that the output is getting printed as expected. @w4nderlust if this makes sense, I'll modify the other modules as well.

**Comment by w4nderlust** [comment]
@Lothiraldan it would be great if you could take a look at the PR, it should solve the issue, but wanted to doublecheck with you before merging it.

**Comment by w4nderlust** [comment]
We merged the PR as we believe it works fine, @Lothiraldan if you could take a look at it to confirm it's fine for you too, that owuld be great.

**Comment by Lothiraldan** [comment]
I made some comments, sorry for the delay, I was busy with some other stuff.
