### ISSUE TITLE
early_stop does not get updated on training resume

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#343]
When resuming a training of a model that has been (for example) stopped due to lack of validation for X epochs, if the model YAML is updated to increase the early_stop value to a greater value of X, ludwig stops the training right away.

Editing the corresponding early_stop parameter in the description.json contained in the model directory with the new intended value fixes the issue, and it is a valid workaround.

**To Reproduce**
Train a model with a model definition YAML containing an early_stop value of 1
Edit the YAML and specify a higher early_stop value (like 10, because you set a "too low" limit and you want to fix that and resume training)
Try to resume the training and you will be stopped at the original early_stop value

**Expected behavior**
description.json value is updated from the YAML reflecting the new value when starting a train\resume

**Comment by w4nderlust** [comment]
Thanks for posting this, will take a look.

**Comment by msaisumanth** [comment]
@carlogrisetti I am unable to reproduce this actually. Here's what I did. I set early_stop = 1 in the model definition and ran this command:
```code
ludwig experiment --data_csv data/train.csv --model_definition_file data/model_definition.yaml
```

The training stopped after 4 epochs. After that, I updated the model definition to have early_stop = 10 and ran this command:
```code
ludwig experiment --data_csv data/train.csv --model_definition_file data/model_definition.yaml -l warning --model_resume_path=results/experiment_run_34/
```

This time, the model was trained for 27 epochs and the description.json was updated to have early_stop = 10. 

<img width="468" alt="Screen Shot 2019-05-21 at 1 59 23 PM" src="https://user-images.githubusercontent.com/17418219/58130346-ab5e2a80-7bd0-11e9-8457-eba6ef8c2d53.png">

Could you please help me reproduce the error?

**Comment by carlogrisetti** [comment]
I'll try to repro as soon as I can. Please bear with me :)

**Comment by carlogrisetti** [comment]
I cannot repro it anymore on the current master... I suppose too much time has passed and I don't have the same conditions anymore (or i simply switched epochs and early stop? dunno and never will)

Sorry for this

**Comment by w4nderlust** [comment]
No problem. If you encounter the problem again, let us know.
