### ISSUE TITLE
Wrong description for save() method in API documentation

### ISSUE THREAD

**Issue by bvaldeiglesias** [uber/ludwig#345]
**Describe the bug**
In the API documentation, under the LudwigModel methods, the description for the **save** method, it says:

> This function allows for loading pretrained models

Where it should probably say: 

> This function allows saving trained models

**Screenshots**
![image](https://user-images.githubusercontent.com/31254043/57892107-25c72d00-7814-11e9-842f-1e5006674763.png)

**Additional context**
I have an Open Source course in colleges which requires me to contribute in a community, I know is a small issue, but would like to contribute by fixing it!

**Comment by w4nderlust** [comment]
Sure, please go on! In the PR template there is an explanation of how to contribute to the docs (changing both the md files and the html).

**Comment by w4nderlust** [comment]
I actually solved it in the meantime
