### ISSUE TITLE
 Calling model.save(path) causes `Model has not been initialized or loaded` due to missing session

### ISSUE THREAD

**Issue by George3d6** [uber/ludwig#346]
After training a model it becomes impossible to close or save it because the underlying `model.model.sessions` object (presumably the TF sessions) is `None`. Presumably because it gets closed at the end of the training (presumably here: https://github.com/uber/ludwig/blob/master/ludwig/train.py#L311)

**Comment by w4nderlust** [comment]
Will fix soon, it's a regression coming from a code refactoring, thanks for spotting it!
Also, I'm curious about mindsdb, tell me more about it! (maybe in private or on gitq)

**Comment by George3d6** [comment]
Thanks, found a temporary workaround for my usecase in the meanwhile. will email you with info regarding mindsdb :)

**Comment by w4nderlust** [comment]
Yeah a temporary workaround is to load the model again after you train it or reinitializing the session. It introduces unwanted latency, but will work.

**Comment by w4nderlust** [comment]
Pushed a commit that should fix the issue, now when you call `model.train` the session is not closed. Let me know if this solves the problem.

**Comment by George3d6** [comment]
Seems to be fine, though one issue I noticed (maybe I'm miss-reading), is that there's no way to set `should_close_session` to `True` in the API interface. Mind you, I don't need this myself, but maybe someone might... though I guess you want to avoid changes to the public API.

**Comment by w4nderlust** [comment]
It's not needed, if you want to close the session you can call `model.close()`
