### ISSUE TITLE
Categorical output containing spaces produces `<UNK>` predictions.

### ISSUE THREAD

**Issue by pwoolvett** [uber/ludwig#351]
**Describe the bug**
When training a categorical output model, if the dataset contains spaces in the category to predict, the trained model produces `<UNK>` predictions.

**To Reproduce**
1. Use data with categorical output where the categories contain spaces.
2. Train a model using said data.
3. Observe 100% `<UNK>` predictions

sample code:

```
    from ludwig.api import LudwigModel
    import pandas as pd

    MODEL_DEFINITION = {
        "input_features": [
            {"name": "lemmon", "type": "text"},
        ],
        "output_features": [
            {"name": "squeezy", "type": "category"}  # NOTE: values conain trailing space(s)
        ],
    }

    df = pd.DataFrame({
        "lemmon": ["asdf fdsa", "fda fasdfas"],
        "squeezy": ["hello trailingspace ", "goodbye trailingspace "],
    })

    mdl = LudwigModel(MODEL_DEFINITION)

    kw = {
        "data_csv":'estado_test.csv',
        "logging_level": logging.INFO,
    }

    train_results = mdl.train(**kw)
    test_results_df, _ = mdl.test(**kw)

    print(test_results_df.T)
```

```
                                         0            1
squeezy_predictions                  <UNK>        <UNK>
squeezy_probabilities_<UNK>              1            1
squeezy_probabilities_hello    2.93884e-19  5.86868e-15
squeezy_probabilities_goodbye   8.4527e-17  6.17836e-13
squeezy_probability                      1            1
```

**Expected behavior**
`idx2str`, `str2idx`, `str2freq` should contain original values, not stripped versions.

**Additional Context**
I think the culprit is in `CategoryBaseFeature.get_feature_meta`, which calls `ludwig.utils.strings_utils.create_vocabulary` with `format=stripped` (even for output categorical features...). The trained model then uses dictionaries (`idx2str`, `str2idx`, `str2freq`) which contain stripped versions of the categories instead of the real data.

An easy fix is to strip the categorical data in advance...

**Environment:**
 - OS: elementary
 - Version 5.0
- Python version: 3.7.1
- Ludwig version: 0.1.2

**Comment by w4nderlust** [comment]
Thanks @pwoolvett for catching this. Should have been solved by the latest commit. Please confirm.

**Comment by pwoolvett** [comment]
Confirmed: https://github.com/uber/ludwig/commit/f3270aa36a73753d793910d10ce7dcf009ac7d2e fixes the issue
