### ISSUE TITLE
Documentation error for horovod usage

### ISSUE THREAD

**Issue by tboo** [uber/ludwig#354]
Hi -

the user guide has a documentation error/typo on how to activate horovod for [distributed training. ](https://uber.github.io/ludwig/user_guide/#distributed-training)

The ```--horovod``` flag is not working anymore and ```-uh``` or ```--use_horovod``` should be used  as correctly stated in the [training section](https://uber.github.io/ludwig/user_guide/#train) of the user guide.

**Comment by w4nderlust** [comment]
Thanks for pointing it out.
