### ISSUE TITLE
Time series handling

### ISSUE THREAD

**Issue by surendra1472** [uber/ludwig#355]
Hi,

I have dataset with time stamp column where data is in following format

Weather prediction example:

Data format:

Time series column: Timestamp
Input features: Temperature, Humidity, Pressure, WindSpeed, Rain (categorical)
Output feature: Rain (categorical)

One row would look like:
2019-03-07

Goal: predict "Rain" column n step(s) in the future.

If i want to use time series then do i need to convert my date to "2019 03 07" format?? or I need to sepearate
my timeseries column into 3 sepearate columns like Year,month,date

**Comment by w4nderlust** [comment]
Already answered in the other Issue. Closing as it is not an Issue, but a discussion.
