### ISSUE TITLE
Change experiment_name from API

### ISSUE THREAD

**Issue by danicattaneob** [uber/ludwig#357]
The method train from the API doesn't allow to change the default value for the experiment name. I've checked the source code and the method full_train() has this parameter but the train() method that it is used from the API doesn't have it.
I think that the solution for this is really simple, just add the parameter to the train() method. If you want I can make the pull request.
Ludwig: 0.1.2

**Comment by msaisumanth** [comment]
@danicattaneob You're right! Should be a simple change. Please create a PR :)

**Comment by msaisumanth** [comment]
https://github.com/uber/ludwig/pull/359/

**Comment by w4nderlust** [comment]
Solved
