### ISSUE TITLE
Try to load english spacy model while french's one is configured

### ISSUE THREAD

**Issue by nlebreton** [uber/ludwig#364]
**Cannot load the French spacy model**
I need to preprocess text input with a French tokenizer.

**To Reproduce**

The French model was installed using the following command:

`python -m spacy download fr`

I was able to check that fr-core-news-sm is properly installed and that no other spacy module is installed.

pip freeze output attached
[pip_freeze_output.txt](https://github.com/uber/ludwig/files/3256071/pip_freeze_output.txt)

While calling the following command:

`ludwig train --data_csv 20_cate.csv --model_definition "{input_features: [{name: DESCRIPTION_DEMANDE, type: text, preprocessing: {word_format: french_tokenize}}], output_features: [{name: ID_DOMAINE, type: category}]}"`

> Loading NLP pipeline
>  Unable to load spacy model en_core_web_sm. Make sure to download it with: python -m spacy download en_core_web_sm

The full output of Ludwig is attached.
[ludwig_output.txt](https://github.com/uber/ludwig/files/3256070/ludwig_output.txt)

No `word_format: french_<something>` works.

**Environment:**

- Windows 10 Enterprise
- spacy 2.1.4
- Python 3.6.8
- Ludwig 0.1.2

**Comment by nlebreton** [comment]
I replaced in the previous command the word format french_tokenize by an unexisting value (for example, french_tokenizzzzzzzzzzzze), 

`ludwig train --data_csv 20_cate.csv --model_definition "{input_features: [{name: DESCRIPTION_DEMANDE, type: text, preprocessing: {word_format: french_tokenizzzzzzzzzzzze}}], output_features: [{name: ID_DOMAINE, type: category}]}"`

And got the following output:

`ValueError: Key french_tokenizzzzzzzzzzzze not supported, available options: dict_keys(['characters', 'json', 'space', 'space_punct', 'underscore', 'comma', 'untokenized', 'stripped', 'english_tokenize', 'english_tokenize_filter', 'english_tokenize_remove_stopwords', 'english_lemmatize', 'english_lemmatize_filter', 'english_lemmatize_remove_stopwords', 'italian_tokenize', 'italian_tokenize_filter', 'italian_tokenize_remove_stopwords', 'italian_lemmatize', 'italian_lemmatize_filter', 'italian_lemmatize_remove_stopwords', 'spanish_tokenize', 'spanish_tokenize_filter', 'spanish_tokenize_remove_stopwords', 'spanish_lemmatize', 'spanish_lemmatize_filter', 'spanish_lemmatize_remove_stopwords', 'german_tokenize', 'german_tokenize_filter', 'german_tokenize_remove_stopwords', 'german_lemmatize', 'german_lemmatize_filter', 'german_lemmatize_remove_stopwords', 'french_tokenize', 'french_tokenize_filter', 'french_tokenize_remove_stopwords', 'french_lemmatize', 'french_lemmatize_filter', 'french_lemmatize_remove_stopwords', 'portuguese_tokenize', 'portuguese_tokenize_filter', 'portuguese_tokenize_remove_stopwords', 'portuguese_lemmatize', 'portuguese_lemmatize_filter', 'portuguese_lemmatize_remove_stopwords', 'dutch_tokenize', 'dutch_tokenize_filter', 'dutch_tokenize_remove_stopwords', 'dutch_lemmatize', 'dutch_lemmatize_filter', 'dutch_lemmatize_remove_stopwords', 'greek_tokenize', 'greek_tokenize_filter', 'greek_tokenize_remove_stopwords', 'greek_lemmatize', 'greek_lemmatize_filter', 'greek_lemmatize_remove_stopwords', 'multi_tokenize', 'multi_tokenize_filter', 'multi_tokenize_remove_stopwords', 'multi_lemmatize', 'multi_lemmatize_filter', 'multi_lemmatize_remove_stopwords'])`

I shows that:
- the parameter word_format is taken into account
- the value french_tokenize is supposed to be taken into account

**Comment by w4nderlust** [comment]
Fixed it, can you please install from the current master with `pip install git+https://github.com/uber/ludwig.git` and confirm that it solves your problem? Thank you.

**Comment by nlebreton** [comment]
I installed your patch calling `pip install git+https://github.com/uber/ludwig.git`.

[patched_ludwig_install.txt](https://github.com/uber/ludwig/files/3260407/patched_ludwig_install.txt)

I then called `ludwig train --data_csv 20_cate.csv --model_definition "{input_features: [{name: DESCRIPTION_DEMANDE, type: text, preprocessing: {word_format: french_tokenize_filter}}], output_features: [{name: ID_DOMAINE, type: category}]}" ` and got the same result.

> Loading NLP pipeline
> Unable to load spacy model en_core_web_sm. Make sure to download it with: python -m spacy download en_core_web_sm

The details of the output:
[patched_ludwig_output.txt](https://github.com/uber/ludwig/files/3260421/patched_ludwig_output.txt)

**Comment by nlebreton** [comment]
I have tried to set `preprocessing -> text -> word_format` instead of` input_features -> preprocessing -> word_format` and got the same result.

I have tried to set italian_tokenize instead of french_tokenize (knowing that italian's spacy module is not installed) and got the same message about English spacy model.

**Comment by w4nderlust** [comment]
In my tests I replicated exactly your command with fake data and it works fine.
Are you sure you are using the latest code for master? As the version number is the same it may have not replaced the regular version, try uninstalling and reinstalling using the git master.

**Comment by nlebreton** [comment]
The `pip install` output was misleading. The version of the file `ludwig/utils/strings_utils.py` actually was the older one. Uninstall/reinstall solved this and I can confirm that your patch allows to use French word formats. Thx.

**Comment by w4nderlust** [comment]
You're welcome!

**Comment by prakass1** [comment]
@w4nderlust 
The release version-0.1.2 still has the typo where only english processing is used even for other languages in format_registry of string_utils.py.

Master branch though has the changes.  Will you be having those changes in the next release and for now it is better to install master?

**Comment by w4nderlust** [comment]
Yes, the next release will include these changes (it will come soon), for now I suggest using master.
