### ISSUE TITLE
Matplotlib backend option for Visualizations

### ISSUE THREAD

**Issue by gogasca** [uber/ludwig#375]
**Is your feature request related to a problem? Please describe.**

It is a normal use case to install ludwig in a remote server and connect via ssh to run experiments, and since data is stored in remote machine user wants to run visualizations via: 

```ludwig visualize```

**Describe the use case**

Create an Compute Engine instance in GCP (Virtual Machine) using Debian 9

```Linux ludwig-vm 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux```

Connect via gcloud ssh to remote GCP instance using -X option to enable X11 and quartz to be able to display Matplotlib graphs in Local client (MacOS, Windows, Linux, etc.).

**Describe the solution you'd like**
Configuration option to configure matplotlib backend to be able to use Matplotlib over SSH session.
```
ludwig visualize --visualization learning_curves --backend Agg --training_statistics /usr/local/src/ludwig/experiment_run_0/training_statistics.json
```

This will pass a backend parameter which configures the backend in: 
```ludwig/utils/visualization_utils.py```

```
if platform == "darwin":  # OS X
    mpl.use('TkAgg')
```

**Describe alternatives you've considered**
Build ludwig and configure backend manually

**Additional context**

**Comment by w4nderlust** [comment]
@gogasca thanks for the request. i guess the main problem here is that the default backend doesn't work / you are reaching to linux machine from a mac machine right?
Can you also confirm that, for your use case, changing to Agg specifically would make it work?
It will be really easy to implement this change but before doing it I want to be sure about the functionality, as i do not have an easy way to test for it at the moment.

**Comment by gogasca** [comment]
Hi @w4nderlust sorry for the confusion, I was able to make it work without any changes in Ludwig, turned out to be more of a X11 configuration, I'm adding the steps below just for reference:


GCP instance
-------------

Install xauth

```
	apt-get install xauth
```

Edit SSH configuration:

```
sudo vim /etc/ssh/ssh_config
```
Verify the following and enable ForwardX11* information as follows:

```
XAuthLocation /usr/bin/xauth
X11UseLocalhost yes

Host *
   ForwardX11 yes
   ForwardX11Trusted yes
   ForwardX11Timeout 3600

```

Restart sshd service

```
service sshd restart
```


Local Machine
-------------

Install xquartz
```
brew cask install xquartz
```

Verify DISPLAY variable.

```
echo $DISPLAY
```

Edit the following SSH config file:

```
/etc/ssh_config
```

Add the following lines:

```
XAuthLocation /usr/X11/bin/xauth

# Unqualified and default settings
Host *  
  ForwardX11 yes
  ForwardX11Trusted yes
```

Test
----

Connect via SSH to your GCP instance:

Local machine
```
export ZONE="us-west1-b"

function gssh() {
	gcloud compute ssh --ssh-flag="-v" --ssh-flag="-X" $1 --zone ${ZONE}; 
}
```

Connect to Remote instance:

```
gssh ludwid-vm
```

Train a model
```
ludwig train...
```

Visualize results

```
ludwig visualize --visualization learning_curves --training_statistics /usr/local/src/ludwig/experiment_run_0/training_statistics.json
```
You should see an image.

If using sudo to install Ludwig

Copy the Xauth credentials:
```
gogasca@ludwig-vm:~$ xauth list
ludwig-vm/unix:10  MIT-MAGIC-COOKIE-1  ba42d4a1b7bfb4312b5d21db804cdb7c


root@localhost:~$ xauth add ludwig-vm/unix:10  MIT-MAGIC-COOKIE-1  ba42d4a1b7bfb4312b5d21db804cdb7c

ludwig visualize --visualization learning_curves --training_statistics /usr/local/src/ludwig/experiment_run_0/training_statistics.json

```

References:
	https://zngguvnf.org/2018-07-21--matplotlib-on-remote-machine.html
	https://unix.stackexchange.com/questions/110558/su-with-error-x11-connection-rejected-because-of-wrong-authentication
