### ISSUE TITLE
Shrunk favicon in uber.github.io/ludwig/examples/

### ISSUE THREAD

**Issue by Sai-Adarsh** [uber/ludwig#377]
**Describe the bug:**
* Shrunk favicon in [uber.github.io/ludwig/examples](https://uber.github.io/ludwig/examples/).

![img](https://i.imgur.com/1DlxlKm.png)

**Fix:**
* Replace [images/ludwig logo.png](https://uber.github.io/ludwig/images/ludwig_logo.png) with the [favicon1](https://uber.github.io/ludwig/favicon-32x32.png) or [favicon2](https://uber.github.io/ludwig/favicon-16x16.png)

**Expected behavior**
* Responsive, fit favicon.

**Screenshots**
* To be replaced in  [uber.github.io/ludwig/examples](https://uber.github.io/ludwig/examples/):
![img](https://i.imgur.com/kQj9UZg.png)

**Comment by w4nderlust** [comment]
Thank you for figuring this out. The problem is fixed now.
