### ISSUE TITLE
Cannot feed value of shape for Tensor with --model_load_path for NER

### ISSUE THREAD

**Issue by priyaJagan90** [uber/ludwig#386]
**Describe the bug**
I am trying to use  pretrained model weights for initialization for building NER models using --model_load_path (defines the path of my pretrained model). Pretrained model built with 7K  records. I was trying to build another NER model and uses pretrained model weights for initialization with 1.5 K records. But I am getting Cannot feed value of shape for Tensor error while building model with below command. I am using CONLL data for training

**Command:**
ludwig experiment --data_train_csv training/training_1.csv --data_validation_csv validation/validation_1.csv --data_test_csv testing/testing_1.csv --model_load_path results/experiment_run_0/model --model_definition_file model_definition/model_definition.yaml

**Error**
 File "D:\Development_Avecto\Anaconda3\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.1.2', 'console_scripts', 'ludwig')()
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\cli.py", line 94, in main
    CLI()
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\cli.py", line 60, in __init__
    getattr(self, args.command)()
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\cli.py", line 65, in experiment
    experiment.cli(sys.argv[2:])
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\experiment.py", line 472, in cli
    experiment(**vars(args))
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\experiment.py", line 200, in experiment
    **kwargs
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\train.py", line 301, in full_train
    debug=debug
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\train.py", line 461, in train
    **model_definition['training']
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\ludwig\models\model.py", line 523, in train
    is_training=True
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Development_Avecto\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (128, 60) for Tensor 'Tagged_Entities/Tagged_Entities_placeholder:0', which has shape '(?, 113)'

**Expected behavior**
I wanted to create the NER model using prebuilt model wiegths as initialization 

**Environment (please complete the following information):**
 - OS: Windows
 - Version:  Windows10
- Python version : 3.6.5
- Ludwig version : 0.1.2

**Comment by w4nderlust** [comment]
@priyaJagan90 thank you for this report. My best guess so far is that the original dataset and the new one have different parameters for `max_sequence_length`.
Could you please help us replicate the error so that we can debug it?
Ideally we would need:
- yaml definition of the original model
- original data (most likely a subsample, even obfuscated or with synthetic data may work, as long as it leads to the same error)
- command for the second training importing the previous model
- the second dataset (again subsampled, obfuscated or synthesized, as long as the error happens).

**Comment by priyaJagan90** [comment]
Hi,

Thanks for your response. I have attached the subsample for original dataset and dataset for second run.
[Data_subset.zip](https://github.com/uber/ludwig/files/3349713/Data_subset.zip)

**Comment by w4nderlust** [comment]
@priyaJagan90 sorry for taking so long, but I was able to replicate your issue, identify the problem and solving it. Here you find a branch with the fixed code: https://github.com/uber/ludwig/tree/fix_model_load_path
Could you please try it out and confirm that it solved your problem? In that case I will merge the branch in master and the solution will be available to everyone in the next release.

**Comment by priyaJagan90** [comment]
Hi
sorry for the late reply. I couldn't access the link https://github.com/uber/ludwig/tree/fix_model_load_path

**Comment by w4nderlust** [comment]
Yes in the mean time we merged into master. Please try using Ludwig 0.2 the
issue should be solved.

On Fri, 26 Jul 2019 at 09:30, priyaJagan90 <notifications@github.com> wrote:

> Hi
> sorry for the late reply. I couldn't access the link
> https://github.com/uber/ludwig/tree/fix_model_load_path
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_tree_fix-5Fmodel-5Fload-5Fpath&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=23i5BhKdATUS7oX_u6k5vF4VIyvNhU-hk3Tq7C4Vmrs&s=EE1fS-I-swgwjo1gFSgwVDFKnlwWJiAbFkCru-xgp6s&e=>
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_386-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISFJSUFCVGRYQCOEKTLQBMREDA5CNFSM4H2KYZ22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25C7GQ-23issuecomment-2D515518362&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=23i5BhKdATUS7oX_u6k5vF4VIyvNhU-hk3Tq7C4Vmrs&s=3tG0wI-GMXf67AUxTtuUUI-Ul61UBZnLDlTRxONtMOY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISDX4QGMS5OHFYU35DLQBMREDANCNFSM4H2KYZ2Q&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=23i5BhKdATUS7oX_u6k5vF4VIyvNhU-hk3Tq7C4Vmrs&s=u-1sZCYG-HIDGbeJSYstHstzjFBtVNpMcHFxUOHGU98&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs
