### ISSUE TITLE
KeyError: "Unable to open object (object 'danes_word' doesn't exist)"

### ISSUE THREAD

**Issue by tomaszmituta** [uber/ludwig#387]
Hi All,
im new to pyton and ludvig.
i have sample.csv and its got 2 columns and 2 rows , when im adding the column number 3 its says :
File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'danes_word' doesn't exist)"

**To Reproduce**
as you can see i have 3 colums : test.dane.dones - when i run training for test and dane its working but when dane change to danes - it give this error.
As well when i try to train the moged with 2 inputs. 

Sample.csv:

![image](https://user-images.githubusercontent.com/38310716/59952243-c2b46000-947b-11e9-902b-9058ae367052.png)

.yaml file:

input_features:
    -
        name: test
        type: text

output_features:
    -
        name: danes
        type: text

**Expected behavior**
To be able to run/train columns and lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/38310716/59952069-3efa7380-947b-11e9-9edf-ded2222813fa.png)

**Environment (please complete the following information):**
 - OS: WIDOWS 10
 - Version Pycharm -2018.3.4
- Python version 3.6
- Ludwig version 0.1.2

**Additional context**
I will be happy to provide more info to solve this problem.

**Comment by msaisumanth** [comment]
Any particular reason why you're treating 'danes' as text and not a categorical feature? Text would mean that the expected output is a sequence.

**Comment by msaisumanth** [comment]
@tomaszmituta

**Comment by tomaszmituta** [comment]
@msaisumanth , thank you - i see now. i got it right after your comment.
not sure why this was a text.
Also seems that .yaml file was case sensitive and i there was good formatting.
