### ISSUE TITLE
Using Programmatic API, not able to render test_statistics dictionary

### ISSUE THREAD

**Issue by cassidythilton** [uber/ludwig#389]
Greetings.. when I execute the following: `predictions, test_stats = model.test(data_df=df)` via API (following `model.train(data_df=df)` I was expecting a dictionary containing `test_statistics` but am not seeing it. I only am able to render `training_statistics.json`.  

My preference would be to use `model_stats = model.experiment(data_df=df)` but the syntax results in _AttributeError: 'LudwigModel' object has no attribute 'experiment'_.

I am working with a simple binary model and would like to leverage the above dictionary in order to visualize a confusion matrix and horizontal bar plot containing entropy of each class from the confusion matrix. 

```
model_definition = {
    'input_features':[
                {'name':'reporting_start', 'type':'text'},
        {'name':'reporting_end', 'type':'text'},
        {'name':'campaign_id', 'type':'text'},
        {'name':'fb_campaign_id', 'type':'text'},
        {'name':'ad_id', 'type':'text'},
        {'name':'gender', 'type':'category'},
        {'name':'age', 'type':'category'},
        {'name':'interest1', 'type':'numerical'},
        {'name':'interest2', 'type':'numerical'},
        {'name':'interest3', 'type':'numerical'},
        {'name':'impressions', 'type':'numerical'},
        {'name':'clicks', 'type':'numerical'},
        {'name':'spent', 'type':'numerical'},
        {'name':'total_conversion', 'type':'numerical'},
    ],
    'output_features': [
        {'name': 'approved_conversion', 'type': 'binary'}
    ]
}
```

![image](https://user-images.githubusercontent.com/49322823/59971992-a2e86f00-9543-11e9-9930-d1cebab229f7.png)

**Environment (please complete the following information):**
 - OS: Mojave
 - Version 10.14.5
- Python version 3.7.3
- Ludwig version (pip install 6/21)

ADDITIONAL: 

I am able to successfully execute `visualize.learning_curves(training_statistics, field, model_names)` via API. Is it fair to say, once I have test_statistics, I will be able to execute `visualize.confusion_matrix(OPTIONS) `via API as well, considering the current version & capabilities of the product?

**Comment by msaisumanth** [comment]
@cassidythilton  I took a quick look at the code but couldn't find anything off. is the returned test_stats empty?

**Comment by w4nderlust** [comment]
@cassidythilton the `text()` function returns a tuple of `(DataFrame or dict), dict`, the first element is the predictions (you can shoose if they are returned as a dataframe or as a dictionary), while the second are the test statistics you are looking for. I updated the API documentation to reflect it more clearly https://github.com/uber/ludwig/commit/71e2d7fb21fffad131827c42a0e4bb72b5cf21a3. 
Closing this, let me know if this solves your issue.
