### ISSUE TITLE
ludwig CLI: cannot 'train' or 'experiment' 

### ISSUE THREAD

**Issue by rfernand2** [uber/ludwig#39]
Installed ludwig today (pip install ludwig) on Python 3.5.5 on Ubuntu 16.04 and on Python 3.6.8 on Windows 10 (version 1809).   In both environments, ludwig seems to be failing to open the model file and issues the error "AttributeError: 'str' object has no attribute 'get'".  

Here is my cmd line: 
ludwig experiment  --model_definition model_definition.yaml  --data_csv e:\github\LabCoat\Client\data\cars.json

Here is the stack trace:

Traceback (most recent call last):
  File "c:\anaconda3\envs\babyai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\babyai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\anaconda3\envs\babyai\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\experiment.py", line 548, in cli
    experiment(**vars(args))
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\experiment.py", line 161, in experiment
    model_definition = merge_with_defaults(model_definition)
  File "c:\anaconda3\envs\babyai\lib\site-packages\ludwig\utils\defaults.py", line 126, in merge_with_defaults
    model_definition.get('preprocessing', {})
AttributeError: 'str' object has no attribute 'get'

It doesn't seem to be opening the model file (same error with existing or non-existing model file specified).

**Comment by rfernand2** [comment]
Also, just tried building ludwig from source code.  Build completed OK (and created new ludwig.exe), but running 'train' or 'experiment' still gives the same error as above.

**Comment by msaisumanth** [comment]
Could you please paste your model_definition yaml file?

**Comment by rfernand2** [comment]
Sure, here it is:
input_features:
    -
        name: text
        type: text
        encoder: parallel_cnn
        level: word

output_features:
    -
        name: class
        type: category

**Comment by w4nderlust** [comment]
PLease use `--model_definition` for passing a YAML encoded string, while use `--model_definition_file` for the YAML file.

Example:
```
--model_definition "{input_features: [{name: body, type: text}], output_features: [{name: class, type: category}]}"
```
is equivalent to:
```
--model_definition_file def.yaml
```
with `def.yaml`:
```yaml
input_features:
  -
    name: body
    type: text
output_features:
  -
    name: class
    type: category
```

**Comment by msaisumanth** [comment]
@rfernand2 I think the issue is your yaml file's format. You need to tab/space separate the features like shown in the previous comment: 
input_features:
  -
    name: text
    type: text
output_features:
  -
    name: class
    type: category

**Comment by rfernand2** [comment]
@msaisumanth - thanks but I did have spaces (of 2 and 4) as shown in your example.  For some reason, copy/paste stripped them out.  I think the problem was using the wrong cmd line argument as pointed out by @w4nderlust above.

**Comment by w4nderlust** [comment]
Looks like that solved it.

**Comment by rfernand2** [comment]
@w4nderlust - thanks for the correction about the command line argument name.  I can see I am getting further now.  I'll close this issue now.

**Comment by Oli2** [comment]
Hello, 
I have build the traning and test csv files for image classification excercise. The moment I launch:
ludwig train \
  --data_train_csv </Users/tomcheckiewics/Documents/Datasets/catsdogs_dataset_training.csv> \
  --data_test_csv </Users/tomcheckiewics/Documents/Datasets/catsdogs_dataset_test.csv> \
  --model_definition_file model_definition.yaml

I am getting the follwing error:

usage: ludwig train [options]
ludwig train: error: one of the arguments -md/--model_definition -mdf/--model_definition_file is required

it looks like the --model_definition_file model_definition.yaml is not recognized by ludwig train.

Would you be able to point me out into a right direction to resolve this ?

Many thanks
T.

**Comment by w4nderlust** [comment]
Remove < and > from your command.

**Comment by Oli2** [comment]
Thank you very much and enjoy the weekend.
T.
