### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by alexiross** [uber/ludwig#391]
Hi I was trying to complete a **time-series forecast** from a csv file and got stuck with the following error:

> _ValueError: could not convert string to float: '2019-06-23'_

I am using dates in the following format 'yyyy-mm-dd' for the input feature:

**input_features:**

        name: Date
        type: timeseries

How could I fix this issue? Any ideas would be greatly appreciated!

**Comment by w4nderlust** [comment]
@alexiross dates are not timeseries in ludwig. dates are dates, we are adding a datatype for them. Timeseries in ludwig are a list of float numbers. separated by space. Check the examples out ;)

**Comment by rajatjain2310** [comment]
I was doing a text classification project, where I have created the sentence vectors in a different algorithm. Now when I am training the same and giving output feature as mentioned in the example:

name: level1
type: category

The sample output column is here:
0           cancellation
1    query_not_specified
2           cancellation
3           order_status
4    query_not_specified
5           order_status
6           cancellation
7    query_not_specified
8           order_status
9           cancellation

I am getting the error: 
could not convert string to float: 'cancellation'

Please help me out!
