### ISSUE TITLE
"Getting started" issue

### ISSUE THREAD

**Issue by rfernand2** [uber/ludwig#40]
To help CLI users get started with Ludwig, it would be great if you could include an example with an associated downloadable .csv file and a matching model file to train it with.

The current "Getting started" documentation (and the associated examples section) all give a sketch of what the .csv file could look like for a particular scenario, but without a specific file that users can try.  Providing a starting "hello world" pair of .csv /model files help eliminate these as a source of error when users are trying to establish their first successful run with ludwig.

**Comment by msaisumanth** [comment]
Check out the example about [Kaggle's Titanic: Predicting survivors.](https://www.kaggle.com/c/titanic/)

**Comment by rfernand2** [comment]
The kaggle link confused me (since it doesn't mention ludwig anywhere), but then I found the ludwig Titanic example.  OK, nice!  But its buried way down in the examples.  Can you make it so there is an example with a downloadable pair of files at the top of the examples (and preferably also in the "Getting Started") section?  Thanks!

**Comment by w4nderlust** [comment]
It's a good suggestion, will do it, thank you!

**Comment by w4nderlust** [comment]
We added many examples with reference datasets, so i consider this solved.
