### ISSUE TITLE
resize_method: crop_or_pad

### ISSUE THREAD

**Issue by TKassis** [uber/ludwig#400]
**Describe the bug**
If I use 'interpolate' as the resize_method for preprocessing an image all is good, but the 'crop_or_pad' method doesn't seem to be working. I'm not sure what the problem is, but the loss I get for both resnet and stacked_cnn is extremely high. I'm talking int the billions! I see there was a new commit that solved this issue but it doesn't seem to be the case.

**To Reproduce**
Run a classification model using 'crop_or_pad' on Windows 10.

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        preprocessing:
          resize_method: interpolate
          height: 224
          width: 224

output_features:
    -
        name: label
        type: category

training:
    batch_size: 16
    epochs: 25

**Expected behavior**
I expect loss to go down with training similar to the 'interpolate' resize method.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
- Python version: 3.6
- Ludwig version: 0.1.2

**Comment by w4nderlust** [comment]
@TKassis how big are your original images?

**Comment by TKassis** [comment]
> @TKassis how big are your original images?

All sorts of sizes. I'm testing Ludwig on the Kaggle dog & cat dataset. Images (jpg) range from about 50x49 pixels to 1023x768 pixels.

**Comment by msaisumanth** [comment]
@TKassis So I think there's nothing wrong here per se. 
If the input image is of size (288, 383, 3), here's whats happens in the two cases:

1. Interpolate: What this does is to resize the image to the desired size. If you look at the two images, they will have the exact same content. 
2. Crop or Pad: Crop out the center part of size (224, 224, 3). So the cropped image may not have some content that the original image has. 

Example:
original image:
![orig](https://user-images.githubusercontent.com/17418219/60369506-bc0c7800-99a8-11e9-8106-7a48065e85da.jpg)

Crop or pad:
![crop_or_pad](https://user-images.githubusercontent.com/17418219/60369518-c464b300-99a8-11e9-826d-ece593bda8fb.jpg)

Interpolate:
![interpolate](https://user-images.githubusercontent.com/17418219/60369527-c9c1fd80-99a8-11e9-8cc4-6e60cb2fe3a7.jpg)
