### ISSUE TITLE
Preprocessing for numerical and category features

### ISSUE THREAD

**Issue by gogasca** [uber/ludwig#406]
I opened the following question:

https://stackoverflow.com/questions/56847158/ludwig-preprocessing

PS: Created ludwig tag.

**Comment by msaisumanth** [comment]
For the moment, we're only supporting replacing NULL values. So if you want to replace 0s, you'd have to replace 0s with a NULL value. And then use 'fill_with_mode' for categorical features.

Pandas treats missing values as NULLs, so you can delete the 0s for categorical features.

**Comment by w4nderlust** [comment]
Answered in StackOverflow.
