### ISSUE TITLE
Adding tokenization and stop words removal for Chinese Language

### ISSUE THREAD

**Issue by prakass1** [uber/ludwig#408]
**Is your feature request related to a problem? Please describe.**
There is issue already mentioned at:
https://github.com/uber/ludwig/issues/122

**Describe the use case**
A clear and concise description of what the use case for this feature is.

The feature is to add function similar to english_tokenize and english_remove_stopwords() for chinese text.

**Describe the solution you'd like**

I have tried this already by adding couple of functions as below  

string_utils.py
`def chinese_tokenize(text):
    return process_text(text, load_nlp_pipeline('zh'))`

`def chinese_tokenize_remove_stopwords(text):
    return process_text(text, load_nlp_pipeline('zh'),
                        filter_stopwords=True)`

And have added the functions into format_registry.

In nlp_utils.py:

from spacy.lang.zh import Chinese
nlp_pipelines = {
    'en': None,
    'it': None,
    'es': None,
    'de': None,
    'fr': None,
    'pt': None,
    'nl': None,
    'el': None,
    'zh': None, # This is added
    'xx': None
}
language_module_registry = {
    'en': 'en_core_web_sm',
    'it': 'it_core_news_sm',
    'es': 'es_core_news_sm',
    'de': 'de_core_news_sm',
    'fr': 'fr_core_news_sm',
    'pt': 'pt_core_news_sm',
    'nl': 'nl_core_news_sm',
    'el': 'el_core_news_sm',
    'zh': 'zh_core', # This is a dummy name that i have choosen and is checked below
    'xx': 'xx_ent_wiki_sm'
}
default_characters = [' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
                      'k', 'l', 'm', 'n', 'o', 'p',
                      'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0',
                      '1', '2', '3', '4', '5', '6',
                      '8', '9', '-', ',', ';', '.', '!', '?', ':', '\'', '\'',
                      '/', '\\', '|', '_', '@', '#',
                      '$', '%', '^', '&', '*', '~', '`', '+', '-', '=', '<',
                      '>', '(', ')', '[', ']', '{',
                      '}']
punctuation = {'.', ',', '@', '$', '%', '/', ':', ';', '+', '='}

def load_nlp_pipeline(language='xx'):
    if language not in language_module_registry:
        logging.error(
            'Language {} is not supported.'
            'Suported languages are: {}'.format(
                language,
                language_module_registry.keys()
            ))
        raise ValueError
    else:
        spacy_module_name = language_module_registry[language]
    global nlp_pipelines
    if nlp_pipelines[language] is None:
        logging.info('Loading NLP pipeline')
        import spacy
        try:
            # For Chinese
            if spacy_module_name is 'zh_core':
                nlp_pipelines[language] = Chinese() # Adding Chinese class for tokenizing ...
            else:
                nlp_pipelines[language] = spacy.load(
                    spacy_module_name,
                    disable=['parser', 'tagger', 'ner']
            )
        except OSError:
            logging.error(
                ' Unable to load spacy model {}. '
                'Make sure to download it with: '
                'python -m spacy download {}'.format(
                    spacy_module_name,
                    spacy_module_name
                ))
            sys.exit(-1)
    return nlp_pipelines[language]

Some output of the test is:

print(process_text('客户说，当钥匙关闭时，它会变硬并且气缸需要强制关闭。',
                   load_nlp_pipeline(language='zh')))
['客户说，当钥匙关闭时，它会变硬并且气缸需要强制关闭', `'。']

print(process_text('客户说，当钥匙关闭时，它会变硬并且气缸需要强制关闭。',`
                   load_nlp_pipeline(language='zh'), filter_stopwords=True))
['客户说，当钥匙关闭时，它会变硬并且气缸需要强制关闭']

Providing word_format as word_format: chinese_tokenize in yaml works.

If it is suitable, I think it can be added.

**Comment by w4nderlust** [comment]
At the moment spacy does not officially support Chinese: https://spacy.io/models
There are models available from third parties: https://github.com/howl-anderson/Chinese_models_for_SpaCy
but as they are not fficial, I would actually rather for those models to be included in the official list before integrating them into Ludwig.
You are free to download them and use them in the meantime.

**Comment by prakass1** [comment]
@w4nderlust Thank you for the answer. I have already looked it up but the model built was on version 2.0.X . There is an issue on the same https://github.com/howl-anderson/Chinese_models_for_SpaCy/issues/16

One way would that I rebuild it from scratch or pass the dataset to train on already created tokens i suppose.

**Comment by w4nderlust** [comment]
That will likely work. Also, you can try using spacy 2.0 instead of spacy 2.1. You will not have some of the other tokenizers, but you could use these chinese models.

**Comment by w4nderlust** [comment]
SpaCy added Chinese as language in release 2.3, this commit adds new Chinese preprocessing to Ludwig, so this issue should be considered solved.
