### ISSUE TITLE
Loading GloVe embeddings defaults to OS char encoding (win=CP1252)

### ISSUE THREAD

**Issue by willaaam** [uber/ludwig#415]
**Describe the bug**
Probably considered an edge case, but I was forced to work on windows today. Loading GloVe embeddings failed because it defaults loading the GloVe embeddings to the OS character encoding, which is CP1252 for windows.

This leads to an error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6148: character maps to <undefined>

**To Reproduce**
Be in windows:
Load GloVe embeddings

**Expected behavior**
Easy resolution would be to force utf8 as this is the standard for downloadable GloVe embeddings in data_utils.py(174):

```
def load_glove(file_path):
    logging.info('  Loading Glove format file {}'.format(file_path))
    embeddings = {}
    with open(file_path, 'r', encoding="utf8") as f:
        for line in f:
            if line:
                split = line.split()
                word = split[0]
                embedding = np.array([float(val) for val in split[1:]])
                embeddings[word] = embedding
    logging.info('  {0} embeddings loaded'.format(len(embeddings)))
    return embeddings
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Version 10
- Python 3.6.6
- Ludwig version 0.1.2

**Additional context**
//

**Comment by w4nderlust** [comment]
Hi @willaaam , thanks for sending this. It is actually a copy of this I believe: https://github.com/uber/ludwig/issues/336
The code on master already solves it, please use it instead of the current release and you should be good to go. Let me know if you still have problems. Closing this in the meantime.
