### ISSUE TITLE
AttributeError Ludwig 

### ISSUE THREAD

**Issue by abc1110** [uber/ludwig#416]
@w4nderlust  I am facing the following attribute error while trying to import Ludwig in Spyder. 

```
from ludwig.api import LudwigModel
Traceback (most recent call last):

  File "<ipython-input-22-8dc99788c173>", line 3, in <module>
    from ludwig.api import LudwigModel

  File "C:\Users\Dell\Anaconda3\lib\site-packages\ludwig\api.py", line 36, in <module>
    ludwig.contrib.contrib_import()

AttributeError: module 'ludwig' has no attribute 'contrib'
```
I even uninstalled and reinstalled from master using  ``` pip install git+http://github.com/uber/ludwig.git ``` but it has not helped.

**Comment by w4nderlust** [comment]
I never used Anaconda nor Spyder.
Will look into it, but I strongly suggest you to create a virtual
environment and install it there as suggested in the documentation.

On Mon, 8 Jul 2019 at 04:37, abc1110 <notifications@github.com> wrote:

> @w4nderlust
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w4nderlust&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oIrdNXB7cswECuiZcZaPU2KGnDIqWHfrrxkhkIBGXn4&s=hydSdrUc-CAT2MJAKP8NO5ALL0tNyDZqaXa2T8DsVP8&e=>
> I am facing the following attribute error while trying to import Ludwig in
> Spyder.
>
> from ludwig.api import LudwigModel
> Traceback (most recent call last):
>
>   File "<ipython-input-22-8dc99788c173>", line 3, in <module>
>     from ludwig.api import LudwigModel
>
>   File "C:\Users\Dell\Anaconda3\lib\site-packages\ludwig\api.py", line 36, in <module>
>     ludwig.contrib.contrib_import()
>
> AttributeError: module 'ludwig' has no attribute 'contrib'
>
> I even uninstalled and reinstalled from master using pip install git+
> http://github.com/uber/ludwig.git but it has not helped.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_416-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISGAUCDUF4Z22R7JZMTP6MRJHA5CNFSM4H62XZPKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G52PZEQ&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oIrdNXB7cswECuiZcZaPU2KGnDIqWHfrrxkhkIBGXn4&s=ar405EPk_lhrfOZX_4jk-gRFpzCRK7DYiemNtr3uIQ0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISETSKDD55NTITABRS3P6MRJHANCNFSM4H62XZPA&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=oIrdNXB7cswECuiZcZaPU2KGnDIqWHfrrxkhkIBGXn4&s=5yMDdTUn-TECRvL6PqqBtYzs_lyNWYRA0407fpCmnVk&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs

**Comment by w4nderlust** [comment]
In my environment importing Ludwig in Spyder works fine. I believe it is a problem with your installation between Anaconda and Spyder and the virtual environment, not a Ludwig problem.
![image](https://user-images.githubusercontent.com/349256/60837067-1ca36e00-a17c-11e9-89fe-d89fa448152b.png)
Closing this. Feel free to keep posting and we can try to help you out. Also please post if you find a solution for your specific case.
