### ISSUE TITLE
Example Docs show wrong CLI argument for specifying model file

### ISSUE THREAD

**Issue by rfernand2** [uber/ludwig#42]
The [doc page here ](https://uber.github.io/ludwig/examples/) shows the command line argument to use for specifying a model definition file as "--model_definition", but I just learned that it should be "--model_definition_file".  Please update ASAP as new users are likely to get tripped up by this (as I did).  Thanks!

**Comment by w4nderlust** [comment]
Thank you for spotting this! I solved it.
