### ISSUE TITLE
Upgrade to Tensorflow 1.14.0

### ISSUE THREAD

**Issue by loretoparisi** [uber/ludwig#429]
Ciao Piero!
Since we moved to TF 1.14.0 backend, I can see this error message:

```
ERROR: ludwig 0.1.2 has requirement tensorflow==1.13.1, but you'll have tensorflow 1.14.0 which is incompatible.
```

I think it should be slightly easy to upgrade to TF 1.14 for ludwing.

Thank you!

**Comment by w4nderlust** [comment]
Yes there shouldn't be any breaking change as far as i know. Will try run the tests in a tf 1.14 virtual environment and if it runs fine change the dependency.

**Comment by w4nderlust** [comment]
Done, you can do `pip install git+http://github.com/uber/ludwig.git` ;)

**Comment by loretoparisi** [comment]
@w4nderlust amazing, thank you!
