### ISSUE TITLE
Docker set-up failure

### ISSUE THREAD

**Issue by nikhilraog** [uber/ludwig#431]
I'm trying to set-up container with ludwig using the ```https://github.com/uber/ludwig/blob/master/Dockerfile``` and my docker-compose file looks like this 

```
version: '3'
services:
  web:
    container_name: web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  ludwig: 
    build: 
      context: ludwig/
  redis:
    image: "redis:alpine"
```

I get the below errors while building 
```
.
.
.
.
Failed to build gmpy
ERROR: fastapi 0.33.0 has requirement pydantic<=0.30.0,>=0.30, but you'll have pydantic 0.30.1 which is incompatible.
Installing collected packages: Cython, python-dateutil, cycler, kiwisolver, pyparsing, matplotlib, pytz, pandas, scipy, cloudpickle, toolz, dask, pillow, PyWavelets, decorator, networkx, scikit-image, joblib, scikit-learn, seaborn, cymem, srsly, murmurhash, preshed, blis, plac, wasabi, urllib3, certifi, chardet, requests, tqdm, thinc, spacy, tabulate, tensorboard, mock, tensorflow-estimator, tensorflow, PyYAML, attrs, atomicwrites, more-itertools, zipp, importlib-metadata, pluggy, wcwidth, py, packaging, pytest, gmpy, starlette, dataclasses, pydantic, fastapi, click, h11, websockets, httptools, uvloop, uvicorn, python-multipart
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0
  Running setup.py install for gmpy: started
    Running setup.py install for gmpy: finished with status 'error'
    ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-d6v9cv4z/gmpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sv9t3yco/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'gmpy' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./src -I/usr/include/python3.6m -c src/gmpy.c -o build/temp.linux-x86_64-3.6/src/gmpy.o
    In file included from src/gmpy.c:251:0:
    src/gmpy.h:30:10: fatal error: gmp.h: No such file or directory
     #include "gmp.h"
              ^~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-d6v9cv4z/gmpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sv9t3yco/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-d6v9cv4z/gmpy/
ERROR: Service 'ludwig' failed to build: The command '/bin/sh -c git clone --depth=1 https://github.com/uber/ludwig.git     && cd ludwig/     && pip install -r requirements.txt     && python -m spacy download en     && python setup.py install' returned a non-zero code: 1
~/docker-related$ 

```

Appreciate if anyone can let me know if I'm missing something. Thanks!

**Comment by w4nderlust** [comment]
Installing `libgmp3-dev` as suggested [here](https://stackoverflow.com/questions/7351205/where-to-find-gmp-h) should fix the problem.

**Comment by w4nderlust** [comment]
The PR should have fixed it, let me know if it is still an issue.

**Comment by nikhilraog** [comment]
Thanks @w4nderlust, will give a try. Alternately, I changed my Python Base version (Python-3.7, instead of Python-3.7-alpine) and worked like charm.

**Comment by simonefrancia** [comment]
Sorry @w4nderlust, why this lib `libgmp3-dev` is need for ludwig?
Also we had recently some problems in building docker image and we solved installing this lib, but it wasn't before.
Thanks

**Comment by w4nderlust** [comment]
It has already been removed in master.

On Mon, 29 Jul 2019 at 10:57, Simone Francia <notifications@github.com>
wrote:

> Sorry @w4nderlust
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w4nderlust&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=TmykKKBe2ucFtTg-9SyWc8HwYRKeUVPeFX1Ck0lkbbk&s=5iYGAyg1DnieP2re1PUd6UxsveCaVvWTUgyLsySzBNQ&e=>,
> why this lib libgmp3-dev is need for ludwig?
> Also we had recently some problems in building docker image and we solved
> installing this lib, but it wasn't before.
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_431-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISCWCB3QLTBIHMJD33TQB2WHXA5CNFSM4IDZ24K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3AB47I-23issuecomment-2D515907197&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=TmykKKBe2ucFtTg-9SyWc8HwYRKeUVPeFX1Ck0lkbbk&s=YMwvuv2T0bDpeYYe4H3l1VkeeVswFuGyj27ZP1Bjq7Y&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISCUPOKFY7H2NNKIWCDQB2WHXANCNFSM4IDZ24KQ&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=TmykKKBe2ucFtTg-9SyWc8HwYRKeUVPeFX1Ck0lkbbk&s=91LBCiajd6-3HjHdnaQE0hfxSscRnaOH4_TGXBU4SBc&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs
