### ISSUE TITLE
Error with pydantic and gmpy

### ISSUE THREAD

**Issue by zapaishchykova** [uber/ludwig#432]
**Describe the bug**
I was performing an installation from source today on two different machines with Ubuntu 18.04 with changed tensorflow cpu -> tensorfrow-gpu (in requirements.txt) and had multiple errors that requirements.txt colud not be installed due to the pydantic version and then due to the gmpy wheels not fould.

**To Reproduce**
```
git clone git@github.com:uber/ludwig.git
cd ludwig
virtualenv -p python3 venv
source venv/bin/activate

```
then change in requirements.txt line with tensorflow to:
tensorflow-gpu==1.14.0
```
pip install -r requirements.txt
python setup.py install
```

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
Change requirements.txt

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.04
- Python 3

**SOLUTION**
So, i find out this solution, maybe it helps someone:
```
 pip3 uninstall pydantic
pip3 install pydantic==0.30.0
sudo apt install libgmp-dev libmpfr-dev libmpc-dev
pip3 install gmpy
pip install -r requirements.txt
```

**Comment by w4nderlust** [comment]
Thank you for noticing this and providing a solution. I included both the pydantic version in requirements and the libgmp in Getting Started and FAQ.
