### ISSUE TITLE
Vizualize error

### ISSUE THREAD

**Issue by zapaishchykova** [uber/ludwig#433]
**Describe the bug**
`ludwig visualize --visualization learning_curves --training_statistics training_statistics.json` UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

**To Reproduce**
`ludwig visualize --visualization learning_curves --training_statistics training_statistics.json` 

**Expected behavior**
Plot to be plotted

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
- Python 3

**Comment by zapaishchykova** [comment]
Nevermind, found solution here:
https://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/
```
sudo apt-get install tcl-dev tk-dev python-tk python3-tk
pip uninstall matplotlib
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
python setup.py install
```

**Comment by w4nderlust** [comment]
If you install from master now there's also an option to save images directly
