### ISSUE TITLE
Saving a model incorrectly adds output feature to list of input features

### ISSUE THREAD

**Issue by thomasmarkus** [uber/ludwig#435]
I'm using the Titanic example with ludwig master (18817003e418e991297a36a0e5909039555c6832) and can also reproduce the issue with version `0.1.2`

`LudwigModel.save()` persists the model in a way that causes the output feature (`Survived`) of the Titanic example in the documentation to be part of the input features. This doesn't seem to affect training, but when loading the model from disk using `LudwigModel.load()` it will fail during `LudwigModel.predict()`, because of a mismatch between the tensor sizes. `tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [17,1] rhs shape= [16,1]`

Manually removing `Survived` from the persisted model's `model_hyperparameters.json` fixes the issue.

**Comment by thomasmarkus** [comment]
Related to https://github.com/uber/ludwig/issues/372 , but that fix seems to only apply to the CLI interface, not the programmatic api.

**Comment by w4nderlust** [comment]
Please use the code from master, now there are two separate functions, predict and test, test requires the output features, predict does not. Let me know if it solves your issue.

**Comment by thomasmarkus** [comment]
Thanks. I am using master (see first line of my message).
I do need to add though that my method flow is like this: `train()`, `test()`, `save()`, `load()`, `predict()`. Maybe the call to `test()`, to gather model performance stats, causes the issue?

**Comment by w4nderlust** [comment]
It's unlikely.
Can you please provide a fully reproducible example so that I can debug?
Either yaml + command + data or python script + data work fine. If you can't share the data or the data is too big, a small subsample where the issue happens is fine too, otherwise you can use the script in `data/dataset_synthesyzer.py` to create a synthetic dataset to reproduce your issue.

**Comment by w4nderlust** [comment]
I actually believe I discovered and solved a bug related to this with the last commit.
Please try the code from master and let me know if you still have the problem, in which case I'll reopen the issue.
