### ISSUE TITLE
pytorch support?

### ISSUE THREAD

**Issue by ekshaks** [uber/ludwig#44]
Great project!

Given the stress on modular design, I'm wondering how hard it is to "swap-in" the pytorch library and the models. 
- Is the library tied deeply to tensorflow?
- Is pytorch support planned in the roadmap?

**Comment by w4nderlust** [comment]
thank you @ekshaks for your appreciation. Being this more a discussion than an issue, can you please open it here in the gitq forum? https://gitq.com/uber/ludwig This will be the first discussion there! :) I'm closing this one.
