### ISSUE TITLE
Ludwig not producing hyperparameters.json file in results folder 

### ISSUE THREAD

**Issue by Sm00g15** [uber/ludwig#440]
**Describe the bug**
Ludwig Kills itself on training and doesn't produce hyperparameters file in results folder to use for predictions

<img width="568" alt="Screen Shot 2019-07-20 at 4 38 48 PM" src="https://user-images.githubusercontent.com/14209806/61574061-24b0c580-ab0d-11e9-9d79-845b5be15287.png">

**To Reproduce**
1. cd into ludwig folder
2. run train command with ```ludwig train --data_csv path/to/file.csv --model_definition "{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}"```
3. inevitably you'll see a returned command similar to the one in the picture above
4. if you check your results/experiment_run_#/model folder there will be no hyperparameters.json file present

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

yaml definiton: 
```input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn

output_features:
    -
        name: title
        type: text
        level: word
        decoder: generator
        cell_type: lstm

output_features: 
    -
        name: author
        type: text
        level: word
        decoder: generator
        cell_type: lstm

output_features: 
    -
        name: subtitle
        type: text
        level: word
        decoder: generator
        cell_type: lstm
```

data sample: 

```image_path,,,,,,
./images/snow.jpeg,,,,,,
```

![UNADJUSTEDNONRAW_thumb_2d1](https://user-images.githubusercontent.com/14209806/61574261-21b7d400-ab11-11e9-9111-edcd37a6c524.jpg)

**Expected behavior**
Expected the model to train and hyperparameters.json file to be generated 

**Screenshots**
<img width="568" alt="Screen Shot 2019-07-20 at 4 38 48 PM" src="https://user-images.githubusercontent.com/14209806/61574264-31cfb380-ab11-11e9-8273-12f11bd7c65d.png">

-- no hyperparameters.json file produced either
<img width="565" alt="Screen Shot 2019-07-20 at 5 10 34 PM" src="https://user-images.githubusercontent.com/14209806/61574272-4f9d1880-ab11-11e9-96d6-12d0faaaa76d.png">

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Mojave 
- Python version 3 
- Ludwig version (most up to date version using ludwig install)

**Additional context**

**Comment by w4nderlust** [comment]
I believe there are several issues at play here.
The first and most obvious it the yaml file: output features is a list, bu you are actually defining it several times with only one element. Moreover, I cant see any input feature definition in your YAML.
Please use some that looks like this:
```
input_features:
  -
    <my input feature 1>
  -
    <my input feature 2>
output_features:
  -
    <my output feature 1>
  -
    <my output feature 2>
```
Also, use the latest version for master to be sure you are not encountering a problem that has already been solved.

**Comment by Sm00g15** [comment]
👍 thank you for the help @w4nderlust, I’ll give those ideas a shot.

**Comment by w4nderlust** [comment]
Closing in the meantime, let me know if you are still experiencing the issue, in that case I'll reopen.
