### ISSUE TITLE
The weather data example python script fails to run

### ISSUE THREAD

**Issue by aspenforest** [uber/ludwig#441]
It fails to run, because Ludwigs latest published release does not have the  
"add_sequence_feature_column" function in data_utils.py, and when I did   
manually copy-paste it into the respective file, the example script ran, but hang indefinitely.   
To fix this issue, I would suggest to put out a new updated release onto PyPI.

**Comment by w4nderlust** [comment]
A new version will be published soon, in the mean time you can install from master.
Thank you
