### ISSUE TITLE
Feature request: output probabilities

### ISSUE THREAD

**Issue by sudodoki** [uber/ludwig#45]
This is either because I couldn't 👀 instructions in documentation or something missing from current functionality: is there a way to have something like `.predict_proba` set of methods that would not only output target label(s) but also confidence/probability model assigns to it?

**Comment by w4nderlust** [comment]
It depends on how you are predicting. If you are using the `ludwig predict` command, there will be files containing the probabilities in the results directory. If you are using the API call `LudwigModel.predict()` you'll either get probabilities as additional columns in your pandas dataframe of if you choose to return a dictionary you'll get something like `return_dict[feature_name]['probabilties']`. I should probably add these details in the api call examples.

**Comment by sudodoki** [comment]
Thanks for taking your time to educate me. Great tool!
