### ISSUE TITLE
gmpy prerequisite is broken on windows systems

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#452]
On windows systems, `pip install gmpy` is broken, alas it needs a lot of prerequisites to be built correctly (first error message you get, is that the wheel cannot be built due to missing gmp.h, for anyone else out there trying to search for this issue, and on windows we don't have libgmp3-dev to install).
Now a "simple" `pip install ludwig` now fails due to missing header files and more.

I know you are not explicitly supporting Windows installs, but up to the H3 feature support (when gmpy was added) the package was able to be built\deployed.
I suppose it could be possible to `pip install ludwig` up to the point where all other packages are correctly installed and then do a final `pip install ludwig --no-deps`, and then manually commenting all H3 references in `ludwig\features\feature_registries.py` but it's a really broken way to workaround over this.
(in my case, with an added `pip uninstall tensorflow` and `pip install tensorflow-gpu` to leverage GPU processing)

Preliminary tests show that this "half-and-half" workaround with --no-deps is running fine with train\test\predict\visualize operations (of course not including anything relative to H3). I am also seeing that 0.1.2 models cannot be used with 0.2 due to `Not found: Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
         [[{{node save/RestoreV2}}]]`
I am looking into this to find if it's related to H3 commenting or if it deserves a separate bug report (even just to give a readable message stating the non retrocompatibility of 0.2 towards 0.1.2)

Thanks!

**Comment by w4nderlust** [comment]
I'm looking to an alternative to gmpy at the moment. Will keep you posted.

**Comment by carlogrisetti** [comment]
FYI, gmpy2 2.0.8 has available pre-built wheels for recent python versions (not on pypy, and I don't understand why they don't mirror them over there).
https://www.lfd.uci.edu/~gohlke/pythonlibs/#gmpy
I could see that as a "clean" workaround for windows users (like: manually install gmpy2 by doing `pip install gmpy2-2.0.8-cp36-cp36m-win_amd64.whl` with the correct cpXX version depending on python environment and win32\amd64 architecture).

I don't know if that could be enough, but I suppose that migrating from gmpy to gmpy2 should be fairly straightforward (I haven't seen anything about that, nor I know\understand the purpose of this module, but I hope they have a similar shape\size :))
gmpy2 at least is actively mantained, and 2.1.0 beta came out in May, so we could hope for an extended support timeframe.

**Comment by w4nderlust** [comment]
Unfortunately it is not straightforward as the functions I'm using are not available anymore in gmpy2. But don't worry the solution that I have working is a simple pure python alternative, will land in a couple days at most.

**Comment by c14kevincardenas** [comment]
Thank you for your updates! Unfortunately, it still appears that gmpy is in the requirements list or somewhere in the ludwig install. On windows 10, pip install ludwig outputs all the requirements already satisfied and this:
Collecting gmpy (from ludwig)
  Using cached https://files.pythonhosted.org/packages/26/37/2184c13cee81e1dbeaebbb13570195247e73ab2138a3db0c9d2c5347e372/gmpy-1.17.zip

**Comment by w4nderlust** [comment]
Install from master.
