### ISSUE TITLE
Unable to export SavedModel: AttributeError: 'Model' object has no attribute 'model'

### ISSUE THREAD

**Issue by hamletbatista** [uber/ludwig#461]
**Describe the bug**
After successfully training, loading and initializing a model, I'm unable to save it for serving.

**To Reproduce**
1. Go to 'colab.google.com'
2. Click on '+ Code'
3. Scroll down to 'New code cell.'
4. Type
from ludwig.api import LudwigModel
ludwig_model = LudwigModel.load("/content/results/experiment_run_0/model")
ludwig_model.initialize_model(train_set_metadata_json="results/experiment_run_0/model/train_set_metadata.json")
ludwig_model.save_for_serving("for_serving")

AttributeError                            Traceback (most recent call last)
<ipython-input-29-2822eb1daa29> in <module>()
----> 1 ludwig_model.save_for_serving("for_serving")

1 frames
/usr/local/lib/python3.6/dist-packages/ludwig/models/model.py in save_savedmodel(self, save_path)
   1363             },
   1364             strip_default_attrs=True,
-> 1365             saver=self.model.saver,
   1366         )
   1367         builder.save()

AttributeError: 'Model' object has no attribute 'model'

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.

input_features:
    -
        name: Questions
        type: text
        encoder: bert
        config_path: uncased_L-12_H-768_A-12/bert_config.json
        checkpoint_path: uncased_L-12_H-768_A-12/bert_model.ckpt
        preprocessing:
          word_tokenizer: bert
          word_vocab_file: uncased_L-12_H-768_A-12/vocab.txt
          padding_symbol: '[PAD]'
          unknown_symbol: '[UNK]'

output_features:
    -
        name: Category0
        type: category
    -
        name: Category2
        type: category
text:
        word_sequence_length_limit: 128
training:
        batch_size: 32
        learning_rate: 0.00002

Dataset: https://www.kaggle.com/ananthu017/question-classification

Issues that are not reproducible will be ignored.

**Expected behavior**

I expect the exported SavedModel so I can use it to serving.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Jupyter (Colab)
 - Version: Kernel Python 3
- Python version: 3.6.8
- Ludwig version: 0.2

**Additional context**

**Comment by hamletbatista** [comment]
I was able to export the model by using the script shared in this comment https://github.com/uber/ludwig/issues/329#issuecomment-508777581

import collections
#import shutil
import logging

#import mlflow
#import mlflow.tensorflow

import tensorflow as tf
from tensorflow.python.saved_model import builder as saved_model_builder

from ludwig.api import LudwigModel

logging.basicConfig(level=logging.INFO)

_logger = logging.getLogger("BERT")#__name__)

#https://www.mlflow.org/docs/latest/tracking.html
#tracking_uri = 'file:/content'#os.environ.get('MLFLOW_TRACKING_URI')
#mlflow.set_tracking_uri(tracking_uri)

#preprocessed_data_url = str(sys.argv[1])
#model_definition_url = str(sys.argv[2])
#save_path = 'model'

#ludwig_model = LudwigModel(
#    model_definition=None,
#    model_definition_file=model_definition_url,
#)

#_logger.info('Training...')
#ludwig_model.train(data_csv=preprocessed_data_url)

def get_tensors(model_definition, model):
    # https://github.com/uber/ludwig/blob/master/ludwig/api.py#L524
    input_tensors = {}
    for input_feature in model_definition['input_features']:
        input_tensors[input_feature['name']] = getattr(model, input_feature['name'])

    output_tensors = {}
    for output_feature in model_definition['output_features']:
        output_tensors[output_feature['name']] = getattr(model, output_feature['name'])

    return input_tensors, output_tensors

input_tensors, output_tensors = get_tensors(
    ludwig_model.model_definition,
    ludwig_model.model,
)

#current_dir = s.path.dirname(os.path.abspath(__file__))
saved_model_path = "for_serving" #os.path.join(current_dir, 'saved_model')
#shutil.rmtree(saved_model_path, ignore_errors=True)

builder = saved_model_builder.SavedModelBuilder(saved_model_path)

with ludwig_model.model.session as sess:
    builder.add_meta_graph_and_variables(
        sess,
        [tf.saved_model.tag_constants.SERVING],
        signature_def_map={
            'predict': tf.saved_model.predict_signature_def(input_tensors, output_tensors)
        },
        strip_default_attrs=True,
        saver=ludwig_model.model.saver,
    )

builder.save()

#shutil.rmtree(save_path, ignore_errors=True)

_logger.info('Saving SavedModel...')

#mlflow.tensorflow.save_model(
#    tf_saved_model_dir=saved_model_path,
#    tf_meta_graph_tags=[tf.saved_model.tag_constants.SERVING],
#    tf_signature_def_key='predict',
#    path=save_path
#)

#_logger.info('Saving artifacts...')

#mlflow.log_artifacts(save_path)

#_logger.info('Artifacts saved!')

> INFO:tensorflow:No assets to save.
>INFO:tensorflow:No assets to write.
>INFO:tensorflow:SavedModel written to: for_serving/saved_model.pb
>INFO:BERT:Saving SavedModel...

**Comment by w4nderlust** [comment]
This PR solves it: https://github.com/uber/ludwig/pull/456
