### ISSUE TITLE
Fail to build the Dockerfile in this repository

### ISSUE THREAD

**Issue by tqa236** [uber/ludwig#463]
**Describe the bug**
I cannot build an image with the Dockerfile in this repository

**To Reproduce**
1. Use the Dockerfile in master

```
FROM tensorflow/tensorflow:latest-py3

RUN apt-get install -y --no-install-recommends \
        git libgmp3-dev
RUN git clone --depth=1 https://github.com/uber/ludwig.git \
    && cd ludwig/ \
    && pip install -r requirements.txt \
    && python -m spacy download en \
    && python setup.py install

WORKDIR /data

ENTRYPOINT ["ludwig"]
```

2. Run the command to build images: `docker build .`
3. See error: 

```
docker : The command '/bin/sh -c git clone --depth=1 https://github.com/uber/ludwig.git     && cd ludwig/     && pip 
install -r requirements.txt' returned a non-zero code: 137
At line:1 char:1
+ docker build .
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command '/b...-zero code: 137:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Expected behavior**
Built without errors.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
- Python: as in Dockerfile
- Ludwig version: as in Dockerfile

**Additional context**
If I comment out the `RUN git clone...` command, there's no error, so I think the problem is in that command.

**Comment by msaisumanth** [comment]
It looks like a memory issue. Take a look [here](https://stackoverflow.com/questions/44907444/error-137-on-docker-build-command-on-win7)

**Comment by tqa236** [comment]
Thank you very much. It works smoothly. I'm sorry that this question doesn't relate to Ludwig.
