### ISSUE TITLE
not able to install ludwig 0.2 on my new system and getting the bellow error when running my old ludwig 0.1 code

### ISSUE THREAD

**Issue by saaeds** [uber/ludwig#470]

**Comment by saaeds** [comment]
> Trying to install ludwig 0.2 on my new workstation, having multiple issues with installation, I have unsuccessfully try it with anaconda and native pip out of conda env, but at this stage I the issue I am facing has to do when running my ludwig 0.1.0 script.

Traceback (most recent call last):
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Vira\multiModel.py", line 60, in <module>
    model_name = ticker, gpus = 0)
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\site-packages\ludwig\api.py", line 417, in train
    random_seed=random_seed)
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\site-packages\ludwig\utils\misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Vira\Anaconda3\envs\viragpu\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I have also try with one of my other workstations under ubuntu and the same issue.

My old script is still running on ludwig 0.1.0 but can't seem to find a way to install it again on my new workstation.

**Comment by msaisumanth** [comment]
What was the error with pip? There was some issue with 0.2 on Windows. Try installing from the source code.

**Comment by saaeds** [comment]
Thanks for the reply msaisumanth, I finally after struggling for a few days it is back online. Very scary!!!!. at the end I started a fresh install of python and ludwig.

**Comment by w4nderlust** [comment]
Not sure, did you solve the issue? What was it? How did you do that?

**Comment by saaeds** [comment]
Thanks w4nderlust, I will try to reproduce the event within the next couple of days and will inform you, but to resolve the challenge what I did was to start a new python installation from fresh and ludwig from the master. A few warnings pop up (the ones for the compat.v1) that I was fixing before and now I am not, perhaps that is part of the issue.

**Comment by w4nderlust** [comment]
You don’t need to fix the warnings.

On Sun, 4 Aug 2019 at 02:30, saaeds <notifications@github.com> wrote:

> Thanks w4nderlust, I will try to reproduce the event within the next
> couple of days and will inform you, but to resolve the challenge what I did
> was to start a new python installation from fresh and ludwig from the
> master. A few warnings pop up (the ones for the compat.v1) that I was
> fixing before and now I am not, perhaps that is part of the issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_470-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISCIG4T7BGSGICZ2N5LQCYPLXA5CNFSM4IIFQJ5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PYC2Y-23issuecomment-2D517964139&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=SOju341QK3YDa_YCCRI-V-fit0ZaG2G5Jn_esEzM4X4&s=Ft0YJbyWg4IlihVEROSWv5sOPCmmO_qFQMUN4ob6DGA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISE56AXZAETKHDDBWQ3QCYPLXANCNFSM4IIFQJ5A&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=SOju341QK3YDa_YCCRI-V-fit0ZaG2G5Jn_esEzM4X4&s=EfTjUSAEYaGjA3TCgHh8qtP6I4NaLZwEgbWY_uH4Mwo&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs
