### ISSUE TITLE
Need to understand the confusion matrix returned in the prediction json file

### ISSUE THREAD

**Issue by rhlr** [uber/ludwig#472]
I ran a simple image classification problem on a small dataset. Total number of classes were 5. I got the following  `confusion matrix` in the prediction_statistics.json file. Can anyone help me understand this:

`"confusion_matrix": [
            [   
                0,
                0,
                0,
                0,
                0,
                0
            ],
            [   
                0,
                0,
                0,
                0,
                0,
                0
            ],
            [   
                0,
                8,
                5,
                5,
                5,
                7
            ],
            [   
                0,
                1,
                0,
                1,
                1,
                0
            ],
            [
                0,
                4,
                3,
                5,
                5,
                3
            ],
            [
                0,
                0,
                0,
                0,
                0,
                0
            ]
        ]
`

**Comment by w4nderlust** [comment]
I suggest you to use the build in confusion matrix misualization.
The first class is unk and the others are sorted by frequency, if you look inside the training set metadata you'll find the vocabulary of your output feature. The visualization resolves it automatically.
