### ISSUE TITLE
ERROR: Failed building wheel for gmpy (installation ludwig)

### ISSUE THREAD

**Issue by bedna-KU** [uber/ludwig#474]
Installation ludwig to venv

```
  ERROR: Command errored out with exit status 1:
   command: /home/nimiq/Dev/Python/Ludwig/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7wnoaj0k/gmpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7wnoaj0k/gmpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v_ojnkwm --python-tag cp37
       cwd: /tmp/pip-install-7wnoaj0k/gmpy/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'gmpy' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./src -I/usr/include/python3.7m -I/home/nimiq/Dev/Python/Ludwig/env/include/python3.7m -c src/gmpy.c -o build/temp.linux-x86_64-3.7/src/gmpy.o
  In file included from src/gmpy.c:251:
  src/gmpy.h:30:10: fatal error: gmp.h: No such file or directory
   #include "gmp.h"
            ^~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for gmpy
```

**Environment**
(env) nimiq@mkmnmskpctest:~/Dev/Python/Ludwig$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

Python 3.7.3

pip -V
pip 19.2.1 from /home/nimiq/Dev/Python/Ludwig/env/lib/python3.7/site-packages/pip (python 3.7)

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)

**Comment by carlogrisetti** [comment]
This has already been addressed with #452 
Just install from master code repo. gmpy prerequisite has been removed
