### ISSUE TITLE
Incorrect documentation: default teacher forcing behavior on sequence decoder "generator"

### ISSUE THREAD

**Issue by lethaiq** [uber/ludwig#479]
**Is your feature request related to a problem? Please describe.**
Clarification on the use of "teacher forcing" by default of sequence decoder "generator" on documentation

**Describe the use case**
The TrainingHelper uses "teacher forcing" by default (https://github.com/uber/ludwig/blob/ee4d5daf07fda2168c4e89dd962b151506d17f9a/ludwig/models/modules/recurrent_modules.py#L445), which makes this statement in the documentation incorrect: "...followed by an rnn that generates outputs **feeding on its own previous predictions**..."

**Describe the solution you'd like**
Classification on the use of "teacher forcing", in which an rnn DOES NOT feed on its own previous predictions but the ground-truth of previous predictions instead.

**Comment by w4nderlust** [comment]
The decoder helper uses a greedy strategy for obtaining the predictions in evaluation mode, while it uses teacher forcing for training. Will clarify this in the docs.

**Comment by w4nderlust** [comment]
Added a mode detailed description in the documentation source, it will be reflected in the website next time it is built and deployed.
