### ISSUE TITLE
Option to not save any files to disk

### ISSUE THREAD

**Issue by BeWe11** [uber/ludwig#491]
I am building a small server around ludwig that receives model definitions + data and stores the resulting model for future predictions. I have turned on all `skip_save` parameters in the `train` method, but some files are still saved to disk.

In particular, the `results` directory is always created as well as some `.npy` files.

Is there any way to configure ludwig to not save anything to disk at all and handle all model persistence myself?

Edit:
I've seen that the prediction script offers a flag to skip saving of the `.npy` files, I've created a separate issue for adding this flag to the python API https://github.com/uber/ludwig/issues/492

So the remaining question is whether it's possible to not create a directory containing experiment results.

**Comment by w4nderlust** [comment]
Let me try to understand exactly the problem: the directory is created when running `LudwigModel.predict()`? Even when everything is skipped?
In that case, we'll certainly need to fix this.

**Comment by BeWe11** [comment]
Thanks for your response, I'll try to clarify what's happening:

The `LudwigModel.train` method accepts four parameters that allow to skip saving of files. These are
```
skip_save_mode
skip_save_progress
skip_save_log
skip_save_processed_input
```
I've set all of these to `True`, but the `results` directory is still being created. The parameter that sets the name of this directory is `output_directory`. I've tried setting this parameter to an empty string or to `None`, but both of these values lead to exceptions. There seems to be no way to avoid the creation of this directory.

Regarding `LuwdigModel.predict`, please take a look at my other issue https://github.com/uber/ludwig/issues/492. The `skip_save_unprocessed_output` parameter, which is available for the command line prediction script, is simply not exposed in the python API, so that the `*.npy` files are always being created and there is no way to turn that off.

**Comment by msaisumanth** [comment]
@w4nderlust this is why results is always being created:
https://github.com/uber/ludwig/blob/48acbf6cb63a859d06eb39b2f7ec27577394251d/ludwig/train.py#L525

We could probably delete all the intermediate data at the end of full_train (if the skip variables were True)

**Comment by w4nderlust** [comment]
Avooiding creating the dir to begin with is probably a better idea. We can
either remove the dir creation from within the function and check if at
least one skip is false and create the dir outside or pass a boolean
“should_create_dir” to this function.

On Mon, 19 Aug 2019 at 15:03, Sai Sumanth Miryala <notifications@github.com>
wrote:

> @w4nderlust
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w4nderlust&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=GZm3DGotTOSdbz48wBn3BYMrZsBkh23NdpjPoCO1yF4&s=KCjKWBQTuSE1PVVhMJsQ9IEYIz5Go8abkfwJGG8PPXM&e=>
> this is why results is always being created:
>
> https://github.com/uber/ludwig/blob/48acbf6cb63a859d06eb39b2f7ec27577394251d/ludwig/train.py#L525
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_blob_48acbf6cb63a859d06eb39b2f7ec27577394251d_ludwig_train.py-23L525&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=GZm3DGotTOSdbz48wBn3BYMrZsBkh23NdpjPoCO1yF4&s=mGcg6kfbJOEPDKbipo7Rp37CMG7fT6VIvYxlrnCQE_o&e=>
>
> We could probably delete all the intermediate data at the end of
> full_train (if the skip variables were True)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_491-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISGBONLN2ZRTZFDSDDTQFMH55A5CNFSM4ILN3JEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UMPTI-23issuecomment-2D522766285&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=GZm3DGotTOSdbz48wBn3BYMrZsBkh23NdpjPoCO1yF4&s=iTtpYVkSuRxiDn8NpRFKtgd4TZyhZyhGHbDRP8DZ7vk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISGPZ2X2M64MD7YGBDDQFMH55ANCNFSM4ILN3JEA&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=GZm3DGotTOSdbz48wBn3BYMrZsBkh23NdpjPoCO1yF4&s=OrpXfuYgEIoQWxVxPAGHrAT-IJk8WoI2k-sgYZ_LPuk&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs

**Comment by w4nderlust** [comment]
PR #530 should solve the issue. it adds two more skip parameters for training and two for testing. I know it's a bit clunky to have all these parameters, in the future we'll likely clean it up a bit to have something more elegant, but at least the functionality is there. Now if they are all false, the directory will not be created.
