### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by FankLi** [uber/ludwig#495]
User Guide Link is 404??

**Comment by flozi00** [comment]
Which did you try ?

https://uber.github.io/ludwig/getting_started/

https://github.com/uber/ludwig/blob/master/mkdocs/docs/user_guide.md

**Comment by FankLi** [comment]
> Which did you try ?
> 
> https://uber.github.io/ludwig/getting_started/
> 
> https://github.com/uber/ludwig/blob/master/mkdocs/docs/user_guide.md

It is good!!!
