### ISSUE TITLE
About Image Processing question

### ISSUE THREAD

**Issue by bobo04020802** [uber/ludwig#498]
i want process image， Does image processing require tagging?
Thank you very much.

like this

[https://pic2.zhimg.com/80/v2-fe55b7b84b598e924b6dffd374f42cdd_hd.jpg](url)

**Comment by carlogrisetti** [comment]
Any ML requires tagging basically, so if you want to simply do an image classification identifying that that's a picture of a dog you just need to feed many images of dogs, tagged with some sort of "dog" keyword.
If you want to be object detection (ie: tracing a bounding box identifying not only that that's a picture of a dog, but exactly where the dog is in the picture) that gets more complicated but it's feasible.
There's a PR ( #344 ) in the works to add a bounding box feature, but that still would require tagged images, and a lot more of those needed for a simple classification.

**Comment by bobo04020802** [comment]
ok，thank you ，now i go study~~
