### ISSUE TITLE
can't install ludwig due to fastapi

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#510]
I encounter error below while installing ludwig through terminal.
error: pydantic 0.30 is installed but pydantic<=0.32.2,>=0.32.2 is required by {'fastapi'}

can I use pydantic 0.32 instead of 0.30?

os: win10 64x86
cpu: i7

**Comment by simonefrancia** [comment]
same to me! 
os: macOS
cpu: i7

**Comment by w4nderlust** [comment]
Can't really understand the error, it looks like <=0.32.2 should batch with 0.30.
Try to install fastapi==0.33.0 beforehand, in my venv it works with that and pydantic 0.30.

**Comment by simonefrancia** [comment]
This resolved problem for `pydantic` but an other error occurred. 
`error: setuptools 39.0.1 is installed but setuptools>=41.0.0 is required by {'tensorboard'}`
but I installed `setuptools>=41.0.0` before installing ludwig.

**Comment by simonefrancia** [comment]
Ok, this command `python3.6 -m pip install setuptools>=41.0.0 fastapi==0.33.0 tensorboard` before installing ludwig, worked for me.

**Comment by Kantshun** [comment]
> Can't really understand the error, it looks like <=0.32.2 should batch with 0.30.
> Try to install fastapi==0.33.0 beforehand, in my venv it works with that and pydantic 0.30.

fastapi require pydantic 0.32.2, but in ludwig's setup.py file, it said "pydantic==0.30".
I simply modify the setup.py manually, change  "pydantic==0.30" to "pydantic==0.32.2", then I can install ludwig through terminal successfully. hopefully there wouldn't has any error occur in my later usage.

**Comment by w4nderlust** [comment]
I will try to remove the ==0.30.0 requirement, it was there because that version was required by another dependency.

**Comment by ajaypr55** [comment]
change requirement.txt,
change version to  pydantic==0.32.2
and change version  setup.py file too,
'pydantic==0.32.2',

then works fine.

**Comment by w4nderlust** [comment]
Fixed the issue, installing from master with `pip install git+http://github.com/uber/ludwig.git` will not require `pydantic==0.30.0 `anymore.
