### ISSUE TITLE
is there any examples about visualization of model?

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#516]
could you please provide some examples about visualization through API? after the model is trained and tested,  there are lots of files are saved, I have no idea of which file i shall use when visualising.
![image](https://user-images.githubusercontent.com/31396222/64919229-c5082b00-d7da-11e9-8163-639fb2b83747.png)
![image](https://user-images.githubusercontent.com/31396222/64919236-d6513780-d7da-11e9-8ddf-57ffb3d60f7b.png)

**Comment by w4nderlust** [comment]
The visualization API provides functions with parameters whose names are pretty recognizable. For instance `learning_curves` needs the training statistics file and you cna see you have a file `training_statistics.json` and likewise for predictions, probabilities and so on.
In the [visualization section](https://uber.github.io/ludwig/user_guide/#visualizations) of the user guide you can find examples of the commands, the API uses exactly the same name and parameters, so it should be easy to figure it out. Let us know if you have further doubts.

**Comment by Kantshun** [comment]
thank you
