### ISSUE TITLE
my ludwig may be not working properly

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#518]
when I start to train my ludwig model, lots of red words pop up. is there anything wrong with my ludwig?
system:win10 64
cup:i7
gpu:nvidis geforce 1060
![image](https://user-images.githubusercontent.com/31396222/65036050-1fd98800-d97d-11e9-829e-08ebb9c265b1.png)

**Comment by msaisumanth** [comment]
They're just deprecation warnings.
