### ISSUE TITLE
Multiple errors - numpy, after a successful installing Ludwig

### ISSUE THREAD

**Issue by fabikm** [uber/ludwig#521]
Please, can someone help? :)

Bug:
root@DESKTOP-IV7IIN5:~# ludwig train --model_definition_file model_definition.yaml --data_csv Tweets.csv
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.

For more information, please see:
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
https://github.com/tensorflow/addons
https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
Traceback (most recent call last):
File "/usr/local/bin/ludwig", line 11, in
load_entry_point('ludwig==0.2.1', 'console_scripts', 'ludwig')()
File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 108, in main
CLI()
File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 64, in init
getattr(self, args.command)()
File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 72, in train
from ludwig import train
File "/usr/local/lib/python3.6/dist-packages/ludwig/train.py", line 30, in
from ludwig.data.preprocessing import preprocess_for_training
File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 30, in
from ludwig.features.feature_registries import base_type_registry
File "/usr/local/lib/python3.6/dist-packages/ludwig/features/feature_registries.py", line 42, in
from ludwig.features.audio_feature import AudioBaseFeature
File "/usr/local/lib/python3.6/dist-packages/ludwig/features/audio_feature.py", line 21, in
import soundfile
File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 142, in
raise OSError('sndfile library not found')
OSError: sndfile library not found

Environment:
- Ubuntu 18.04.1 LTS under Linux Subsystem / Win 10
- Python 3.6.8
- pip3
- last version of ludwig September 2019

Additional context:
Ludwig has been installed from: git+https://github.com/uber/ludwig, without any problem.

**Comment by msaisumanth** [comment]
Can you take a look at this: https://github.com/bastibe/SoundFile/issues/118

Ideally you don't need all this unless you're using audio features in your model. Let me know if you're not able to fix it and I'll try to think of another work around.

**Comment by fabikm** [comment]
Thank you, so much! :) It works, the error has been fixed with:

install this
sudo apt-get install libsndfile1
