### ISSUE TITLE
Feature request: Autokeras / Automl

### ISSUE THREAD

**Issue by flozi00** [uber/ludwig#533]
Using an automl solution would make it even easier to train your own models without being an expert.
Furthermore, Ludwig would get new models / encoders on a regular basis by integrating the Autokeras API.
For example, new features like object recognition would be provided by the Autokeras team.

How hard would it be or is it even possible to integrate the Autokeras API?

https://autokeras.com/auto_model

**Comment by w4nderlust** [comment]
@flozi00  we are already working on a hyperparameter optimization extension as we announced a few months ago.

Regarding Autokeras. The architecture of Ludwig is substantially different in particular in how it treats the outputs. Ludwig has a compositional way of defining models while autokeras has a monolithic way of doing that, so there won't be any integration.
What people can do is actually adding input encoders and output decoders, which are much more useful than monolithic models as they can be reused for several different tasks.

**Comment by flozi00** [comment]
Thank you for the answer !
