### ISSUE TITLE
WARNING:tensorflow: when I run !ludwig experiment \

### ISSUE THREAD

**Issue by DavidNSEO** [uber/ludwig#534]
**Describe the bug**

When I write - "!ludwig experiment \" I get error - 
WARNING:tensorflow
The TensorFlow contrib module will not be included in TensorFlow 2.0.
ModuleNotFoundError: No module named 'soundfile'

**To Reproduce**
1.  I'm using Google Colab.
2. I have wrote -
"!pip install ludwig" (I have used the updated version)
and "!gsutil cp gs://dataset-uploader/bbc/bbc-text.csv ."
So far all work fine.
3. See error -
When I write - "!ludwig experiment \"
I get - 
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 108, in main
    CLI()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 67, in experiment
    from ludwig import experiment
  File "/usr/local/lib/python3.6/dist-packages/ludwig/experiment.py", line 28, in <module>
    from ludwig.data.postprocessing import postprocess
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/postprocessing.py", line 19, in <module>
    from ludwig.features.feature_registries import output_type_registry
  File "/usr/local/lib/python3.6/dist-packages/ludwig/features/feature_registries.py", line 42, in <module>
    from ludwig.features.audio_feature import AudioBaseFeature
  File "/usr/local/lib/python3.6/dist-packages/ludwig/features/audio_feature.py", line 21, in <module>
    import soundfile
ModuleNotFoundError: No module named 'soundfile'

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 
- Python 3 version

**Comment by tboo** [comment]
`pip install soundfile` should solve it.

**Comment by DavidNSEO** [comment]
I did - pip install soundfile
The result - 
Requirement already satisfied: soundfile in /usr/local/lib/python3.6/dist-packages (0.10.2)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.6/dist-packages (from soundfile) (1.12.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.0->soundfile) (2.19)

I have run again - !ludwig experiment \
and got the same issue like I have wrote before -
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

usage: ludwig experiment [options]
ludwig experiment: error: one of the arguments -md/--model_definition -mdf/--model_definition_file is required

Can you please advice ?
*I don't have too much programing background and new to Jupyter notebook so LMK if I do a basic mistake.
Here is what I did - https://drive.google.com/open?id=1CcAINGPm4RRl3nAnCk4N7OEPeb1ULRad

**Comment by tboo** [comment]
You need to specify the data annotation csv file and you would need to define the model. many examples for that are listed [here](https://uber.github.io/ludwig/examples/)

**Comment by w4nderlust** [comment]
> `pip install soundfile` should solve it. (@w4nderlust something to include in the requirements.txt ;))

I changed the way requirements is structured. You can see here how it works now: https://github.com/uber/ludwig/blob/master/README.md#installation

I still have to make it so that the packages in the extensions are imported conditionally and not automatically. That will be done today.

In the meantime people can just install the `[full]` extension.

**Comment by w4nderlust** [comment]
> usage: ludwig experiment [options]
> ludwig experiment: error: one of the arguments -md/--model_definition -mdf/--model_definition_file is required

Two things here:
1. ignore the TensorFlow warning. It's something they added for suggesting users how to migrate to TensorFlow 2.
2. If you look at the output of the command, it explains to you what is wrong, namely you did not specify a model definition. You also did not specify the data you want to train on. I suggest you to read the [Getting Started](https://uber.github.io/ludwig/getting_started/) guide and later on the [User Guide](https://uber.github.io/ludwig/user_guide/). Also `ludwig experiment --help` explains the parameters available to you.

**Comment by AlexeyGy** [comment]
To improve user experience with the CLI, I suggest hiding the TensorFlow warning level messages by default. Could add a ```--debug``` flag to still show them.

**Comment by w4nderlust** [comment]
That warning is the only one left anyway.

On Sat, 12 Oct 2019 at 03:00, Alexey Györi <notifications@github.com> wrote:

> To improve user experience with the CLI, I suggest hiding the TensorFlow
> warning level messages by default. Could add a --debug flag to still show
> them.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_534-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISGUYXHJVRU4WZTXJALQOGN2HA5CNFSM4I7VQB42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB3RVQ-23issuecomment-2D541309142&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=pDyiPPBeNcoFJHciwNRJxqmEKPlnfuKiroiNcCtVzxY&s=DtvYVWQlHHgPJa5h9ITmqiSL5jBQRLR6wgpCMBLK4Hk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISAKSADGXTBPVDYQ3XTQOGN2HANCNFSM4I7VQB4Q&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=pDyiPPBeNcoFJHciwNRJxqmEKPlnfuKiroiNcCtVzxY&s=W0A2lbxS-X8ECbJjHrmUvLErsgdukuINWy09jtZWGJM&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs

**Comment by AlexeyGy** [comment]
<img width="1664" alt="Screenshot 2019-10-12 at 21 20 19" src="https://user-images.githubusercontent.com/13885630/66706682-27027480-ed36-11e9-965d-f03f30cb80f9.png">
I am also seeing the ones for TensorBoard as per screenshot.

I would argue that it is disruptive esp. first time users. This then makes them open up new Github issues like this one.

**Comment by w4nderlust** [comment]
I'm not going to address it. If you look around reading about tensorflow warning you'll soon figure out there is no unique, non hacky way or removing them, even by setting environment variables.
I will just wait for newer versions of tensorflow to solve their internal warning issues because in most cases removing them mean either removing all warnings and info, even useful ones, or writing specific pieces of nasty code that uses some tensorflow internal variables and functions and by consequence is unmaintainable.and will result in broken code later in the future. On the Ludwig side, we are already trying to address all the deprecation warnings we can, and will keep on doing it in the future.

**Comment by tboo** [comment]
> I changed the way requirements is structured. You can see here how it works now: https://github.com/uber/ludwig/blob/master/README.md#installation

This is a great solution. Thanks :)
