### ISSUE TITLE
Inform users of --help command, improve cli help

### ISSUE THREAD

**Issue by AlexeyGy** [uber/ludwig#536]
When running the ```ludwig``` command, the following info is displayed:

<img width="1260" alt="Screenshot 2019-10-12 at 12 04 48" src="https://user-images.githubusercontent.com/13885630/66699593-93568700-ece8-11e9-933d-3aae1a9f04e2.png">

I suggest changing it to the same message that is displayed when running ```ludwig --help``` albeit with a few small tweaks orienting themselves at the help command of the ```pip``` package manager:

**OLD**
<img width="963" alt="Screenshot 2019-10-12 at 12 09 29" src="https://user-images.githubusercontent.com/13885630/66699718-59d24b80-ece9-11e9-8f51-d9b5bbf55ef3.png">

**NEW**
ludwig -h and ludwig show the same message:

```
Usage: 
    ludwig <command> [options]

Commands:
   experiment            Runs a full experiment training a model and testing it
   train                 Trains a model
   predict               Predicts using a pretrained model
   serve                 Serves a pretrained model
   test                  Tests a pretrained model
   visualize             Visualizes experimental results
   collect_weights       Collects tensors containing a pretrained model weights
   collect_activations   Collects tensors for each datapoint using a pretrained model

Description:
   ludwig cli runner

General Options:
  -h, --help                  Show contextual help.
```
Now each command then just as now has its separate help including a Description and a contextual options list. Which should separate required arguments, e.g. for ```train``` model_definition_file or model_definition from optional arguments.

**Comment by w4nderlust** [comment]
I don't think `ludwig` and `ludwig -h` should have the same output. In the first case it is correct to show an error for the missing command, in the second case it is not. Will keep things as the they are.

**Comment by AlexeyGy** [comment]
Would you support adding information about the -h command when just running ludwig? I for one was not aware that it existed.
