### ISSUE TITLE
date feature question / michelangelo

### ISSUE THREAD

**Issue by tboneai** [uber/ludwig#543]
I am having an issue with the date that I cannot figure out and a general question. I am a driver, not a programmer, so please bear with me.   :)

My csv file passes the date as yyyymmdd hhmmss. I have tried the default, different yaml nesting,  and multiple combinations of '%Y%m%d %H%M%S' but I still cannot get it to work. Does the file need changed to include a / and : in the date field? Any help would be appreciated. (leaving the date preprocessing blank has gotten me the farthest, or clearest error) 

My other question revolves around predictions and the Uber Summit video regarding Michelangelo and Uber Eats where an update is passed to better determine when the food will be ready and when a driver is called. I am trying to predict the forex market 5 minutes in advance and would like to pass new data along (lets say at 2 and 4 minutes) to better determine the closing price at 5 minutes. Is that possible with Ludwig without re-running the entire job? If I just add data and then re-run it, without Ludwig knowing the previous prediction, I am afraid it may not recalculate correctly. 
Lastly, I would like to say Thank You to the crew at Uber Engineering for making Ludwig available. I know there may be better, or easier, cut and paste options for me from the internet but that's no way to learn. I apologize for the cut and paste job
------------------------------------------------------------------------------------------------------------
Datestamp,open,high,low,close,volume
20191001 000000,1.088760,1.088790,1.088650,1.088650,0

-------------------------------------------------------------------------------------------------------------
input_features:
    -
        name: datestamp
        type: date
    -
        name: open
        type: numerical
    -
        name: high
        type: numerical
    -
        name: low
        type: numerical
    -
        name: close
        type: numerical
output_features:
    -
        name: open
        type: numerical
    -
        name: high
        type: numerical
    -
        name: low
        type: numerical
    -
        name: close
        type: numerical
preprocessing:
        force_split: false
        split_probabilities: [0.7,0.1,0.2]
        stratify: null
        missing_value_strategy: backfill
        encoder: wave
        cell_type: lstm_cudnn
        gpus: 0

-------------------------------------------------------------------------------------------------------------
command: ('C:\\Users\\tmine\\env\\Scripts\\ludwig experiment --data_csv '
 'env\\lib\\eurusd_data.csv -mdf env\\lib\\model_definition_file.yaml')
random_seed: 42
input_data: 'env\\lib\\eurusd_data.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'name': 'datestamp',
                              'tied_weights': None,
                              'type': 'date'},
                          {   'name': 'open',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'high',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'low',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'close',
                              'tied_weights': None,
                              'type': 'numerical'}],
    'output_features': [   {   'clip': None,
                               'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'open',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical'},
                           {   'clip': None,
                               'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'high',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical'},
                           {   'clip': None,
                               'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'low',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical'},
                           {   'clip': None,
                               'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'close',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical'}],
    'preprocessing': {   'audio': {   'audio_feature': {'type': 'raw'},
                                      'audio_file_length_limit_in_s': 7.5,
                                      'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'norm': None,
                                      'padding_value': 0},
                         'bag': {   'fill_value': '',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'cell_type': 'lstm_cudnn',
                         'date': {   'datetime_format': None,
                                     'fill_value': '',
                                     'missing_value_strategy': 'fill_with_const'},
                         'encoder': 'wave',
                         'force_split': False,
                         'gpus': 0,
                         'h3': {   'fill_value': 576495936675512319,
                                   'missing_value_strategy': 'fill_with_const'},
                         'image': {   'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'num_processes': 1,
                                      'resize_method': 'interpolate',
                                      'scaling': 'pixel_normalization'},
                         'missing_value_strategy': 'backfill',
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const',
                                          'normalization': None},
                         'sequence': {   'fill_value': '',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'tokenizer': 'space',
                                         'unknown_symbol': '<UNK>',
                                         'vocab_file': None},
                         'set': {   'fill_value': '',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'split_probabilities': [0.7, 0.1, 0.2],
                         'stratify': None,
                         'text': {   'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'char_tokenizer': 'characters',
                                     'char_vocab_file': None,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256,
                                     'word_tokenizer': 'space_punct',
                                     'word_vocab_file': None},
                         'timeseries': {   'fill_value': '',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256,
                                           'tokenizer': 'space'},
                         'vector': {   'fill_value': '',
                                       'missing_value_strategy': 'fill_with_const'}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 5,
                    'epochs': 100,
                    'eval_batch_size': 0,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 1,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}

Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Traceback (most recent call last):
  File "c:\users\tmine\env\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tmine\env\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\users\tmine\env\lib\site-packages\ludwig\cli.py", line 108, in main
    CLI()
  File "c:\users\tmine\env\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\users\tmine\env\lib\site-packages\ludwig\cli.py", line 69, in experiment
    experiment.cli(sys.argv[2:])
  File "c:\users\tmine\env\lib\site-packages\ludwig\experiment.py", line 529, in cli
    experiment(**vars(args))
  File "c:\users\tmine\env\lib\site-packages\ludwig\experiment.py", line 219, in experiment
    **kwargs
  File "c:\users\tmine\env\lib\site-packages\ludwig\train.py", line 287, in full_train
    random_seed=random_seed
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 339, in preprocess_for_training
    random_seed=random_seed
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 485, in preprocess_for_training_by_type
    random_seed=random_seed
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 614, in _preprocess_csv_for_training
    random_seed=random_seed
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 68, in build_dataset
    **kwargs
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 89, in build_dataset_df
    global_preprocessing_parameters
  File "c:\users\tmine\env\lib\site-packages\ludwig\data\preprocessing.py", line 129, in build_metadata
    dataset_df[feature['name']].astype(str),
  File "c:\users\tmine\env\lib\site-packages\pandas\core\frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "c:\users\tmine\env\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datestamp'

**Comment by tboneai** [comment]
Added / & : to date string in the data file and included the preprocessing field and datetime_format in the yaml file. File now runs. Closing ticket since the second item was a discussion

**Comment by w4nderlust** [comment]
Glad you solved the issue. Regarding the dicussion part, i don't quite get the question, could you try to rephrase please?

**Comment by tboneai** [comment]
Hi Piero, thank you for replying. I may have figured it out while reading another timeseries ticket but here is what I would like to accomplish. 
I am using 1 min data in an attempt to predict 5 mins into the future. I would like to receive the 5 min prediction, then 2 mins later give Ludwig new data and receive a 3 minute prediction. Then compare the two results in order to see if it provides a more accurate 5 min forecast. 
With that said, while reading another ticket you mentioned the market was a level 2 chaos system. Would it be more appropriate to use Pyro or recreate Slawek's es-rnn model using only tensorflow instead of Ludwig? 

Tyrone  


Sent from Yahoo Mail for iPad


On Wednesday, October 23, 2019, 11:04 PM, Piero Molino <notifications@github.com> wrote:


Glad you solved the issue. Regarding the dicussion part, i don't quite get the question, could you try to rephrase please?

**Comment by w4nderlust** [comment]
I think all the tools you described can be used for the task. Which is more appropriate depends on the details. FOr instance Ludwig would be more appropriate most likely if you have additional information other than just the time series (like categories, or any other additional feature).
