### ISSUE TITLE
ValueError: No training data is provided!

### ISSUE THREAD

**Issue by BY-hash** [uber/ludwig#561]
Hello,
I've tried running 
ludwig train --model_resume_path C:\Users\user\Desktop\DataSet\ieee28nodesOriginal --model_definition "{input_features: [{name: T_in1, type: numerical},{name: T_in2, type: numerical}], output_features: [{name: T_out1, type: numerical},{name: T_out2, type: numerical}]}"
and for some reason no matter what changes I've tried, I always get the error
"ValueError: No training data is provided!"
Any help appriciated!

The data is attached in Word format. (ieee28nodesOriginal ofcourse is of .csv UTF-8 type)

[28node.docx](https://github.com/uber/ludwig/files/3816617/28node.docx)

**Comment by msaisumanth** [comment]
Did you train a model before this already?

--model_resume_path is used to continue the training of a model from a previous experiment.

**Comment by w4nderlust** [comment]
I think the error is pretty clear, you should provide the data with `--data_csv`, while you are trying to provide it with `--model_resume_path` that is unrelated,

**Comment by BY-hash** [comment]
Thank you
