### ISSUE TITLE
Export Image Architecture of the Model

### ISSUE THREAD

**Issue by rafaelmarconiramos** [uber/ludwig#562]
Ludwig is an AUTOML, but I want know which architecture is applied in the solution.
I think who works with CNN wants to know what architecture is using.
Is it possible to export an image with the architecture?

**Comment by msaisumanth** [comment]
What do you mean by export an image? You can use tensorboard to visualize the underlying tensorflow graph. If you just want to see which encoder/decoder etc. were used, you can see that in the results directory. 

If it's something else, please elaborate or provide an example.

**Comment by w4nderlust** [comment]
Ludwig has nothing to do with AutoML right now.
Moreover, the architecture is fully described in the user guide, the variables are printed if you set the logging level to debug and you can look at the full computational graph if you open the model with tensorboard.
