### ISSUE TITLE
Disable split in ludwig test 

### ISSUE THREAD

**Issue by karthikkrishnanv** [uber/ludwig#573]
**Is your feature request related to a problem? Please describe.**
I am unable to get ludwig test to product results on the entire dataset. Not sure if I am missing something or needs a new feature to disable split.

**Describe the use case**
Dataset is trained using individual train/valid/test csv (i.e via ludwig train --data_train_csv train.csv  --data_validation_csv valid.csv  --data_test_csv  test.csv -mdf model_definition.yaml ). Now I want to look into the statistics of test.csv (say using ludwig test  --data_csv test_with_split.csv --train_set_metadata_json train.json -m results/experiment_run_4/model/ -s full). test_with_split.csv is the same file as test.csv with an added column 'split' set to 2. This always returns only a subset of data. test_with_split.csv has 50K lines, while the predictions inside results dir is ~12K data points. 

I've tried using ludwig predict with --evaluate_performance, but it looks like it isn't supported [ludwig predict: error: unrecognized arguments: --evaluate_performance]

Doc states "If the argument --evaluate_performance if provided, a predict_statistics.json file containing all prediction statistics will also be outputted"

**Describe the solution you'd like**
If ludwig test can simply take a file and output all the predictions with test statistics, it would be great (or a simple way to avoid split column)

**Describe alternatives you've considered**
I might have to handroll the predictions, but would rather use the awesome statistics already provided.

**Comment by w4nderlust** [comment]
Should use `split = full`

**Comment by karthikkrishnanv** [comment]
ludwig test works. Sorry for the faux paus. Turned out I was looking at the number of lines incorrectly due to the new lines in some of the records and how it showed up in the editor.

**Comment by w4nderlust** [comment]
No worries, glad there was no problem.
