### ISSUE TITLE
Proposal:  Training performance improvements on cpu-only platforms

### ISSUE THREAD

**Issue by jimthompson5802** [uber/ludwig#574]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the use case**

In reviewing Ludwig's code base, I noticed in `ludwig/utils/tf_utils.py` this [code fragment](https://github.com/uber/ludwig/blob/master/ludwig/utils/tf_utils.py#L43):
``` 
def get_tf_config(gpus=None, gpu_fraction=1, horovod=None,
                  allow_parallel_threads=True):
    intra_op_parallelism_threads = 2  # defult in tensorflow
    inter_op_parallelism_threads = 5  # defult in tensorflow
```

This sequence hard codes Tensorflow's configuration parameter `intra_op_parallelism_threads` to the value '2'.  According to [Tensorflow's documentation](https://github.com/tensorflow/tensorflow/blob/v1.14.0/tensorflow/core/protobuf/config.proto#L341) setting `intra_op_parallelism_threads=0` allows the Tensorflow's run-time to select a system appropriate value.

This chart shows the effect of setting `intra_op_parallelism_threads = 0` on two different platforms: MacBookPro (8vcpu/16GB RAM) and an AWS c5.4xlarge (16vcpu/32GB RAM).  As the chart shows, reductions in the training time per epoch is possible with the '0' setting:
![intra_op_effect_on_training](https://user-images.githubusercontent.com/1425269/69014012-14daae00-0954-11ea-92ca-b8e21f1a73bb.png)

Note: 

* This reflects testing only with a CNN architecture.  I have not done testing on other types of neural network architectures.  I'm assuming similar results will hold with other types of neural network architectures.
* This proposal covers cpu-only platforms and not gpu-enabled platforms.
* No assessment on changing the default value of `inter_op_parallelism_threads`

**Describe the solution you'd like**

* For `intra_op_parallelism_threads` change default value from '2' to '0'.
* Provide a mechanism to override the default value to a user specified value.  The override mechanism could be provided in one of two ways:
  * Adding a key to the `training` section in the model definition, e.g.,
  ```
  training:
    tensorflow_intra_op_parallelism_threads: 2
  ```
  * Add parameter to LudwigModel's `train` method, e.g., 
  ``` 
  def train(
    . . .
    tensorflow_intra_op_parallelism_threads = 0,
    . . .
    ):
      . . .
  ```
    Ludwig's cli will be updated to reflect this additional parameter.
  

**Describe alternatives you've considered**

See previous section.

**Additional context**

If this proposal is acceptable, I'm willing to work on its implementation.  I'll need guidance on the override mechanism.

If there is interest, these are the training logs from the benchmark training runs.
[intra_op_2_macbook.txt](https://github.com/uber/ludwig/files/3856096/intra_op_2_macbook.txt)
[intra_op_0_macbook.txt](https://github.com/uber/ludwig/files/3856097/intra_op_0_macbook.txt)
[intra_op_2_aws.txt](https://github.com/uber/ludwig/files/3856098/intra_op_2_aws.txt)
[intra_op_0_aws.txt](https://github.com/uber/ludwig/files/3856099/intra_op_0_aws.txt)

**Comment by w4nderlust** [comment]
Interesting finding, thank you. Those parameters were likely the default in older versions of TensorFlow, we can run a few more tests and in case update them as you suggested.

**Comment by w4nderlust** [comment]
Set both to 0 after some testing, it's faster this way.

**Comment by jimthompson5802** [comment]
I'm glad this worked out.
