### ISSUE TITLE
Really slow startup time

### ISSUE THREAD

**Issue by sk-** [uber/ludwig#58]
Starting `ludwig` is really slow, taking more than 10 seconds to start on a macbook pro. This is probably due to some model imports.

```
$ time ludwig --help
usage: ludwig <command> [<args>]

Available sub-commands:
   experiment            Runs a full experiment training a model and testing it
   train                 Trains a model
   predict               Predicts using a pretrained model
   visualize             Visualizes experimental results
   collect_weights       Collects tensors containing a pretrained model weights
   collect_activations   Collects tensors for each datapoint using a pretrained model

ludwig cli runner

positional arguments:
  command     Subcommand to run

optional arguments:
  -h, --help  show this help message and exit

real	0m11.582s
user	0m8.958s
sys	0m1.447s
```

**Comment by w4nderlust** [comment]
The main reason is that it imports a lot of libraries. For instance the `visualize` module imports matplotlib that is not used by any other modules. I don't have a solution right now on how to solve this, but I definitely want to improve speedup time. If you have suggestions or links feel free to past them here.

**Comment by w4nderlust** [comment]
This commit partially adresses the issue: https://github.com/uber/ludwig/commit/a211400bcaa2892a73196cbd2317bb5c77cccdec
Startup time has improved up to 50%. Still not blazingly fast, but some improvement had been made.

**Comment by Felix-N** [comment]
i wondered about the same. im our case we run a system continously to classify incoming images, though have no real time requirement.

that said the startup time is not the biggest issue, though calling
`    predictions = ludwig_model.predict(data_df=dataframe)`
feels as if it initializes each time, and hence the slow feeling

**Comment by w4nderlust** [comment]
@Felix-N not sure what are actually doing, but no, if you call `ludwig_model.predict` it does not initialize each time, just the first time and then the tensorflow session keeps open.
Anyway, in the next couple days I'm going to release v0.1.2 which speeds up loading even more (at the expense of a little change in the api).

**Comment by w4nderlust** [comment]
We did substantial improvements in speeding up load time, suggestions are welcome on how to improve even further, but at the moment I consider it not to be an issue anymore.
