### ISSUE TITLE
how to use chinese text to do classification?

### ISSUE THREAD

**Issue by guhuawuli** [uber/ludwig#581]
**Is your feature request related to a problem? Please describe.**

Does ludwig support multi language? I want to use chinese text to do classification. how to do preprocess, segmentation, embedding?

**Describe alternatives you've considered**
Tensorflow is supporting multi-language feature, if ludwig is based on tensorflow, maybe the above problem is not so difficult.

**Comment by w4nderlust** [comment]
Thanks for asking this question @guhuawuli.. There is curently no specific mechanism for chinese text, but you tokenize the text as characters and use a character based model (use `level: char` in you text feature to obtain this(. If you can point me to the specific mechanism in TensorFlow for dealing with Chinese I will take a look and try to integrate it.

**Comment by w4nderlust** [comment]
SpaCy added Chinese as language in release 2.3, this commit adds new Chinese preprocessing to Ludwig, so this issue should be considered solved.
