### ISSUE TITLE
ValueError: Key rnn not supported, available options: dict_keys(['stacked_cnn', 'resnet'])

### ISSUE THREAD

**Issue by rafaelmarconiramos** [uber/ludwig#582]
I am testing different encoders supported by Ludwig, but when I use rnn (and others), for example, it generates an error:

**ValueError: Key rnn not supported, available options: dict_keys(['stacked_cnn', 'resnet'])**

If I use "stacked_cnn" or "resnet," the application workes well.

My YAML file is:

input_features:
    -
        name: image_path
        type: image
        encoder: rnn

output_features:
    -
        name: categoria
        type: category

training:
    batch_size: 100
    epochs: 100
    early_stop: 50
    learning_rate: 0.0001

My executed command:

python -m ludwig.train --output_directory "/home/rafael/ludwig/log/exp1/rnn/" --data_train_csv "/home/rafael/ludwig/train64.csv" --model_definition_file "/home/rafael/ludwig/rnn.txt"

ludwig Version: 0.2.1
Python 3.5.2

**Comment by manesioz** [comment]
It states in the [documentation](https://uber.github.io/ludwig/user_guide/#image-features): 

>Currently there are two encoders supported for images: Convolutional Stack Encoder and ResNet encoder which can be set by setting encoder parameter to `stacked_cnn` or `resnet` in the input feature dictionary in the model definition (`stacked_cnn` is the default one).

**Comment by w4nderlust** [comment]
@rafaelmarconiramos there is no rnn encoder for images. Please check the documentation as @manesioz suggested for knowing about the available encoders for each feature type.
