### ISSUE TITLE
model's predictions accuracy

### ISSUE THREAD

**Issue by BY-hash** [uber/ludwig#587]
Hello,

Is there any way availabe in ludwig to estimae the error of predication for numeric values? (since I can't use ROC curve for binary problems or confusion matrix for labeling problems)

At the same context, for the case that there is no prediction performance measurments avalible for numeric problems, and say I calculate the MSE (of my predictions vs. the pre-known correspondoing outputs), In order that this MSE value would have any meaning I must have some a-priory knowledge of the lack of fit of the model. 
Thougth maybe I could  get this by looking at  "train_batch_mean_squared_error_T_out2 " graph for example(screenshot linked). Would like to make sure that this graph is indeed relavent for this purpose:
 It means that in epochs 15 the MSE was 1.06e-4? This MSE is relative to what? Here, when training in each epochs the model "predict" different output until its close enogh to the output given to the model for its training? so this graph is a good measure to the lack of fitting of the model?

Thank you!

![image](https://user-images.githubusercontent.com/51758806/69967012-3b861080-1520-11ea-940a-7b2e553d5f27.png)

**Comment by msaisumanth** [comment]
sorry for the late response. For numerical features, you can measure Mean Square Error, Mean Absolute Error and R-squared.

**Comment by w4nderlust** [comment]
And they are calculated depending on the ground truth of the different sets (training, validation and test). How to quantify whan constitutes a good prediction depends on your problem and also depends on the range of values you are trying to predict. If you values are between 0 and 10 and the MAE is  5, that's a pretty bad prediction and 0.5 would be a relatively good prediction, but if you values are between 0 and 1, 0.5 MAE would be pretty bad.

**Comment by solyron** [comment]
yes, thank you
