### ISSUE TITLE
Feature Request: Export models as TensorFlow models

### ISSUE THREAD

**Issue by sk-** [uber/ludwig#59]
Would it be possible to export the models as TensorFlow models. In that way we wouldn'nt need to depend on `ludwig` and its dependencies to just run the inference part, and additionally we could convert the models to `tflite` so that we run them on mobile.

May be related to #55.

**Comment by w4nderlust** [comment]
Yeah closing this one as a duplicate of #55 . I answered there, please continue the discussion there.
