### ISSUE TITLE
Wrong User Guide description for H3 Input Features and Encoders section 

### ISSUE THREAD

**Issue by weifengpdx** [uber/ludwig#591]
**Describe the bug**

The User Guide description for the H3 Input Features and Encoders is using Date Feature's description, needs update.

**To Reproduce**

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Python version
- Ludwig version

**Additional context**

**Comment by msaisumanth** [comment]
It's a minor error, only this part needs to be fixed

```Currently there are two encoders supported for dates: Embed Encoder and Wave encoder which can be set by setting encoder parameter to embed or wave in the input feature dictionary in the model definition (embed is the default one).
```
The actual section explaining the encoders is correct.

**Comment by w4nderlust** [comment]
Should be fixed, let me know if there are further errors.
