### ISSUE TITLE
"Bad" error message and inconsistent behavior between large dataframe and large file

### ISSUE THREAD

**Issue by George3d6** [uber/ludwig#593]
**Describe the bug**
When training with ludwig using a large file (0.58 million rows x 18 columns, mostly of categorical and text types) training works fine, however, when passing that file as a dataframe, after a while I get the following error (pasting the relevant bits of the stack trace w/o file system info):

```                                                                                                         
    train_stats = model.train(data_df=training_sample, model_name='blah', skip_save_progress=True, gpus=get_useable_gpus())                                                                                                                                                                                             
  File "ludwig/api.py", line 529, in train                                                                                                    
    debug=debug,                                                                                                                                                                              
  File "ludwig/train.py", line 287, in full_train                                                                                             
    random_seed=random_seed                                                                                                                                                                   
  File "udwig/data/preprocessing.py", line 326, in preprocess_for_training                                                                   
    random_seed=random_seed                                                                                                                                                                   
  File "ludwig/data/preprocessing.py", line 543, in preprocess_for_training_by_type                                                           
    train_set_metadata.get(DATA_TRAIN_HDF5_FP)                                                                                                                                                
  File "ludwig/data/dataset.py", line 25, in __init__                                                                                         
    self.size = min(map(len, self.dataset.values()))                                                                                                                                          
AttributeError: 'NoneType' object has no attribute 'value
```

Passing the exact same data-frame but with `.iloc[0:4000]` (i.e. a very small sub-sample) doesn't run into this error, so I assume this error has to do with the size of the data.

**To Reproduce**
I can't share the file since it's proprietary information, if you don't have a large dataset handy to replicate I can generate one locally and write the code to replicate then update here.

**Expected behavior**
Ideally, I'd expect ludwig to handle dataframes and files the same way.

Realistically, I guess this might be hard, but it might be easy to make the above error more explicit in telling the user that whatever happened was due to size.

**Environment (please complete the following information):**
(Note, tried on multiple operating system, initially the bug was encountered on ubuntu 18.04)
 - OS: Linux
 - Version: 5.3.8-arch1-1
- Python version: 3.7.4 (Also happened on 3.6.8 on the machine ubuntu)
- Ludwig version: 0.2.1

**Comment by msaisumanth** [comment]
@George3d6 I don't think it's because of size. The error is basically because the preprocessed dataset is ```None```.

 When you say training works fine, did you use the command line to train the model?

**Comment by George3d6** [comment]
@msaisumanth I severely doubt this because when I feed the same dataframe but with `.iloc[0:4000]` it works fine.

I used the command line to train with the file. I used the library/API from within python code to train with the dataframe (both the full one, which produces that error, and the one with `.iloc[0:4000]`, applied to it, which doesn't)

**Comment by George3d6** [comment]
Actually @msaisumanth , it might be that you're right and I've been chasing a ghost, I'll check and close the issue if it turns out it's indeed an empty/None dataframe being passed.

**Comment by George3d6** [comment]
Ok, I think the issue was that I was accidentally passing an empty dataframe, my bad :/ Will close the issue, sorry for the bother.

**Comment by w4nderlust** [comment]
@George3d6 no worries, please let us know if you encounter other problems.
