### ISSUE TITLE
Disable certain columns quickly (feature request)

### ISSUE THREAD

**Issue by mangleddata** [uber/ludwig#600]
**Is your feature request related to a problem? Please describe.**
Would like to know if there's a quick way to disable a feature without having to modify csv and the model file. 

**Describe the use case**
I have a use case with many columns, some of which may be either redundant or not contributing to the model. In a random forest world, I would've looked for feature importance and trim the feature columns. Would be great if there's a simple way to enable spot disabling to get runs. For example, I imagine some override parameter disable somewhere (model config or the main script) to disable a specific column for quick tries.

**Describe the solution you'd like**
disable parameter in the model config

**Describe alternatives you've considered**
Rebuild csv and model file after removing specific columns.

**Comment by msaisumanth** [comment]
@mangleddata I'm not sure what you're looking for. In the model definition, you have to explicitly specify all the columns you want to work with. Could you please provide a more concrete example?

**Comment by mangleddata** [comment]
@msaisumanth - Here is what I mean. Let's say I start with 10000 rows with 100 columns/features. I build the model file with all the 100 columns specified and run my model. If I want to remove say few columns (say 5) to check how the performance is affected, I believe I need to create a new csv with those 5 columns removed from the csv as well as model file. What I meant was, if there's a quick way to run ludwig by simply setting a avoid or disable flag in model file. But your question makes me think, if I don't explicitly include the column in model file, would it be automatically ignored (which is what I want)

**Comment by msaisumanth** [comment]
Yeah, if you don't specify in the model definition, it will be ignored. Try the LudwigAPI. 

That way, you can pass the model definition as a dictionary. You can drop and add keys programatically.

**Comment by mangleddata** [comment]
This is great! Thanks for the quick response. Been using the ludwig train command with the model file/dataset generated programmatically upstream. Will look into the API. Closing as it is already supported.
