### ISSUE TITLE
pip install Ludwig[viz] doesn't work in a terminal with zsh shell active

### ISSUE THREAD

**Issue by ralfbanisch** [uber/ludwig#602]
**Is your feature request related to a problem? Please describe.**
in a Mac OSX terminal with the zsh shell, installation of Ludwig with optional keywords [viz] etc. doesn't work:

`zsh: no matches found: ludwig[viz]`

Switching to bash shell solves the problem.

**Describe the use case**
installing Ludwig in zsh shell.

**Describe the solution you'd like**
Either document somewhere that the zsh shell doesn't support this, or enable zsh support.

**Comment by msaisumanth** [comment]
Thanks for creating the issue @ralfbanisch 

I found this solution on stackoverflow:
https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity

with zsh, you just need to do:

```pip install 'ludwig[viz]'```

I feel it'd be too much to include in the documentation, so let's leave it here for now.
