### ISSUE TITLE
Add class_weights to binary output features loss for dealing with unbalanced data

### ISSUE THREAD

**Issue by iEvidently** [uber/ludwig#615]
Good day,

Please, I will like to know how to handle imbalanced text classification. I have class distribution of 8.4% versus 91.6%. Show oversample before passing the data to Ludwig or just use 'loss' class_weight. 

I will be glad if you can help clarify how to calculate class_weight.

Thanks

**Comment by msaisumanth** [comment]
@iEvidently You can specify class weights for the loss function as follows:
```yaml

output_features:
    -
        name: intent
        type: category
        loss:
             class_weights: [5, 1, 1]
```

This would give the weight 5 for class '0', 1 for class '1' and 1 for 'UNK' (unknown). You'll have to experiment with these numbers to get better performance.

**Comment by iEvidently** [comment]
@msaisumanth Thanks a lot for the suggestion. When I added the class_weights for the model, I got the following error: 

`loss_weight = float(self.loss['weight'])
KeyError: 'weight'`

Since my model is a binary  classification, I think 'class-weight' may not be applicable.

My original model definition was:

`input_features:
  - name: sentence
    type: text
    encoder: parallel_cnn
    level: word

output_features:
  - name: label
    type: binary

training:
  epoch: 5`

From the Ludwig output:

` 'output_features': [   {   'dependencies': [],
                               'loss': {   'confidence_penalty': 0,
                                           'positive_class_weight': 1,
                                           'robust_lambda': 0,
                                           'weight': 1},
                               'name': 'label',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'threshold': 0.5,
                               'type': 'binary'}],`

I could not find instruction for specifying 'positive_class_weight'.

Please, should I use the following format:

positive_class_weight:5
weight:1

Thanks once again for taking time out of your busy schedule to help with this.

**Comment by msaisumanth** [comment]
Can you share how you added the class weights to the model definition?

**Comment by iEvidently** [comment]
This is how added the class weights:

`input_features:
    -
        name: sentence
        type: text
        level: word
        encoder: parallel_cnn

output_features:
    -
        name: label
        type: binary
        loss:
             class_weights: [5, 1, 1]`

**Comment by msaisumanth** [comment]
Got it. It looks like the format is different for category features and binary features. For binary, the current expectation is like below:

```yaml
output_features:
     - 
         name: 
         type: binary
         loss:
                weight: 5
```

I just verified that this works. Maybe we should have the same notation for both binary and category features @w4nderlust

**Comment by iEvidently** [comment]
@msaisumanth Thanks for clarifying that. No more error message with ```weight: 5```

**Comment by w4nderlust** [comment]
There's a bit of confusion here. `weight` is not the class weight for binary features. `weight` is a parameter used when a multi-task setting is used, i.e. when there is more than one feature and one wants to give a different weight to the loss of a specific feature. This has nothing to do with the weights of each class. I just realized this is not explained anywhere in the docs so we will have to add it.

`class_weights` on the other hand does exactly what you are looking for, but it is available currently only for categorical features. So if you want to use it just set your feature to categorical, there will be 3 classes UNK, True and False and the rest will work fine even if the loss and the decoder will be the ones for multiclass instead. It's a temporary workaround. What actually needs to happen is that we add a weighted version of binary cross entropy and that users can specify weights for the positive and negative class like they do for the categorical case. So I consider this a feature request.

**Comment by iEvidently** [comment]
Thanks @w4nderlust for clarifying that, I will do as suggested. Change the outcome to category and use class_weights.

**Comment by mangleddata** [comment]
One issue I see w/ adding class_weights is, the mapping doesn't seem to follow any order. Each data file may end up with a different str2idx mapping in the train_set_metadata.json. It should probably be a key:value pair instead, I think. Or is there a way to fix the sort order somehow ?

**Comment by w4nderlust** [comment]
@mangleddata the mapping is obtained by sorting the classes by frequency and adding a UNK class at the beginning, so: `{"UNK: 0, most_frequent_class: 1, second_most_frequent_class: 2, ...}`.

I see your point that the class weights could / should be provided as a dictionary, it makes sense, because at the moment you need to know the mapping beforehand in order to provide the weights. This can be an enhancement, would be great if someone wanted to contribute it, I can give precise instructions on hot to do it.
(to help my memory) **improvement: class_weights provided as a dictionary**

At the moment what I suggest to do is to preprocess the data first using `data/preprocessing.py`, that creates the JSON file and then look at the ordering of the classes in the JSON file and provide class weights accordingly.

**Comment by w4nderlust** [comment]
So, quick update: I added the option to provide class_weights as a dictionary (see the commit above) and I also updated the user guide about it and also about a `positive_class_weight` parameter that is available for binary features. The changes are not yet reflected on the website as it has not yet been rebuilt, but will be reflected soon, but you can see the parameter here: https://github.com/uber/ludwig/blob/master/ludwig/features/binary_feature.py#L183
This should solve all issues and requests, so I'm closing it, let me know if there are other requests of if you encounter problems.

**Comment by iEvidently** [comment]
@w4nderlust Thanks for helping resolve this.

**Comment by mangleddata** [comment]
+1

Thank you for adding the option quickly.
