### ISSUE TITLE
ludwig w/tensorflow 1.15 and python 3.7.6 dies looking for GLIBC_2.23

### ISSUE THREAD

**Issue by slederman** [uber/ludwig#624]
I've git a conda environment in which I'm trying to get ludwig to run. I've got tensorflow 1.15 and python 3.7.6 in that environment. When I run ludwig I get this error:

ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /ai/anaconda/envs/ludwig/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

I don't see a way to get the requested version of glibc to install in the environment via conda or via pip.

**Comment by w4nderlust** [comment]
It's a TensorFlow installation issue, not a ludwig one.
This may help you https://github.com/tensorflow/tensorflow/issues/28660

**Comment by slederman** [comment]
The combination of python 3.6.8 and tensorflow 1.13.1 works with ludwig. Thanks for your help!

It would be really helpful if there were a compatibility matrix to help folks to know which combinations of versions of tensorflow/python/ludwig work together. In particular, I learned the hard way that tensorflow 2.0 doesn't work with ludwig.

**Comment by w4nderlust** [comment]
Well it's in the requirements :)

**Comment by slederman** [comment]
Ah, I do see this now: https://github.com/uber/ludwig/blob/master/requirements.txt
It would be helpful to include the support version of Python as well as that was part of the issue.

Thanks again for your help. Not meaning to be critical. Just hoping to save others some grief.

**Comment by w4nderlust** [comment]
> Ah, I do see this now: https://github.com/uber/ludwig/blob/master/requirements.txt
> It would be helpful to include the supported version of Python as well as that was part of the issue.
> 
> Thanks again for your help. Not meaning to be critical. Just hoping to save others some grief.

Sure no worries. I guess the point is that it's difficult to keep track of all combinations. For instance I work with python 3.5 usually (for compatibility) and have never seen this specific issue, while in other case I had Ludwig run fine on 3.4 and 3.5. Anyway ,if thigs like this happen consistently maybe I can add rules to the CI tool to deal with them, what do you think?

**Comment by slederman** [comment]
Coding in rules sounds like a great idea to me. If you as primary developer have difficulty tracking all the combinations then ludwig users will have even more trouble. In particular, if TF 2 is not supported (I found this out the hard way) it would be nice to code in a check for that. Thanks again for all of your hard work. Ludwig is very impressive software.

**Comment by w4nderlust** [comment]
@slederman thanks you! A little clarification: when you install Ludwig the correct version of TF is installed. I don't know how you ended up with TF2, but if you run just `pip install ludwig` it will install the right TF.
