### ISSUE TITLE
Tensorflow 1.15.2 is built with separate cpu-gpu packages

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#633]
Requirements were bumped to 1.15.2, but in 1.15.2 (and upwards most likely) cpu and gpu packages were separated once again, due to the discovery of an unsupported workaround to deploy packages on Pypi. Please refer to: https://github.com/tensorflow/tensorflow/issues/36347

You should decide whether to require a previous version, or whether to reinclude instructions to choose between tensorflow and tensorflow-gpu packages as in old fashioned ludwig setup info by first uninstalling tensorflow and then reinstalling tensorflow-gpu==1.15.2

**Comment by w4nderlust** [comment]
Oh my, I though i was done with this... :(

**Comment by carlogrisetti** [comment]
Heh... They basically messed up with the way they generated the packages.
If I understood correctly, however, tensorflow-gpu should also cover cpu usage. It might be worth a test. They were renaming tensorflow to tensorflow-cpu and tensorflow-gpu to tensorflow (so this should be the one now supporting any architecture)

**Comment by carlogrisetti** [comment]
In the meantime, I can confirm that tensorflow-gpu is correctly working on a non-gpu machine.
PR #635 might be modified to always have tensorflow-gpu in the requirements since it should handle both gpu and non-gpu environments.
I could only test that on a windows machine (both GPU and non-GPU), so I can't vouch for other OSs

**Comment by w4nderlust** [comment]
I tested it by specifying `CUDA_VISIBLE_DEVICES=''` and it works reverting to CPU computation. i'm not aware of other drawbacks of using the GPU version, so i updated the PR to reflect this.

**Comment by w4nderlust** [comment]
Merged #635 which fixes this.
