### ISSUE TITLE
MultiTask learning weights

### ISSUE THREAD

**Issue by mangleddata** [uber/ludwig#641]
Are there knobs available to adjust the bias of multitask learning ? For example, if I have a mix of categorical, binary and numerical outputs and want to set different biases so that the loss of one feature doesn't dominate (for example, numerical loss over others). Hope this makes sense. If not, please correct my understanding. 

The reason I ask is, if I train just the binary feature alone, my runs go on for 40 epoch before being early stopped. But if I add more output features, they quickly get stopped out (which my suspicion was due to dominant numerical loss)

**Comment by w4nderlust** [comment]
it is not specified in the docs, will update them, but there is a `weight` parameter to be used inside the `loss` section of each output feature. The loss is computed as a weighted sum of all the losses and the weight parameter determines the weight associated with the loss of each output feature.

Regarding early stopping, it also depends on the field and measure you are using for validation. You cna look at the details in the training section of the user guide. https://uber.github.io/ludwig/user_guide/#training

Let me know if you have further questions. For now will mark this as documentation issue to be fixed.

**Comment by w4nderlust** [comment]
I added a multi-task learning section in the user Guide source markdown file. See the commit referred above to look at the contents. It will be reflected in documentation website next it will be updated.

**Comment by mangleddata** [comment]
Thank you! I'll give it a try. Multi-task learning is a bit of golden nugget that needs more exposure. The doc changes makes it clear.
