### ISSUE TITLE
Bug with weather example

### ISSUE THREAD

**Issue by rogeriosmorais** [uber/ludwig#649]
Hi guys, I know this is very small and probably just a typo, but the example given in https://uber.github.io/ludwig/examples/#time-series-forecasting-weather-data-example, in the pre-processing portion of the provided code there's SPLIT in 3 different points, but that doesn't run as it is. I suppose it was meant to create a new column in the dataframe, if that's the case it should be 'SPLIT', not SPLIT. I was able to run it without any problems after making that small change. Just suggestion to update the documentation.

**Comment by w4nderlust** [comment]
Thanks for noticing! `SPLIT` is a constant in Ludwig that is `SPLIT = 'split'`. So I'll change to either import the constant or replace with the string. Thank you.
