### ISSUE TITLE
Missing reuters-allcats.csv in the Example page

### ISSUE THREAD

**Issue by serv** [uber/ludwig#65]
I cannot find `reuters-allcats.csv` file link in https://uber.github.io/ludwig/examples/ .

I think the Example page should contain this file, so a user can actually follow the example to try Ludwig out.

Thanks for open sourcing this project.

**Comment by serv** [comment]
It looks like I raised an issue that is similar to https://github.com/uber/ludwig/issues/40 .
If #40 is solved, please close this issue.

**Comment by w4nderlust** [comment]
Thanks for sending this issue.
Unfortunately that dataset was a reformatted file of the Reuters dataset, but as it has its own license we ended up not including it.
I will replace it with something that looks like that and has no strings attached.

**Comment by lee-geyer** [comment]
I found a link to a csv file with the same name here: 

http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/

I downloaded this file and used to to test the ludwig example and the program ran fine.  I did not get the exact same result, so it might be a different subset, but it allows you to play with ludwig using this example.

**Comment by w4nderlust** [comment]
Thanks for pointing it out @lee-geyer ! I may add the link to the example and that should work around the issue in including the dataset in our repo.

**Comment by michalmar** [comment]
> I found a link to a csv file with the same name here:
> 
> http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/
> 
> I downloaded this file and used to to test the ludwig example and the program ran fine. I did not get the exact same result, so it might be a different subset, but it allows you to play with ludwig using this example.

Which file did you take, please? I ended up with couple of texts, and sgm files...

**Comment by lee-geyer** [comment]
Reuters-allcat-6.zip

Sent from my iPhone

On Feb 17, 2019, at 3:46 PM, michalmar <notifications@github.com<mailto:notifications@github.com>> wrote:


I found a link to a csv file with the same name here:

http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/

I downloaded this file and used to to test the ludwig example and the program ran fine. I did not get the exact same result, so it might be a different subset, but it allows you to play with ludwig using this example.

Which file did you take, please? I ended up with couple of texts, and sgm files...

**Comment by michalmar** [comment]
> > I found a link to a csv file with the same name here:
> > http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/
> > I downloaded this file and used to to test the ludwig example and the program ran fine. I did not get the exact same result, so it might be a different subset, but it allows you to play with ludwig using this example.
> 
> Which file did you take, please? I ended up with couple of texts, and sgm files...

I've found that already (reuters-allcat-6.zip)

**Comment by w4nderlust** [comment]
This commit: https://github.com/uber/ludwig/commit/29298f0795297fb9fb5ec2b5263af1969022f816 solves it.
