### ISSUE TITLE
Unable to install Ludwig on Macbook pro using pip

### ISSUE THREAD

**Issue by abhiravg** [uber/ludwig#658]
**Describe the bug**
Unable to install Ludwig on Macbook pro 2019. Error:
`ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15.2 (from ludwig) (from versions: none)`
`ERROR: No matching distribution found for tensorflow-gpu==1.15.2 (from ludwig)`

**To Reproduce**
1. `python3 -m venv /path/to/venv`
2. `source /path/venv/bin/activate`
3. `pip install ludwig`

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
Clean installation.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Version 10.15.3
- Python version 3.7.3
- Pip version 20.0.2
-Setuptools version 46.0.0
- Ludwig version N/A

**Additional context**

**Comment by abhiravg** [comment]
tensorflow-gpu is not available for macOS and should not be a hard requirement for ludwig.

**Comment by abhiravg** [comment]
Solution: Build from source - replace `tensorflow-gpu` with `tensorflow` in requirements.txt

**Comment by w4nderlust** [comment]
@abhiravg thank you for let us know. People in the TF1 brunch made a bit of a mess, first removing the gpu version and merging it into the regular one then reintroducing it and telling that the gpu version also includes the non gpu setting, but now you are telling me thegpu version on mac can-t be installed...
This is unfortunate, I can try to fix it, although the next release of Ludwig will be base on TF2 that should not have this problem. If it going to take a long time i may do an intermediate small fix release to solve this. Anyway, thanks for letting us know.

**Comment by w4nderlust** [comment]
I actuall ydecided to address it immediately, now tensorflow CPU is the default, again :)

**Comment by ifokeev** [comment]
@w4nderlust the best way for @abhiravg is using a docker container. I use `ludwig` with `tensorflow-gpu` on macos without any problems

**Comment by w4nderlust** [comment]
@ifokeev thanks for providing an alternative solution. Anyway, I want Ludwig to be natively installed at least on Linux and Mac anyway, so I reverted back to non GPU default. The next version will use TF2 so the will not be any more problems about this.
