### ISSUE TITLE
Retraining a trained model with ludwig==0.2.2.3 results into key errors.

### ISSUE THREAD

**Issue by xirect** [uber/ludwig#665]
**Describe the bug**
Retraining a trained model with ludwig==0.2.2.3 results into key errors. Downgrading to ludwig==0.2.2 solved the problem

File "/usr/local/lib/python3.6/site-packages/ludwig/models/model.py", line 442, in train
[of['name'] for of in output_features] + ['combined']
ValueError: The specificed validation_field combined is not valid.Available ones are: ['class', 'combined']

**To Reproduce**
1. Train a simple default model
2. Save the model
3. Load the model with the python api
4. Train the model
5. Receive error

Error occurs even when following the basic yaml files and tutorial on the Ludwig Examples.

**Expected behavior**
When training the model it should not result in key-error for.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 19.10
- Python version 3.7.1
- Ludwig version 0.2.2.3

**Additional context**

**Comment by w4nderlust** [comment]
Already solved by the last commit: https://github.com/uber/ludwig/commit/49648aac505f5d6b584aabec531c254d27ec5e8e
You can install from master but there will be a 0.2.2.4 release incorporating it soon.

**Comment by w4nderlust** [comment]
Here's the link to the new release that fixes the problem: https://github.com/uber/ludwig/releases/tag/v0.2.2.4
it's also already on [Pypi](https://pypi.org/project/ludwig/) ;)
