### ISSUE TITLE
ludwig serve fails to install

### ISSUE THREAD

**Issue by orthodoc** [uber/ludwig#666]
`ludwig` serve needs the installation of `fastapi`.

`fastapi` has a hard requirement of `python 3.6`

The following commands
```python
pip install ludwig[serve] 
pip install ludwig[full]
```
will succeed only if `python 3.6` is installed.

Possibly related to #473

**Comment by w4nderlust** [comment]
Thanks for sending this. Judging from this https://pypi.org/project/fastapi/ any version above 3.6 works with fastapi. 3.6+ is anyway what we are testing in the CI anyway, from next version will make it an explicit requirement.
