### ISSUE TITLE
How to get the visualization  result?

### ISSUE THREAD

**Issue by MrRace** [uber/ludwig#69]
After running `ludwig visualize --visualization learning_curves -ts results/experiment_run_4/training_statistics.json`, it returns empty. Where to get the visualization results?Is it saved as a image in somewhere?

**Comment by gridcellcoder** [comment]
According to the [docs](https://uber.github.io/ludwig/user_guide/#visualize) it should be `-tes` not `-ts` and in the [README](https://github.com/uber/ludwig/blob/master/README.md) it is `--training_stats` when it should be  `--training_statistics` results/training_stats.json

try with `-tes` someone also needs to correct the README

**Comment by w4nderlust** [comment]
Actually, I may have inverted `tes` and `trs`. Will change that. Anyway, i guess the point is a different one: when you run the visualize commands, a window is opened and you can save the image from there, the motivation being that in some cases, when you have a lot of classes for instance, graphs need to be resized a bit to be readable before saving them. If no window is opening, then please report on your configuration and please make a reproducible example so that I can look into it.

**Comment by davideprimiceri** [comment]
Hi, I have the same problem working on google colab, in fact after running `!ludwig visualize --visualization learning_curves --training_statistics /content/results/experiment_run_0/training_statistics.json` I do not get the visualization, but the cell is empty

**Comment by w4nderlust** [comment]
@davideprimiceri can you please share a colab that reproduces the issue?

**Comment by davideprimiceri** [comment]
Yes: https://colab.research.google.com/drive/1XamjWtR7R5c44tieSDMLPRljDS2p3Cg-

**Comment by w4nderlust** [comment]
Oh so you are running the visualize command  from the colab, you are not calling the functions themselves. I'm not sure how that would work, as if you call matplotlib functions by running the proces, they are unlikely to be piped into the cell output. Do you have experience in doing something like this (calling scripts that open mtplotlib windows and having them rendered in colab cells)?

This is making me think that probably I should add an option to `visualize` that allows for saving the images to disk instead of opening windows. That would solve your problem as you would be able to open the saved images in a cell, and also @MrRace 's problem (if if I don't know yet what his problem was in detail).

**Comment by dshlai** [comment]
Hi, since **visualize** is using matplotlib internally, wouldn’t using inline plot in Colab or Juypter also work?

**Comment by w4nderlust** [comment]
@dshlai I don't have enough experience with either to be sure about it. Will look into it and try to figure it out.

**Comment by dsmmr** [comment]
I also find the visualize command a bit bulky and non-intuitive. A more "intelligent" variant would be nice, where the visualize command is just called with the results folder of the experiment and returned is a choice which plots can be made after possible results files were found by ludwig. Would this be feasible?

For example in this case I do not know if I used it wrong or another file is expected:

```
(test) D:\ludwig\titanic\results\experiment_run_1>ludwig visualize --visualization confusion_matrix --predictions prediction_statistics.json
No prediction_statistics provided

(test) D:\ludwig\titanic\results\experiment_run_1>dir
14.02.2019  14:47    <DIR>          .
14.02.2019  14:47    <DIR>          ..
14.02.2019  14:35             5.768 description.json
14.02.2019  14:47    <DIR>          model
14.02.2019  14:47            20.401 prediction_statistics.json
14.02.2019  14:47             1.373 Survived_predictions.csv
14.02.2019  14:47               308 Survived_predictions.npy
14.02.2019  14:47             2.309 Survived_probabilities.csv
14.02.2019  14:47               848 Survived_probabilities.npy
14.02.2019  14:47            88.804 training_statistics.json
```

**Comment by w4nderlust** [comment]
@dsmmr you should provide `--prediction_statistics` not `--predictions`.

**Comment by w4nderlust** [comment]
@MrRace can you please provide details about your environment and a reproducible example, otherwise it's really difficult for us to help you.

**Comment by MrRace** [comment]
> @MrRace can you please provide details about your environment and a reproducible example, otherwise it's really difficult for us to help you.

What environment?I just install the packages in requirements.txt. Run `ludwig visualize --visualization.......` these is no any window opened. Therefore what commands should I use to get the environment you mentioned?

**Comment by MrRace** [comment]
> According to the [docs](https://uber.github.io/ludwig/user_guide/#visualize) it should be `-tes` not `-ts` and in the [README](https://github.com/uber/ludwig/blob/master/README.md) it is `--training_stats` when it should be `--training_statistics` results/training_stats.json
> 
> try with `-tes` someone also needs to correct the README

I use `ludwig visualize --help` to check the arguments, and it do not have a argument like  `-tes` . It exist difference between Document and Command.

**Comment by w4nderlust** [comment]
@MrRace, I meant what operative system, what version of python and so on. I'm trying to find a way to replicate your issue to fix it. Can you attach your `training_statistics.json` or send it to me privately?

**Comment by MrRace** [comment]
@w4nderlust ,Here is my system message：`Linux version 4.15.0-45-generic (buildd@lcy01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10))`,and I use python 3.5. The attachment is the file I use to do the visualization.


[training_statistics.zip](https://github.com/uber/ludwig/files/2867644/training_statistics.zip)

**Comment by w4nderlust** [comment]
Looked at your training statistics. There seem to be nothing wrong with it. On the same configuration i was able to obtain a visualization of the learning curves. I don't actually know what is going wrong here. You don't get any error, the program closes correctly, but you just don't see the window, right?
Maybe one thing you can try is to update matplotlib in your virtualenv to the latest version and see if that solves the issue, but it's kinda of a hail mary, without an error I have a hard time replicating the problem and figuring out a solution. If also this doesn't work, I would suggest you just wait for the addition of an `--output_directory` parameter to `visualize` which is in the list of future enhancement. Or if you actually want, you can try to contribute, it should be pretty straightforward.

**Comment by dehdari** [comment]
Similar problem for me on MacOS, where nothing was appearing.  It turns out that my Matplotlib backend was displaying the plots in the background, behind every other window on my desktop.

Still, the ability to save images to disk would be nice (and more plots automatically in Tensorboard).

**Comment by w4nderlust** [comment]
@dehdari from the window that opens you can save them (there's a button at the bottom). The rationale to have them in the window is that before saving you can resize (which is useful if you have many classes or many models to compare, otherwise labels would overlap and the plot not be readable). Anyway, will add the functionality ho save the plots directly.
Which other plots would you be interested to have in the TensorBoard? Consider it is only used to keep track of measures at the batch level during training.

**Comment by gobzer** [comment]
I hacked the [ludwig/utils/visualization_utils.py](https://github.com/uber/ludwig/blob/master/ludwig/utils/visualization_utils.py) to save the graphs.
Before each
`plt.show()`
I put a
`plt.savefig(title+'.png')`
It's stupid, but works
saves the graphs in current directory

**Comment by w4nderlust** [comment]
#gobzer it's not stupid, it's the way it should be done :)
I would be really glad if you could add a `save_figures`, `save_path` and `figure_extention` parameters to the `visualize.py` module command line interface and pass those parameters through to compose the path `savefig` is going to save the file to, and finally make a PR. it would be much appreciated and it would be was I was planning to doanyway.

**Comment by carlogrisetti** [comment]
In the meantime, pull request #332 should fix the naming mismatch in the parameters, both in the arguments passed to ludwig visualize, and in the web user guide

**Comment by w4nderlust** [comment]
#403 addresses this.

**Comment by newbiepawel** [comment]
This worked for me:

ludwig.visualize.learning_curves(
  train_stats,
  field = True
)

**Comment by w4nderlust** [comment]
Yes we added those new visualize functions in v0.2 explicitly for this, glad they work!
the field parameter should be the name of the output feature you want to visualize the learning curves of. In some visualization functions it is optional so also if you specify `True` it works, but others actually require it.

**Comment by muhammad-yasir** [comment]
I tried to generate confusion matrix for the prediction_statistics by using following command. 

ludwig visualize --visualization confusion_matrix  --prediction_statistics ./results/experiment_run_0/prediction_statistics.json
However, I got the following error
/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/yasirmuhammad/anaconda3/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/cli.py", line 94, in main
    CLI()
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/cli.py", line 60, in __init__
    getattr(self, args.command)()
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/cli.py", line 80, in visualize
    visualize.cli(sys.argv[2:])
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/visualize.py", line 1826, in cli
    confusion_matrix(**vars(args))
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/visualize.py", line 1463, in confusion_matrix
    metadata = load_json(ground_truth_metadata)
  File "/Users/yasirmuhammad/anaconda3/lib/python3.6/site-packages/ludwig/utils/data_utils.py", line 66, in load_json
    with open(data_fp, 'r') as input_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Could you please help me how to sort out the issue?

**Comment by jimthompson5802** [comment]
@muhammad-yasir   Let me see if I can help. 

One thing I noticed in the information you provided is that the command arguments do not appear to be correct.  Starting in v0.3 breaking changes occurred in cli arguments.  Here is the [current documentation](https://ludwig-ai.github.io/ludwig-docs/user_guide/#confusion-matrix) for the `confusion_matrix` visualization.

Here is an example of the command for creating a confusion matrix.  This example uses Ludwig's `examples/mnist`.  I'm using `ludwig_version: '0.3.2'`
```
ludwig visualize \
  --visualization confusion_matrix \
  --output_feature label \
  --ground_truth_metadata results/experiment_run_0/model/training_set_metadata.json \
  --output_directory visualizations \
  --file_format png \
  --test_statistics ./results/experiment_run_0/test_statistics.json
```
Here are the outputs from the above command:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1425269/108601687-c5abd600-736b-11eb-88e7-2b283f3cedcc.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1425269/108601693-d2302e80-736b-11eb-93b7-57b6cfd452ca.png">

If this does not solve the issue, then I'll need more information.  Please provide:
* Version of the OS
* Version of Ludwig, ensure the version is v0.3 or later.
* Ludwig command that trained the model

Let me know if this helped.

**Comment by muhammad-yasir** [comment]
Thanks Jim. It worked. I was using ludwig==0.1.12. I upgraded to the recent
one and it worked.

**Comment by jimthompson5802** [comment]
@muhammad-yasir   
Great to hear that the advice solved the issue.

If you encounter other problems, feel free to open new issues so we can help you.
