### ISSUE TITLE
TF2 porting: ImportError: cannot import name 'flatten'

### ISSUE THREAD

**Issue by jimthompson5802** [uber/ludwig#692]
**Describe the bug**
@w4nderlust 
I'm using this issue to report a problem I encountered, outside of the context of a PR.  Before  starting my next task, I ran the unit test `tests/integration_tests/test_simple_features.py`  This resulted in this error:
``` 
_____________________________________ ERROR collecting tests/integration_tests/test_simple_features.py _____________________________________
ImportError while importing test module '/opt/project/tests/integration_tests/test_simple_features.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/integration_tests/test_simple_features.py:24: in <module>
    from ludwig.experiment import full_experiment
ludwig/experiment.py:32: in <module>
    from ludwig.data.postprocessing import postprocess
ludwig/data/postprocessing.py:20: in <module>
    from ludwig.features.feature_registries import output_type_registry
ludwig/features/feature_registries.py:39: in <module>
    from ludwig.features.image_feature import ImageBaseFeature
ludwig/features/image_feature.py:30: in <module>
    from ludwig.models.modules.image_encoders import ResNetEncoder
ludwig/models/modules/image_encoders.py:20: in <module>
    from ludwig.models.modules.convolutional_modules import flatten, ConvStack2D, \
E   ImportError: cannot import name 'flatten'
```

**To Reproduce**
1.  Position at this commit https://github.com/uber/ludwig/pull/682/commits/d76ec6c5fa7fc839882e5d8c5edf2a54650516b1
2. `pytest tests/integration_tests/test_simple_feature.py`

**Expected behavior**
Successfully execution of the unit test

**Screenshots**
N/A

**Environment (please complete the following information):**
- Python version
- Ludwig version in-progress version for conversion to TF2

**Additional context**
This commit https://github.com/uber/ludwig/pull/682/commits/9342276c9504bd211b2c441b18650050857aab83 removed the `flatten()` function.  I could not locate in the code base the new location for `flatten()` (and the other functions).

**Comment by w4nderlust** [comment]
I must have removed even if it was used buring cleanup. we can use `tf.keras.layers.Flatten` instead.
