### ISSUE TITLE
Visualization API AssertionError

### ISSUE THREAD

**Issue by donfour10** [uber/ludwig#694]
**Describe the bug**
I try to create the compare_performance chart with the visualization API and it throws an AssertionError.

**To Reproduce**
`from ludwig.visualize import compare_performance
`

`stats = [{'combined': {'accuracy': 0.0, 'loss': 21.042979235191247}, 'target_category': {'jaccard': 0.14934778770208643, 'loss': 21.042979235191247}}, {'combined': {'accuracy': 0.0, 'loss': 20.444052153835703}, 'target_category': {'jaccard': 0.1627610707413676, 'loss': 20.444052153835703}}]
`

`model_names = ['Model1', 'Model2']
`

`compare_performance(
    test_stats_per_model=stats,
    output_feature_name='target_category',
    model_names=model_names
)`

That's the Error:

![image](https://user-images.githubusercontent.com/55831555/79859484-5e329c00-83d1-11ea-8cf9-6206fa9c9427.png)

It also doesn't change when I set a output_directory for the method.

**Expected behavior**
Show chart with the comparisation.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 19.10
- Python version 3.7.5
- Ludwig version 0.2.1

**Comment by w4nderlust** [comment]
@donfour10 thank you for letting us know. That visualization was originally implemented for categorical output features, but yours is a set output feature. Let me fix the doce to work with any output feature type. Will keep you posted.

**Comment by w4nderlust** [comment]
The most recent commit fixes this. please install from master and confirm it this soves your problem.
To install from master:
`pip uninstall ludwig` and then`pip install git+http://github.com/uber/ludwig.git`

**Comment by donfour10** [comment]
thanks for the quickly fix!
