### ISSUE TITLE
BERT Encoder - Training session killed

### ISSUE THREAD

**Issue by donfour10** [uber/ludwig#703]
**Describe the bug**
Everytime I try to run a training with a BERT Ecoder, the process killed after a few minutes before the first epoch of training started. 

**To Reproduce**
My dataset consists of text as input and a set of categories as output. (If you need a sample of data, contact me and I see if I can provide something to you. But it's defenetly not the data because every other experiment works with the same data ;)! )

Model_definition:
![image](https://user-images.githubusercontent.com/55831555/80529988-a5ec9100-8998-11ea-8500-6cbc1b356237.png)

cmd: ludwig train --data_csv /analyst/ludwig_experiments/ludwig_training_with_sd.csv -mdf /analyst/model_definition.yaml --output_directory /analyst/ludwig_experiments/results3 --experiment_name bert
or 
I also tried it with the API Method `LudwigModel.train` but the same happens here.

bert model: https://storage.googleapis.com/bert_models/2019_05_30/wwm_uncased_L-24_H-1024_A-16.zip

What happens:
![image](https://user-images.githubusercontent.com/55831555/80531215-87879500-899a-11ea-8722-06a8ee1a6af2.png)
(with the API method this is not displayed)
few minutes later -> 
![image](https://user-images.githubusercontent.com/55831555/80531319-b6057000-899a-11ea-825b-d33a4bef0961.png)

**Expected behavior**
Training of model executes.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 19.01
- Python version 3.7.5
- Ludwig version 0.2.1

**Additional context**
I would be very grateful for ideas!

**Comment by w4nderlust** [comment]
I suspect the reason is an out of memory error. Can you try with a small batch size, like 1? If that works you can increase it until you get the same error which will tell you how big of a batch size you can fir in ram /vram

**Comment by donfour10** [comment]
Your suspection was correct. Thank you very much!
