### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.preprocessing.text' has no attribute 'text_dataset_from_directory'

### ISSUE THREAD

**Issue by Harish2104** [uber/ludwig#713]
**Describe the bug**
Unable to load the function text_dataset_from_directory. I have installed tensorflow 2.2 and keras 

**Expected behavior**
Not able to load the function.  
**Screenshots**
![image](https://user-images.githubusercontent.com/7239271/82784274-cca9c480-9e7d-11ea-92dd-566c7896bc9e.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - Version [e.g. 22] 10
- Python version - 3.8.2
- Ludwig version -  Not installed

**Additional context**

**Comment by w4nderlust** [comment]
You should post this in the Keras repo, not her, this has nothingto do with Ludwig.
