### ISSUE TITLE
Do not re-load pre-trained embeddings for each feature if multiple input features use the same one

### ISSUE THREAD

**Issue by jmizgajski** [uber/ludwig#720]
**Is your feature request related to a problem? Please describe.**

When there are multiple input_features using the same pre-trained embedding ludwig loads the file from scratch for each feature which takes considerable time. 

**Describe the use case**

Speed up training start-up time when there are multiple text features using the same pre-trained embedding.

**Describe the solution you'd like**

Cache the loading of the embeddings from file (by default or if you want to preserve memory make it optional). 

**Describe alternatives you've considered**

speeding up the load time for embeddings so repeating the loading is negligible.

**Comment by w4nderlust** [comment]
This is a good point. Let's discuss how to solve this in the PR you opened.

**Comment by w4nderlust** [comment]
This has been merged ;)
