### ISSUE TITLE
From ludwig import LudwigModel

### ISSUE THREAD

**Issue by muhammad-yasir** [uber/ludwig#731]
**Describe the bug**
I created a virtualenv first and installed ludwig using `pip install ludwig` command. The installation showed that it is installed successfully. However, when I ran the command `from ludwig import LudwigModel` it throws `ModuleNotFoundError: No module named 'ludwig'`. 
When I ran the same import command directly from the command prompt (by enabling virtual env), it throws an error: `from can't read /var/mail/ludwig` error. 
I checked the installed libraries for virtual env and it showed that ludwig 0.2.2.7 is installed. 

I also tried to install the ludwig from github directly by `using pip install git+https://github.com/uber/ludwig`. However, it throws an error message ERROR: Command errored out with exit status 1: `git clone -q https://github.com/uber/ludwig /private/var/folders/t_/blb5k35x34j54cclfnfj82qm0000gn/T/pip-req-build-dgrui0kq Check the logs for full command output.`

Could you please help in fixing the issue
**To Reproduce**

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
Run without error.

**Screenshots**

**Environment (please complete the following information):**
- Python version
- Ludwig version

**Additional context**

**Comment by w4nderlust** [comment]
As shown in the documentation https://ludwig-ai.github.io/ludwig-docs/getting_started/#programmatic-api the corret import is
`from ludwig.api import LudwigModel`.

**Comment by befman123** [comment]
Same here except I used from ludwig.api import LudwigModel and no bueno. im also using version 0.9.1. I don't know why this is happening because sometimes it works sometimes it doesn't
