### ISSUE TITLE
Category output feature question

### ISSUE THREAD

**Issue by w4nderlust** [uber/ludwig#743]
I was doing a text classification project, where I have created the sentence vectors in a different algorithm. Now when I am training the same and giving output feature as mentioned in the example:

name: level1
type: category

The sample output column is here:
0           cancellation
1    query_not_specified
2           cancellation
3           order_status
4    query_not_specified
5           order_status
6           cancellation
7    query_not_specified
8           order_status
9           cancellation

I am getting the error: 
could not convert string to float: 'cancellation'

Please help me out!

_Originally posted by @rajatjain2310 in https://github.com/uber/ludwig/issues/391#issuecomment-645841718_

**Comment by w4nderlust** [comment]
@rajatjain2310  please be more precise in describing your problem. What you are describing shouldn't lead to any error.
Please provide a sample fo the data, the model definition and the command you used for training. Alternatively, please provide the code you are using.

**Comment by rajatjain2310** [comment]
Piero,

I figured out the problem myself. I was trying to give vector input in a
dataframe rather than the solution prescribed in your docs.
You can please go ahead and close the thread.
