### ISSUE TITLE
version as a sanity check for ludwig

### ISSUE THREAD

**Issue by kanishk16** [uber/ludwig#748]
### **Is your feature request related to a problem? Please describe.**
It is sometimes seen (#168, #731) users face an ambiguity to know if ludwig is installed properly or not.
 
### **Describe the use case**
Sanity check for ludwig being installed as intended. Moreover, this would become important when ludwig further scales up and starts being developed in full swing.

### **Describe the solution you'd like**
Something on similar lines as followed by tensorflow, pytorch and even fastai 
```
import ludwig
ludwig.__version__
```

### **Describe alternatives you've considered**
We can check for the version installed from `pip list` and have a sanity check using `from ludwig.api import LudwigModel` as described in the documentation

**Comment by w4nderlust** [comment]
Ludwig package already has a `__version__`.
