### ISSUE TITLE
Numerical outputs

### ISSUE THREAD

**Issue by tboneai** [uber/ludwig#751]
**Describe the bug**
I am getting mixed outputs in my files and I am not sure why. I have added and removed multiple features trying to track down the cause with no luck. Some of the results I receive are numeric, some are not, and some files just repeat the same result. 
Changing the inputs to category resolves the issue and I am fairly certain using sequential inputs work as well (tested previously).

I do not understand the difference between the results in runs 19 & 20. I would expect the files created in run 20 to mimic the previous files...i.e. run 19 accident_output returns mixed results but run 20 accident_output are all numeric. 

I am attaching the results from three experiments. 
First run (19) is a basic numeric to numeric and the data file was created by copying and pasting the data into a new csv file. 
Second run (20) are same files with no changes except for using the hdf files created by run19. I didn't even closed the command prompt. 
Third run I changed the inputs to category and received all numeric outputs as expected. (new hdf files)

Run 19
accident_output_predictions - mixed outputs beginning in Col A, Line 9
analyst_output_predictions - File repeats 4.89e-36
application_output_predictions  - mixed results
art_output_predictions - all numerics as desired
concept_output_predictions - mixed

Run 20
accident_output_predictions - all numerical as desired
analyst_output_predictions - File repeats 4.20e-13
application_output_predictions  - mixed results
art_output_predictions - numerical but repeats -0.00099 
concept_output_predictions - numerical as desired

**To Reproduce**
1. Load predict_syn3.csv and mdf_syn_numerical.yaml  file provided in link
2. Run experiment command
3. finish 
4. Run experiment command
5. Finish
6. Compare results between both runs

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

I have included everything I could think of from all the runs in a zipped file on onedrive. Let me know if you have any issues accessing the files since its my first time using it for guests. 

https://1drv.ms/u/s!AuPln-jFNoUohzfn-jK--mBwHIuj?e=1MNwxM

**Expected behavior**

Expect all results to be consistent and numerical

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 
 - Version [e.g. 22] build 18363.900
- Python version 3.6
- Ludwig version 0.2.2.2
- Running in Conda environment
Package              Version
-------------------- -------------------
absl-py              0.9.0
astor                0.8.0
certifi              2020.4.5.2
Cython               0.29.14
gast                 0.2.2
google-pasta         0.1.7
grpcio               1.16.1
h5py                 2.9.0
joblib               0.14.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
ludwig               0.2.2.7
Markdown             3.1.1
mkl-fft              1.0.14
mkl-random           1.1.0
mkl-service          2.3.0
numpy                1.17.2
opt-einsum           3.1.0
pandas               0.25.3
pip                  19.3.1
protobuf             3.9.2
pyreadline           2.1
python-dateutil      2.8.1
pytz                 2019.3
PyYAML               5.1.2
scikit-learn         0.21.3
scipy                1.3.1
setuptools           41.6.0.post20191030
six                  1.12.0
tabulate             0.8.5
tensorboard          1.15.0
tensorflow-estimator 1.15.1
tensorflow-gpu       1.15.3
termcolor            1.1.0
tqdm                 4.37.0
webencodings         0.5.1
Werkzeug             0.16.0
wheel                0.33.6
wincertstore         0.2
wrapt                1.11.2

**Additional context**

**Comment by w4nderlust** [comment]
This is indeed pretty weird, would want to llok into it, but we are actually in the midst of porting to TF2, would you mind testing if you get the same problems if you run with the code in the `tf2_porting` branch? Because if the ported code solves the problem as i suspect I may not spend time trying to figure out this problem in the TF1 code.

**Comment by tboneai** [comment]
I’ll check it out. Its no rush. This is just a learning project for me. 

Sent from Yahoo Mail for iPhone


On Sunday, July 5, 2020, 2:36 AM, Piero Molino <notifications@github.com> wrote:




This is indeed pretty weird, would want to llok into it, but we are actually in the midst of porting to TF2, would you mind testing if you get the same problems if you run with the code in the tf2_porting branch? Because if the ported code solves the problem as i suspect I may not spend time trying to figure out this problem in the TF1 code.

**Comment by w4nderlust** [comment]
Update: the code in master now is fully TF2, @tboneai would you be so kind to check if the error persists?

**Comment by tboneai** [comment]
I'm pretty busy this week but I start on this next Monday
    On Tuesday, September 8, 2020, 08:49:43 PM EDT, Piero Molino <notifications@github.com> wrote:  
 
 


Update: the code in master now is fully TF2, @tboneai would you be so kind to check if the error persists?

**Comment by tboneai** [comment]
I am no longer seeing the mixed output and numbers repeating so that appears to be resolved. 
The results still include irrational numbers? in them 

0.00047587976
0.0002978705
-0.0042092577
9.056553e-05
0.0016669892
-0.001928445
0.000567548
-0.0015795492
1.4830381e-05
0.0040690303
0.0028433092

**Comment by w4nderlust** [comment]
Glad this is solved. We also introduced a cache freshness check that recreates the hdf5 wen needed, so that may have helped too. Not sure about irrational numbers, if you are referring to numbers returned in scientific notation, that's because they are particuarly small or big, but that should be fine, it's just a matter of visualization.
Closing, let me know if you have further issues.
