### ISSUE TITLE
Ludwig API does not have experiment method like CLI does.

### ISSUE THREAD

**Issue by Narragansett** [uber/ludwig#752]
Ludwig API does not seem to have an experiment method like CLI does. Yes? No? Documented?

**Comment by w4nderlust** [comment]
As you can see from the API page in the docs ( https://ludwig-ai.github.io/ludwig-docs/api/LudwigModel/ ) there is no exposes counterpart of the `experiment` CLI command at the moment.
It is easy to replicate it programmatically by using the `train` method and the `test` method, but if you actually need one I may consider introducing it as a feature request.

**Comment by w4nderlust** [comment]
This was indeed added in v0.3.
