### ISSUE TITLE
Save Luwdig Experiment in Google Colab

### ISSUE THREAD

**Issue by MarijnQ** [uber/ludwig#770]
Hi guys,
So thanks to Hamlet Basista I finally got a grip of Ludwig and I love it.
However, in this [article](https://www.searchenginejournal.com/automated-intent-classification-using-deep-learning-part-2/318691/) he uses the BERT encoder.
I have a laptop that does not have a GPU, so running the code takes me many hours. This is not a massive problem since the results are much more accurate.
I ran this code, but unfortunately I don't seem to be able to re-use my experiments. I can't seem to find it and after I close a Google Colab tab Ludwigmodel.load cant find the experiments I've run.

Can anyone give me advice on how to save experiments so I can use it for multiple predictions.
Thanks in advance!

**Comment by w4nderlust** [comment]
I wasn't aware of that article, thanks for sharing!

There are a few ways you can persist the files in Colab.
Check this: https://colab.research.google.com/notebooks/io.ipynb
The one i usually use is mounting the hdrive and then work with that, but there's other options too.
Closing, let me know if this doesn't solve your issue.

**Comment by MarijnQ** [comment]
Thanks for your response.
Colab has a weird thing that on the left side panel you can see the files and download them. But only the files. Not the folders.
Anyway, I just copied those, saved them in my Drive in a folder that I created just fir Python experiments and now I can reuse those.
Thanks!

**Comment by w4nderlust** [comment]
You are welcome!
