### ISSUE TITLE
Bert Ludwig: Program killed during training

### ISSUE THREAD

**Issue by muhammad-yasir** [uber/ludwig#773]
Hi there, 

I am using Python 3.6. and downloaded L-12 H-768 A-12 Bert config and vocab from github. When I train the program, it started training. On Epoch 1: it shows 1% progress for a while (about 20 minutes) and the program killed. I took the snapshot of program for better understanding. 
<img width="926" alt="Screen Shot 2020-07-16 at 22 48 57" src="https://user-images.githubusercontent.com/25621662/87663305-b7834f00-c7b7-11ea-8486-196fce24c8c8.png">

Could you please guide me in fixing the issue?

**Comment by w4nderlust** [comment]
From the screen it looks like you are running training on a CPU. That's very very slow with BERT (it will take several hours if not days, depending on your data).
That said, I don't see any error on screen so i don't know what is actually goign on.
What's your configuration? In particular how much RAM do you have? It is possible that with the default batch size the process is running out of memory, you should try reducing the batch size, but that will make training even slower.
I suggest you train in a setting where you have a GPU available.

**Comment by muhammad-yasir** [comment]
Thanks for the reply. Ram size is 8 GB. I will try on GPU

**Comment by w4nderlust** [comment]
With 8gb of ram, out of memory is very likely the issue. I would thance the training batch size in the model configuration. You can try 16 and if you still encounter the problem, decrease up to 1. let me know if this enables you to train.

**Comment by muhammad-yasir** [comment]
Thanks. Changing batch size to 16 enabled me to complete the training.

**Comment by w4nderlust** [comment]
You are welcome.
