### ISSUE TITLE
Record tensorflow version in description.json

### ISSUE THREAD

**Issue by danielduckworth** [uber/ludwig#799]
**Is your feature request related to a problem? Please describe.**

I've been cross checking the score_predictions.csv stored when running a Ludwig experiment with running the Ludwig predict from the CLI. I've been getting slightly different results in some cases and very different results in others.

**Describe the use case**
Including the tensorflow version along with the Ludwig version would make it easier to re-create the environment a model was trained in.

**Describe the solution you'd like**
Inclusion of the version of tensorflow in the description.json file.

**Additional context**
This may not be the solution to the inconsistent prediction results. But it will help isolate the issue.

**Comment by w4nderlust** [comment]
@danielduckworth  thanks for the suggestion, definitely adding it.
