### ISSUE TITLE
bug: ludwig.hyperopt module conflict

### ISSUE THREAD

**Issue by ifokeev** [uber/ludwig#805]
Because of the current naming there are no way to import from `ludwig.hyperopt` correctly
<img width="525" alt="Screenshot 2020-08-08 at 10 54 38" src="https://user-images.githubusercontent.com/2017148/89705404-c2b83d80-d965-11ea-8611-808d0e9798e1.png">

<img width="466" alt="Screenshot 2020-08-08 at 10 57 02" src="https://user-images.githubusercontent.com/2017148/89705417-ea0f0a80-d965-11ea-9453-7a6f63742257.png">

**Comment by w4nderlust** [comment]
Good catch, thanks!
