### ISSUE TITLE
bug: experiment ValueError on NaN

### ISSUE THREAD

**Issue by ifokeev** [uber/ludwig#807]
<img width="838" alt="Screenshot 2020-08-08 at 00 18 32" src="https://user-images.githubusercontent.com/2017148/89705768-77ebf500-d968-11ea-886f-f370f946560c.png">

If the dataset has some `null` values inside then this bug popping.
To prevent this there are a good idea to add new `drop_row` missing strategy inside the preprocessing.

**Comment by w4nderlust** [comment]
Merged #808 thank you!
