### ISSUE TITLE
model_definition_file in programmatic API takes an open file object instead of file path

### ISSUE THREAD

**Issue by lingxz** [uber/ludwig#81]
When I try to use the programmatic API, 
```
model = LudwigModel(model_definition={}, model_definition_file="some/path/to/file.yml")
```
it throws `AttributeError: 'str' object has no attribute 'get'`. It seems like when loading the model_definition_file, Ludwig is using `yaml.load`, which, according to the [pyyaml documentation](https://pyyaml.org/wiki/PyYAMLDocumentation), takes a byte string, a Unicode string, an open binary file object, or an open text file object. However, the ludwig documentation says that model_definition_file should be a file path. I tried passing in an open file object and it works. 

I think either the documentation needs to be changed or the model initialization should be modified to actually take a file path instead.

**Comment by msaisumanth** [comment]
Thanks for reporting this! We'll fix it and let you know.

**Comment by w4nderlust** [comment]
@lingxz can you please confirm that the bugfix solves the issue for you?

**Comment by lingxz** [comment]
yes this fixes it, thanks!

**Comment by Frankofoedu** [comment]
@lingxz  hello, this bug is still present in the pip install

**Comment by w4nderlust** [comment]
We are going to release a v0.1.1 with this and other bugfixes in the near future.

**Comment by sahand68** [comment]
I still used the pip install I get the same  bug.

**Comment by w4nderlust** [comment]
@sahand68 we haven't release v0.1.1 yet. As I already said, use the code on master.
