### ISSUE TITLE
TF2 is slower than TF1, improve speed

### ISSUE THREAD

**Issue by ifokeev** [uber/ludwig#819]
https://github.com/tensorflow/tensorflow/issues/33487

Getting the same result: epochs became longer because of switching to TF2.
I noticed also that it's using less memory than TF1, but slower epochs are killing this advantage.

TF 2.3 – less epoch time, but still slow.

Looks like there are some issues with `experimental_run_functions_eagerly`.
Very disappointed. Going to switch back to ludwig 0.2.2.8

**Comment by w4nderlust** [comment]
There are a couple optimizations we'll implement before releasing v0.3 that will hopefully improve speed (using Inputs for "compiling" the graph beforehand and disabling running functions eagerly. Will keep you posted. Although this is not really a Ludwig bug as you can understand.

@tgaddair FYI. We may want to use `experimental_run_functions_eagerly` only when `debug=True` for instance, but need to test how much it actually helps.

**Comment by tgaddair** [comment]
Hey @ifokeev @w4nderlust, my guess at this point is that not enough of the code is being compiled into a graph, and is instead running eagerly.  I will make it a priority to dig into this before the v0.3.0 release.  To help with repro, is there a particular dataset / config you're running with that's showing this behavior?

**Comment by ifokeev** [comment]
Hey @tgaddair ,
> To help with repro, is there a particular dataset / config you're running with that's showing this behavior?

I see @jimthompson5802 and you merged the fix, so the dataset is not needed anymore.
Thank you for the fix. Will try soon.

**Comment by tgaddair** [comment]
Thanks @ifokeev.  We'll wait to close the issue until we have confirmation that performance is where it should be for your model.
