### ISSUE TITLE
Installation error on ubuntu

### ISSUE THREAD

**Issue by pixxelfactory** [uber/ludwig#82]
I tried to install it on ubuntu, details:
- Ubuntu 18.04.1 LTS under Linux Subsystem / Win 10
- Python 3.6.7
- pip latest version (just installed)
- Installed all dependencies via pip manually

I get this error when trying to install ludwig:
Collecting ludwig
Could not find a version that satisfies the requirement ludwig (from versions: )
No matching distribution found for ludwig

**Comment by msaisumanth** [comment]
Can you try this:
pip install --index-url https://pypi.org/project/ludwig/ ludwig

This directly points to the ludwig repo. Also, are you using a virtual environment? 
You don't need to install the requirements separately if you're using pip to install Ludwig.

**Comment by pixxelfactory** [comment]
Hi, thanks for the response,
same error..
Well, as said, i am using Ubuntu on the Windows 10 Linux Subsystem (in wich i am running other stuff too, such as my lamp-stack)

**Comment by w4nderlust** [comment]
Unfortunately I don't have a windows machine to try it on, but i suspect it has to do with `pip`. I can suggest to install it by cloning the repo and installing it manually, as explained in [Getting Started](http://uber.github.io/ludwig/getting-started). Please let me know if following those instructions you are able to install it.

**Comment by pixxelfactory** [comment]
I think i found the solution:
Since on ubuntu by default there is python 2 and python 3, if you install pip via apt-get install python-pip, it will install the python2 version.
So what i did, is install python3-pip and installed ludwig via:
pip3 install ludwig
instead of:
pip install ludwig

Now the installation completed successfully (i've run the spacy-download command successfully too).
Maybe this information could be useful to someone else too.
However, there is another problem: if i try to write ludwig in the terminal it says "ludwig: command not found"..
BTW: It has nothing to do with Windows, i am replicating the steps within a Virtual machine running ubuntu 18.04..

Thanks and best regards

**Comment by w4nderlust** [comment]
Try to run `python3 -m ludwig.train -h`.
I'm not really sure of what happens with this configuration with python2 and python3 at the same time, I should strongly suggest you to create a virtual environment with `virtualenv -p python3`, install everything there and you should have no problem.
Please confirm if either the first command or installing within a virtualenv solves your issue.

**Comment by pixxelfactory** [comment]
That works! Thanks!
Well, its a stock-installation of ubuntu and they strangely bundle both python versions o.O
Nevertheless, putting it into a virtual environment works!
Case closed, thanks!
