### ISSUE TITLE
Latest master (TF2) doesn't honor validation_measure

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#822]
Ludwig from master with all requirements installed from fresh
yaml containing only one output classification feature
yaml containing validation_measure: accuracy in the preprocessing section

a combined output is generated with only the "loss" output value and no combined "accuracy", with the model being saved on loss improvements (also console output explicitly says so).
This could be either due to a missed interpretation of the yaml instruction, or (most probably) to the missing combined accuracy value in the output (and maybe it reverts to the default combined loss value).

**Comment by w4nderlust** [comment]
Thanks for pointing this out, looking into it.

**Comment by w4nderlust** [comment]
Can you provide the model definition?
ecuase if I try setting just the validation metric without changing the validation field I correctly get:
```
ValueError: The specificed metric accuracy is not valid. Available metrics for combined output features are: ['loss']

```

**Comment by w4nderlust** [comment]
Figured it out, it should work now, please confirm.

**Comment by carlogrisetti** [comment]
Hum... I still don't see an accuracy column in the combined section, and it's still not working, basing the training on loss instead of accuracy.

Here's my yaml 
[model_definition.zip](https://github.com/uber/ludwig/files/5078358/model_definition.zip)

**Comment by carlogrisetti** [comment]
FYI, the combined accuracy value is not generated in the logs either, since there is no corresponding value in the tensorboard visualizations. It's like it's not even being calculated within the "combined" measures

**Comment by w4nderlust** [comment]
The combined accuracy has been removed for the time being. The reason is that if you have say a numerical feature and a categorical feature, combined accuracy doesn't have a meaning. Plus the way we are calculating metrics right now is different and would make calculating combined accuracy tricky.
Still thinking about ways to reintroduce it before the release of v0.3 though, in particular if all output features have an accuracy value.
Combined loss should be used for the time being for that purpose, which is also the new default:
```
validation_field: combined
validation_metric: loss
```

Oh you are using validation_measure, while now it's validation_metric, we changed the naming convention, wherever it was measure now it's metric for consistency.

**Comment by carlogrisetti** [comment]
You should *really* put a warning to show that an unknown yaml parameter have been specified, or you'll have *LOTS* of "this doesn't work anymore" to reply with "we changed that in 0.3.0, read the docs"

Ok then, anyway I am hugely fond of the combined accuracy metric, and I would be OK in having it only when all output features have an accuracy output (otherwise I agree with you, it's nonsense to display an accuracy only on part of the prediction, whilist the loss is calculated on all of them)

**Comment by carlogrisetti** [comment]
PS: if you're not calculating a combined accuracy anymore... how the heck is ludwig supposed to decide whether to save the model or not, based on accuracy?

**Comment by w4nderlust** [comment]
either on combined loss (default), or on any metric of any output feature (including loss)

**Comment by carlogrisetti** [comment]
Oh ok.
In any case, specifying `validation_field: combined` (the default value you pointed out earlier) works fine, whilist specifying `validation_metric: loss` (which should already be the default value now) gives this error:

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\ludwig.exe\__main__.py", line 7, in <module>
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 125, in main
    CLI()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 66, in __init__
    getattr(self, args.command)()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 76, in train
    train.cli(sys.argv[2:])
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 825, in cli
    full_train(**vars(args))
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 361, in full_train
    debug=debug
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 532, in train
    **model_definition[TRAINING]
  File "c:\program files\python36\lib\site-packages\ludwig\models\trainer.py", line 302, in train
    only_of = output_features[0]
KeyError: 0

**Comment by w4nderlust** [comment]
This commit from yesterda https://github.com/uber/ludwig/commit/80ea6e99dfe6342cbb419e979b3f6ec5394825ca should have solved the issue. Please pull from master ;)
