### ISSUE TITLE
[bug] test_statistics calculates for the last epoch

### ISSUE THREAD

**Issue by ifokeev** [uber/ludwig#833]
https://github.com/uber/ludwig/blob/d70bc4aff35e6ac3c4a17a828e080e703e33bce6/ludwig/experiment.py#L388

The issue here that I see test/validation statistics for the last epoch,  not last improved. 
Is that a bug or the feature?

**Comment by w4nderlust** [comment]
Let me look inot it. Also, that part of the code will undergo quite some substantial reworking before v0.3 exits the alpha stage anyway, so this it is great that if this is an error we are catching it now.

**Comment by w4nderlust** [comment]
Can you please check the commit above? it should solve the issue.
If the model was saved during training, i.e. we have a way to recover the model saved at the epoch where max performance on validation is reached, we load it before runnign the prediction.
If the model was not saved during training, we can only use the model at the last epoch, which is what the training process returns.
Please confirm if this is ok for you.

**Comment by w4nderlust** [comment]
@ifokeev did you have time to check this out?
