### ISSUE TITLE
[Feature Request] add CLI command to convert LudwigModel to SavedModel

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#841]
Could be a nice addition, but I don't know how much effort does it take, and how much it would be appreciated by end users:

I think having the ability to one-shot convert the usual `LudwigModel` to a TF `SavedModel` format would be nice to have, even since I suppose it could be a quick addition for you to do.
I tried manually doing that with the model.save_savedmodel as per the unit tests example, but the test script assumes you're doing a training right before saving it, and I get stuck to `ValueError: Model <ludwig.models.ecd.ECD object at 0x000001F7C48E94E0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).`
My scenario (I actually have no need to use a SavedModel, but most probably will in the future) is to do all the training\comparing\testing\whatever within Ludwig, and only export the final and definitive model to a third party.
Most probable use would be to finally convert it to TFLite and consume it in a mobile solution.

Bonus points for having the output both in `SavedModel` and to subsequently also convert it to `TFLite` via https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_saved_model

**Comment by w4nderlust** [comment]
This is now added.

**Comment by carlogrisetti** [comment]
@w4nderlust just to let you know that you still have the card in "to do", and I think you can move it in done :)
https://github.com/uber/ludwig/projects/1#card-44109355

**Comment by w4nderlust** [comment]
Thanks :)
