### ISSUE TITLE
[Feature Request] Stratify on non-output feature

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#850]
I would like to be able to specify a stratify parameter on a feature that is not part of the output features of the model.
The scenario is that I want to randomly split my dataset with the force_split: true and split_probabilities parameters, but I want to be sure of having an uniform distribution of samples in all datasets, using a field I'm not going to define in the output features (but yes, if defined would have been a category type output).

Why I'm not using that field in the output features? Because it would be an unnecessary complication for the model to learn to predict it, since I'm not using that in my results, and on the other hand it is very useful because the different sample groups have different characteristics, that have all to be included in the training and validation (and test?) datasets to have a fair training.

**Comment by w4nderlust** [comment]
Right now there is a check if the column name is in output features, the reason is that we can actually stratify only on categories and binary values. I could include input features too, but in your usecase looks like there is an additional column in the dataset that is neither  an input nor an output feature, correct? In that case one thing I can do is to transform the value errors that arise from the name not being in output_features to a warning, would that make sense to you?

**Comment by carlogrisetti** [comment]
That's exactly my use case. I know the dataset has different properties based on a field I "humanly" know, but don't want to give it in input (because I won't have it in the actual input in production unless manually tagged) and I don't care about it in the output (so no need to waste neurons trying to predict that, and also I don't want it's loss/accuracy to affect training).

If that error/warning switch does the trick I'm up for it. It will be the user's responsibility to provide an actual category column and not a numerical one or similar (like it currently is if you're defining a category output feature on a numerical column)

**Comment by carlogrisetti** [comment]
Created PR #854 to "solve" this.

**Comment by carlogrisetti** [comment]
Everything's good... but there's the annoying warning popping up on model load when trying to predict... and in that case the stratify parameter means absolutely nothing so it shouldn't even be checked for.
It all works fine however, so it's just an aesthetic improvement on the outputs.

**Comment by w4nderlust** [comment]
mmm yes that same code is called when the model is loaded too and if stratify is outside inputs and outputs it will complain. i may replace stratify with none at saving time, but I don't know if the model will be loaded and trained again, in which case stratify may be useful.
So I would say let's live with that, and if you are very sure you don't want to train that model again, substitute the value of stratify with none in model definition inside the model directory you load from.
