### ISSUE TITLE
Ludwig serve doesn't work

### ISSUE THREAD

**Issue by Teladoc-juanse** [uber/ludwig#858]
I tried this in Google Collab and on my Mac.

*Environment*
- Google Collab : Python 3.6.9
- Mac : Python 3.7.6
- pip install 'ludwig[serve]'  done, no errors

`sudo -H pip install 'ludwig[serve]'               
Requirement already satisfied: ludwig[serve] in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (0.2.2.8)
Requirement already satisfied: pandas>=0.19 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (1.0.3)
Requirement already satisfied: tqdm in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (4.46.0)
Requirement already satisfied: Cython>=0.25 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.29.17)
Requirement already satisfied: numpy>=1.15 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (1.18.1)
Requirement already satisfied: scikit-learn in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.22.1)
Requirement already satisfied: PyYAML>=3.12 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (5.3.1)
Requirement already satisfied: absl-py in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.10.0)
Requirement already satisfied: tensorflow==1.15.3 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (1.15.3)
Requirement already satisfied: h5py>=2.6 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (2.10.0)
Requirement already satisfied: tabulate>=0.7 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.8.7)
Requirement already satisfied: scipy>=0.18 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (1.4.1)
Requirement already satisfied: uvicorn; extra == "serve" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.11.8)
Requirement already satisfied: fastapi; extra == "serve" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.61.1)
Requirement already satisfied: pydantic==0.32.2; extra == "serve" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.32.2)
Requirement already satisfied: python-multipart; extra == "serve" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from ludwig[serve]) (0.0.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.19->ludwig[serve]) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.19->ludwig[serve]) (2020.1)
Requirement already satisfied: joblib>=0.11 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from scikit-learn->ludwig[serve]) (0.15.1)
Requirement already satisfied: six in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from absl-py->ludwig[serve]) (1.15.0)
Requirement already satisfied: keras-applications>=1.0.8 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.0.8)
Requirement already satisfied: tensorflow-estimator==1.15.1 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.15.1)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.15.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.1.2)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (0.34.2)
Requirement already satisfied: astor>=0.6.0 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (0.8.1)
Requirement already satisfied: protobuf>=3.6.1 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (3.13.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (3.3.0)
Requirement already satisfied: grpcio>=1.8.6 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.31.0)
Requirement already satisfied: wrapt>=1.11.1 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (1.11.2)
Requirement already satisfied: gast==0.2.2 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (0.2.2)
Requirement already satisfied: google-pasta>=0.1.6 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.15.3->ludwig[serve]) (0.2.0)
Requirement already satisfied: uvloop>=0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from uvicorn; extra == "serve"->ludwig[serve]) (0.14.0)
Requirement already satisfied: click==7.* in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from uvicorn; extra == "serve"->ludwig[serve]) (7.1.2)
Requirement already satisfied: h11<0.10,>=0.8 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from uvicorn; extra == "serve"->ludwig[serve]) (0.9.0)
Requirement already satisfied: websockets==8.* in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from uvicorn; extra == "serve"->ludwig[serve]) (8.1)
Requirement already satisfied: httptools==0.1.*; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from uvicorn; extra == "serve"->ludwig[serve]) (0.1.1)
Requirement already satisfied: starlette==0.13.6 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from fastapi; extra == "serve"->ludwig[serve]) (0.13.6)
Requirement already satisfied: setuptools>=41.0.0 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.3->ludwig[serve]) (47.1.1.post20200604)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.3->ludwig[serve]) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.3->ludwig[serve]) (3.2.2)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.3->ludwig[serve]) (1.6.0)
Requirement already satisfied: zipp>=0.5 in /Users/macmini/opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.3->ludwig[serve]) (3.1.0)`

**Screenshots**
[Image](https://p479.p0.n0.cdn.getcloudapp.com/items/yAubJGg4/Image%202020-08-31%20at%209.30.09%20PM.png?v=e312a374ed052c06053cd6d0a783e841)

**Comment by w4nderlust** [comment]
you have t ospecify the path to the model, not to the experiment. In your specific case, add `/model` to the path you are providing.

**Comment by Teladoc-juanse** [comment]
I have the same problem : [https://p479.p0.n0.cdn.getcloudapp.com/items/X6uNKepR/Image%202020-09-01%20at%2010.23.31%20AM.png?v=bcb4256b9eaddfcd61b2457b6ffe1a46](url)

**Comment by Teladoc-juanse** [comment]
I still have the same problem [screenshot](https://p479.p0.n0.cdn.getcloudapp.com/items/X6uNKepR/Image%202020-09-01%20at%2010.23.31%20AM.png?v=bcb4256b9eaddfcd61b2457b6ffe1a46)

**Comment by w4nderlust** [comment]
Are you sure you are running from the virtual environment where you installed ludwig[serve]? Does the model directory contain the model files (weights, hyperparameters and train set metadata)?

**Comment by Teladoc-juanse** [comment]
Yes,  I used the same virtual environment. I installed FastAI and launched a server with the Ludwig API and it worked but when I use 
`ludwig serve` I always have the same issue.

Since I need to put into production 2 models at the same time I will keep the FastAI option, but it's a pity that the error thrown  by `ludwig` was not more explicit about the origin.

**Comment by w4nderlust** [comment]
This is the code that generates your error:
```
try:
    import uvicorn
    from fastapi import FastAPI
    from starlette.datastructures import UploadFile
    from starlette.requests import Request
    from starlette.responses import JSONResponse
except ImportError:
    logger.error(
        ' fastapi and other serving dependencies are not installed. '
        'In order to install all serving dependencies run '
        'pip install ludwig[serve]'
    )
    sys.exit(-1)
```

It means that you problem has to do with your environment and your dependencies.

Could you please try to open a python prompt and load those dependencies one by one? i expect one of them will fail, and we can figure out from there.

**Comment by w4nderlust** [comment]
Also I just pushed to master a commit that prints the full error: https://github.com/uber/ludwig/commit/42ed14f9183bf698c7a2ec382db5e235c0ab4557

Can you please install ludwig from master and try again?

`pip uninstall ludwig & pip install git+http://github.com/uber/ludwig.git`

**Comment by Teladoc-juanse** [comment]
Hello,
Since I was using FastAPI for the server I was not using `ludwig serve` anymore since this afternoon (Paris time). I tried what you suggested (the import of all the dependencies) and they passed so I tried `ludwig serve` again and it worked this time. However what I noticed when I was installing FastAPI manually is that Pydantic causes some problems during the installation and you have to try many times. So my best guess is that when you install FastAPI with `pip install ludwig[serve]` there's a dependency that doesn't install correctly hence causing the other problems.

Thanks for your prompt answer and help with this matter.

**Comment by w4nderlust** [comment]
I see, thank you for reporting on that.
Glad things worked out anyway :)
If you happen to be able to post here what error were you encountering without ht sudo -H I can try to dig deeper.
Thank you so much anyway!
