### ISSUE TITLE
Dockerfile has not been updated to reflect TF2 porting

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#865]
I know it's not core right now, but just to keep in mind that those need to be updated in the future.
Might need that for a test I'll do next week, and if so I could upgrade and check for issues.

https://github.com/uber/ludwig/blob/a8fe093581fa2e0b3a28cde9d2b73b5e6a7a630c/Dockerfile#L10

https://github.com/uber/ludwig/blob/a8fe093581fa2e0b3a28cde9d2b73b5e6a7a630c/Dockerfile_dev#L12

**Comment by tgaddair** [comment]
Thanks for raising the issue, @carlogrisetti.  Should be pretty straightforward to update following the structure of [.travis.yml](https://github.com/uber/ludwig/blob/master/.travis.yml).
