### ISSUE TITLE
ModuleNotFoundError: No module named 'en_core_web_sm' while training a dataset

### ISSUE THREAD

**Issue by ashoksrinivas** [uber/ludwig#88]
Getting No module found 'en_core_web_sm' while training dataset

I ran following command
```
ludwig train --data_csv path/to/camera_dataset.csv --model_definition "{input_
features: [{name: Model, type: text}], output_features: [{name: Price, type: numerical}]}"
```
Error Screenshot
![image](https://user-images.githubusercontent.com/23184429/52831706-98cce480-30fb-11e9-8912-fd89ce5cc56c.png)

Sample Data set screenshot
![image](https://user-images.githubusercontent.com/23184429/52831759-cfa2fa80-30fb-11e9-8f9b-822d216d4589.png)

**Comment by w4nderlust** [comment]
As explainedin the readme and in [getting started](https://uber.github.io/ludwig/getting_started/) you have to downoad the spaCy model:
```
python -m spacy download en
```

**Comment by ashoksrinivas** [comment]
Thanks ...that worked...but stuck in issue https://github.com/uber/ludwig/issues/97
