### ISSUE TITLE
API documentation shows wrong keyword argument for predict

### ISSUE THREAD

**Issue by lingxz** [uber/ludwig#89]
Seems like the [example here](https://uber.github.io/ludwig/api/#ludwigmodel-class) for the predict API is wrong. It says the argument is `dataset_csv` and `dataset_df` when it should be `data_csv` and `data_df`. It's correct in the [later part of the docs](https://uber.github.io/ludwig/api/#predict) though.

**Comment by w4nderlust** [comment]
Thanks for noticing it. I fixed it.
