### ISSUE TITLE
Column Features

### ISSUE THREAD

**Issue by YassLight07** [uber/ludwig#915]
Hello,

Can you please give me an example for each of the following feature types: SET and BAG. You only give an example for the "vector" type. It would be great to do the same for all column types.

Thank you

Kind regards,

Yassin

user guide: https://ludwig-ai.github.io/ludwig-docs/user_guide/#spacy-based-word-format-options

**Comment by w4nderlust** [comment]
@YassLight07 thanks for asking this question. I updated the source of the user guide to include this information. It will be visible the next time the website is updated.

This is what I added:
Set features are expected to be provided as a string of elements separated by whitespace, e.g. "elem5 elem9 elem6".
bag features are the same, but some elements may be present more than once.

Closing this issue, but feel free to keep asking questions.
