### ISSUE TITLE
0.3.0 does not allow to evaluate a specific dataset split

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#927]
I don't know if this is wanted or not, because it seems a backwards step to elimitate this, but in 0.3.0 there is no --split parameter anymore. I understand that someone having separate train, vali and test datasets is not impacted, but if you're using a single dataset file this could be problematic.
Am I missing something (like some sort of strange yaml parameter somewhere) or is that feature removed?
I tried looking in the CLI parsers but found none that could be of use in this sense.

Thanks!

**Comment by carlogrisetti** [comment]
Oh... just for a reference, this happened during the great purge within https://github.com/uber/ludwig/commit/b7a1ade7b7ac4c835f31877cd532d3fe0deb1bbc

**Comment by w4nderlust** [comment]
Yes the functionality was removed for simplicity.
v0.3.0 is more API-centric, and the API now returns the preprocessed data when you run train() so you can run evaluate and predict on the split you want programmatically.
In #924 I reintroduced the parameter, this time in experiment() calling it `eval_split`.
I believe your main concern is with predict and evaluate CLI command, right?
I can re-add the parameter in predict() and evaluate() so that it can be used also in the CLI commands.

**Comment by carlogrisetti** [comment]
The only use case I can think of is within evaluate, to run comparisons on the test dataset across multiple models. (Or validation, if test is not used).

On a side note, how should predict use the split parameter? I don't see a scenario on when you would want to run predict on part of the dataset, having a dataset splitted between training, validation and test, which seem unuseful in a "predict" situation.

**Comment by w4nderlust** [comment]
The logic is 99% the same for predict and evaluate, and as I'm adding it back to evaluate will add it back to predict too, but I agree, it makes less sense. It just makes it handy if you have an already preprocessed hdf5 file.

**Comment by carlogrisetti** [comment]
Oh well, if it's so convenient I agree... There will always be that special someone who will make use of it :)

Thanks

**Comment by w4nderlust** [comment]
This PR addresses the issue: #929

**Comment by w4nderlust** [comment]
Merged

**Comment by carlogrisetti** [comment]
@w4nderlust actually I didn't have the time to test this, but it doesn't seem good to me (partially at lease)
This is the output I get when trying to run evaluate with a specific split, having an .hdf5 already generated from the training session. If I don't use the split parameter, it works like it's supposed to.
It seems like you changed the tag under which you save the "tag" representing the split in the hdf5 file, or anyway it is different between training and prediction.

Found hdf5 and meta.json with the same filename of the input file, using them instead
Loading data from: dataset.hdf5
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\ludwig.exe\__main__.py", line 7, in <module>
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 146, in main
    CLI()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 72, in __init__
    getattr(self, args.command)()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 87, in evaluate
    evaluate.cli(sys.argv[2:])
  File "c:\program files\python36\lib\site-packages\ludwig\evaluate.py", line 284, in cli
    evaluate_cli(**vars(args))
  File "c:\program files\python36\lib\site-packages\ludwig\evaluate.py", line 127, in evaluate_cli
    debug=debug
  File "c:\program files\python36\lib\site-packages\ludwig\api.py", line 791, in evaluate
    include_outputs=True
  File "c:\program files\python36\lib\site-packages\ludwig\data\preprocessing.py", line 1522, in preprocess_for_prediction
    dataset[SPLIT]
KeyError: 'split'

**Comment by w4nderlust** [comment]
It looks like the hdf5 case was the only one that did not work, this should fix it https://github.com/uber/ludwig/pull/1003 . Please confirm.

**Comment by carlogrisetti** [comment]
Confirmed working
