### ISSUE TITLE
error installing on win 7 - which component of MS Visual C++  is needed ?

### ISSUE THREAD

**Issue by AhmadMuhammdi** [uber/ludwig#94]
Hello ,  
when trying to install Ludwig on win 7 
Python 3.6.8 used
I started with this command 
    
>pip install ludwig

it goes well for some time then it show the below error , it says requires  Microsoft Visual C++ 14,so which component of it does it need?

   > copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.6\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.6\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

thanks 
Ahmad

**Comment by ksteinfe** [comment]
Hi Ahmad,
In my experience, the Microsoft Visual C++ 2015 Redistributable is what you're looking for (I'm on Windows 10, so what works for me may not for you). 

Go to [Visual Studio Downloads](https://visualstudio.microsoft.com/vs/older-downloads/), under Redistributables and Build Tools, select Microsoft Visual C++ 2015 Redistributable Update 3.

**Comment by w4nderlust** [comment]
This is related to installing `ujson` on windows machines, it's not a Ludwig error. @ksteinfe answer solves this issue.

**Comment by AhmadMuhammdi** [comment]
Thanks ksteinfe , w4nderlust ,   
now completed setup well

**Comment by jonathanrjpereira** [comment]
I'm getting a setup failed error after trying to install Microsoft Visual C++ 2015 Redistributable Update 3 as mentioned by @ksteinfe 

`One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file. `

`0x80070666 - Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel. 
`

If I replace the existing verison with this, will it break some of the other programs I have already installed?

**Comment by w4nderlust** [comment]
@jonathanrjpereira unfortunately I cannot know about that.

**Comment by ChromoBacterium** [comment]
> I'm getting a setup failed error after trying to install Microsoft Visual C++ 2015 Redistributable Update 3 as mentioned by @ksteinfe
> 
> `One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file. `
> 
> `0x80070666 - Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel. `
> 
> If I replace the existing verison with this, will it break some of the other programs I have already installed?

No it won't. The program is used for building. Once built, it is no longer necessary.
