### ISSUE TITLE
preprocessing methods

### ISSUE THREAD

**Issue by YassLight07** [uber/ludwig#950]
Hello,

What preprocessing methods are applied to data before the training phase? It would be nice to have a brief summary of all these steps in the doc.  By preprocessing, I mean: one-hot-encoding, normalization, imputation, etc.

Thank you,

Yassine

**Comment by w4nderlust** [comment]
The docs contain such information.
Check the [Preprocessing section in the User Guide](https://ludwig.ai/user_guide/#preprocessing) and then the preprocessing sections of each datatype in the user Guide.
If you still have questions, please feel free to ask them here. Closing in the meantime.
