### ISSUE TITLE
Evaluate not found

### ISSUE THREAD

**Issue by Juggernaut1997** [uber/ludwig#952]
INFO:tensorflow:Restoring parameters from results/simple_image_experiment_single_model/model\model_weights

AttributeError                            Traceback (most recent call last)
<ipython-input-18-1e5cdef68648> in <module>
     15 
     16 # make predictions
---> 17 test_stats, pred_df, _ = model.evaluate(dataset=test_df, data_format='df', collect_predictions=True, collect_overall_stats=True)
     18 
     19 # collect test statsitics

AttributeError: 'LudwigModel' object has no attribute 'evaluate'

**Comment by w4nderlust** [comment]
This is not how we want the issues to be provided.
Pasting an error without any context makes our work of trying to help you solve your issues very hard and is very disrespectful toward us.
We are not a search engine, nor a pattern matching answer bot, we are human being that put effort and passion in an open source project for the benefit of everyone.
Please provide context of what you are trying to do, what commands are you using, configuration, data etc. although this is likely just you trying to load a Ludwig v0.2 model in v0.3...

**Comment by Juggernaut1997** [comment]
So, I was trying the MNIST example you have provided. But while running its visualization part, I got stuck at the line where model.evalute starts.

**Comment by jimthompson5802** [comment]
@Juggernaut1997   Just for clarity when you write "trying to MNIST example you have provided," are you referring to the Jupyter notebook called `examples/mnist/visualize_model_test_results.ipynb`?    For me, this notebook works.

It will help me if you can be more specific on what example file you are trying to run.

One last thing, if you are running the Jupyter notebook, please do the following in a notebook cell and send the response.  You should see the answer as `0.3`.
![image](https://user-images.githubusercontent.com/1425269/95911560-a4106180-0d6f-11eb-92e0-0149321356e2.png)

**Comment by w4nderlust** [comment]
@Juggernaut1997 if you could please be precise about the error and how to reproduce it we can look into it. Also in my case the notebook works, so I'm trying to figure out what is actually the issue.

**Comment by w4nderlust** [comment]
@Juggernaut1997 as you closed the issue I believe you solved it, could you please post here about the solution so that is some one else encounters your problem they can use your solution too?
