### ISSUE TITLE
FileNotFoundError model_hyperparameters.json

### ISSUE THREAD

**Issue by aminaBm** [uber/ludwig#953]
When loading a trained model using LudwigModel.load

  `  model = LudwigModel.load("/LudwigModels/model")`

I got this error :

FileNotFoundError: [Errno 2] No such file or directory: '/LudwigModels/model/model_hyperparameters.json'

however, when I open the directory I can found it

it works perfectly when I load other models

**Comment by w4nderlust** [comment]
Are you sure the path is correct? It would be weird to have a `LudwigModels` directory in the root.

**Comment by aminaBm** [comment]
@w4nderlust this is the path _/LudwigModels/sentiment/2/results/api_experiment_run/model_

**Comment by kanishk16** [comment]
@aminaBm Did you try using this path while loading the model? If not try and let us know if you still run into issues.

**Comment by w4nderlust** [comment]
> @w4nderlust this is the path _/LudwigModels/sentiment/2/results/api_experiment_run/model_

It is an absolute path, so you have the LudwigModels in the root of you file system?
If that is true, are you sure you have the rights to access the files? (by default the owner is likely going to be root).

Maybe you could consider placing the models in user space, like `~/LudwigModels/...` and the issue will likely be solved.

**Comment by aminaBm** [comment]
now it shows `No training data is provided!`

**Comment by w4nderlust** [comment]
Probably you have the same issue with th data, try placing it in a place where it can be accessed.

**Comment by w4nderlust** [comment]
@aminaBm I'm guessing you solved the issue, could you please post the solution so that other people with the same issue would know how solve it?

**Comment by aminaBm** [comment]
@w4nderlust in fact, I thought the problem was solved when it wasn't, although I retrained the data still showing me the same "no training data" message

**Comment by aminaBm** [comment]
[the solution](https://github.com/uber/ludwig/issues/991#issuecomment-721381093)

**Comment by kaykumar** [comment]
When I faced this , I was doing this:

train_stats, _, model_dir  = model.train(dataset=df)
model = LudwigModel.load(model_dir)

Solution is:

model = LudwigModel.load(model_dir **+ "/model"**)

Hope it will save some time for someone.

Thanks,
Kamal

**Comment by w4nderlust** [comment]
@kaykumar thanks for sharing.
One detail from the documentation here https://ludwig.ai/latest/user_guide/api/LudwigModel/#train
is that the returned directory is not indeed the directory of the model, but the `output_directory` which contains a bunch of things: a description or the training run, the training statistics and the model directory itself. it is documented in the description of the train command line command here https://ludwig.ai/latest/user_guide/command_line_interface/#train but this is good feedback that we may want to include this kind of information in the API documentation too (@dantreiman @justinxzhao FYI).

So a slightly improved snippet (that is also os agnostic) for people ending here is the following:
```
train_stats, _, output_dir = model.train(dataset=df)
model = LudwigModel.load(os.join(output_dir, "model")
```
