### ISSUE TITLE
Iterating over tf.Tensor is extremely slow in set_feature postprocess

### ISSUE THREAD

**Issue by catr1ne55** [uber/ludwig#963]
**Describe the bug**
"Postprocess" function in `set_feature.py` is super slow because of one loop over tf.Tensorflow prediction results

**To Reproduce**
1. Create any big model with "set" output feature (my case was multilabel (tags) classification with ~10000 train dataset) 
2. run "predict" on big dataset (~3000 rows to predict on and ~10000 tags in the `idx2str` dict after training)
3. "postprocess" function will be executed for quite a long time (20-30 times longer than the prediction process itself)

**Expected behavior**
Iteration in "postprocess" can be done way faster if `numpy()` will be used for PREDICTIONS ([here](https://github.com/uber/ludwig/blob/master/ludwig/features/set_feature.py#L258), as well as it is already done for [PROBABILITIES](https://github.com/uber/ludwig/blob/master/ludwig/features/set_feature.py#L270)

Simple code snippet to reproduce:

```
import tensorflow as tf

import sys
import datetime

def print_now(msg):
    print(datetime.datetime.now(), ': ', msg)
    sys.stdout.flush()

pred_set_fake = tf.zeros([10000,], tf.int32)
print_now(pred_set_fake)

print_now('start 1')
for i, pred in enumerate(pred_set_fake):
    1 + 1
print_now('end 1')


print_now('start 2')
for i, pred in enumerate(pred_set_fake.numpy()):
    1 + 1
print_now('end 2')
```

output is:

```
/data# python test_iter.py 
....
2020-10-20 06:11:03.063242 :  tf.Tensor([0 0 0 ... 0 0 0], shape=(10000,), dtype=int32)
2020-10-20 06:11:03.063733 :  start 1
2020-10-20 06:11:04.344766 :  end 1
2020-10-20 06:11:04.344881 :  start 2
2020-10-20 06:11:04.347144 :  end 2
```

1.3 sec vs 0.003 sec...

and since there are On^2 complexity (for in for), it is becoming a bottleneck in a whole "predict" method of the model...

**Environment (please complete the following information):**
- OS: tensorflow:2.3.0 docker image
- Python version 3.6.9 in tensorflow:2.3.0 docker image
- Ludwig version v0.3

**Additional context**
It probably can be relevant for other types of features as well, but since I am currently working with `set` only, I can't be 100% sure

**Comment by tgaddair** [comment]
Thanks for the detailed issue @catr1ne55.  Can you take a look at #964 and let me know if it addresses the performance issues for your model?

**Comment by catr1ne55** [comment]
Thanks for the quick fix @tgaddair! Now the performance issue is resolved.
