### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by JDface** [uber/ludwig#967]
Hello:

I have simple questions. I want to use ludwig in my Jupyter Notebook and i need help with examples how to do that.

If ludwig cannot be imported in jupyter notebook, please let me know.

Any help is greatly appreciated.

Thanking in advance.

**Comment by jimthompson5802** [comment]
@JDface It possible to use Ludwig in a jupyter notebook.  There are several example notebooks in the Ludwig's example directory.  Here is one example: https://github.com/uber/ludwig/tree/master/examples/kfold_cv

**Comment by JDface** [comment]
thank you for your help & link, I appreciate you.
