### ISSUE TITLE
Weird in_memory behavior results in whole .hdf5 load at startup

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#977]
Hello, can you just confirm me that the documentation is still up to date and this:

![image](https://user-images.githubusercontent.com/4464640/97336653-8b2fa200-187f-11eb-9311-d56624d8493c.png)

is still a valid in_memory declaration? (I correctly see it applied in the hyperparameters sumup that ludwig prints out prior to actually doing anything, but I just wanted to check)
I have only a single image input feature, and I also tried declaring that inside of the image feature (under preprocessing: in_memory: false) but every time I start the training it seems to be loading the whole .hdf5, disregarding the in_memory: false request.
I expected it to almost skip the .hdf5 loading, and just start training by loading each batch "just-in-time".

Documentation here https://ludwig-ai.github.io/ludwig-docs/user_guide/#image-features-preprocessing is not so clear on how to work it out, and the sample does not include all the default parameters like with many other features (which would include the in_memory correct declaration also).

Full disclaimer: I created the .hdf5 with a training that did not have in_memory: false, so if something is saved within the .hdf5 itself that prevents it to correctly doing the in_memory thing, that's the issue, but I don't have the resources to repro\retry a full .hdf5 rebuild right now

**Comment by w4nderlust** [comment]
Your config should be correct. Let me look into this.

**Comment by carlogrisetti** [comment]
Aaaaand this does not happen anymore after reinstalling a whole lot of packages...
Might have been environment-related. Sorry for reporting this.

**Comment by carlogrisetti** [comment]
Oh... I found out why... I was setting `in_memory: false` as a global preprocessing parameter, and not as a parameter of the `image:` class.
Sorry for the inconvenience!

PS: this brings me more and more towards some system of a blocking error telling you that you tried to set a non-existent parameter

**Comment by w4nderlust** [comment]
Yes that's what i was pointing out in my previous message :)
And again yes, as we are converging towards a more stable syntax for the config file, we are considering introducing some (ideally lightweight and sustainable) mechanism for pointing out errors in the model definition. Let me actually add a card in the project for this.
