### ISSUE TITLE
Cannot perform evaluation on trained image model using either resnet or stacked_cnn

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#987]
CLI evaluation on a model trained with a resnet input feature crashes.
This works correctly on a numerical\categorical input. Only an image input feature seems to have this issue, either with resnet encoder or stacked_cnn encoder (I tried both)

Attached the sample model definition I used and the stack dump

[model_definition.txt](https://github.com/uber/ludwig/files/5476557/model_definition.txt)
[stackdump.txt](https://github.com/uber/ludwig/files/5476547/stackdump.txt)

**Comment by w4nderlust** [comment]
@carlogrisetti looking into this. Can you check if `predict` works?

**Comment by carlogrisetti** [comment]
For now I can sell you that I can run inference from the APIs, so calling ludwigmodel.predict works fine in any scenario tested (both resnet and stacked_cnn)
Also the evaluation within the training cycle seems to always works fine (but since I'm having issues in converging to a solution on a project I'm working on, I'm not so sure about that... At least it's not crashing and results don't look suspicious)

**Comment by w4nderlust** [comment]
Looked into it. generated a dataset, trained a model, run predict and run evaluate from cli and everything works.
I'm guessing there's something else going on, could you please create a reproducible example using synthetic data? (now there's a symthesize_dataset command).

**Comment by carlogrisetti** [comment]
Sure, there has to be something weird since I can't evaluate older models too, I found out. This means it's not specific to the model/ludwig version, but to my environment (I tried rolling back the code to 0.3.0-rc1 with no avail, but I didn't roll back all the other pip packages in the dependencies).

Might be something related to pip packages versions: i recently upgraded all packages with the eager parameter, forcing pip to install the most up to date package (within the requirements.txt constraints of each package, of course).

I'll try both generating the synthetic dataset to repro, and to look into packages min/max versions.

**Comment by carlogrisetti** [comment]
I uninstalled and reinstalled several components, even trying a support matrix between trained and evaluated versions of tensorflow... and as soon as i tried downgrading to tensorflow 2.2.0 i was able to evaluate models trained with 2.2.0. I was not able to evaluate models trained with 2.3.1 thou... After some fiddling around it all works now, but I can't repro the issue\solution steps. I have another machine that has the same issue, and I highly suspect the root cause are the tests I've done for the export_tflite PR, which I had done using tensorflow nightly... maybe something was left dirty by that package even after uninstall, and it got cleaned only with the tasks I've done today.

Will try to repro on the other machine and report back :)

**Comment by carlogrisetti** [comment]
On the second machine nothing I tried working... aligning versions, removing and adding packages...
I have the two machines perfectly aligned on the same pinned versions... but that did not work.
I was using a different model for testing (the real one on the production machine and a different, testing one, on the test machine), and using the same "test" model it works on both machines. I cannot port the production model to the test machine so I'm now trying to rebuild all the production non-working model from scratch (dataset et al) because I suspect there is something related to versions used when training.

**Comment by carlogrisetti** [comment]
I can't find out what is going wrong with that machine or how I fixed it on the other one.
I'll update if I find out how to fix that and do not resort to destroying the whole machine :)

**Comment by w4nderlust** [comment]
Ok so closing for now, if you end up replicating the issue open to reopen and llok into it ;)
