### ISSUE TITLE
"No training data is provided!" message while prediction

### ISSUE THREAD

**Issue by aminaBm** [uber/ludwig#991]
I loaded and saved my trained model
```
from ludwig.api import LudwigModel
model = LudwigModel.load("./model")
model.model.save_savedmodel('./savedModel')
```
and when I try to predict, it shows **No training data is provided!**
`predictions = model.predict(data_csv = "tweet.csv")`

**Comment by tgaddair** [comment]
Hey @aminaBm, can you try changing the param `data_csv` to `dataset` and let me know how that goes?

**Comment by aminaBm** [comment]
@tgaddair the same message, it doesn't change anything

**Comment by aminaBm** [comment]
it works perfectly now thank you
